### ISSUE TITLE
Adding OAuth Support to Swagger

### ISSUE THREAD

**Issue by ivanhawkes** [emicklei/go-restful#108]
I'm looking to open access to my API via OAuth2. Currently, I can't find any method of outputting the required fields to the swagger document as detail in http://developers-blog.helloreverb.com/enabling-oauth-with-swagger/

Is support for this planned presently? Being able to build the OAuth requirements into the Swagger docs would be a definite boon for my work.

**Comment by emicklei** [comment]
see https://github.com/emicklei/go-restful-openapi
