### ISSUE TITLE
Add support for Swagger 2.0

### ISSUE THREAD

**Issue by emicklei** [emicklei/go-restful#157]
http://swagger.io

**Comment by emicklei** [comment]
The current swagger package has a dependency on go-restful because it includes the Swagger service that can serve an api listing (and declarations) dynamically. For spec 2.0, I am considering splitting this up such that the swagger spec and builders can be used by other rest frameworks.

**Comment by emicklei** [comment]
The modelBuilder struct is an important and complex part of the swagger package. Currently, it is an internal (non-exposed) type and therefore not user-pluggable (with the exception of the recent ModelBuildable interface).  I think a new design should allow for more customizations in both the Model building process as well as the ApiDeclarations (e.g. Authorizations).

**Comment by emicklei** [comment]
I propose to create a new repository and the following packages:

**github.com/emicklei/swagger/v1**
this package will have a "in-sync" copy of the current go-restful/swagger models and builder, spec version 1.2

**github.com/emicklei/swagger/v2**
this package will implement the same models and builder according to spec version 2.0

Code that is required to integrate swagger/v2 with the current go-restful will be become available in go-restful/swagger/v2. By integration I mean translating Route information into ApiDeclarations etc.

**Comment by fortytw2** [comment]
Any progress on this? The current release of `swagger-ui` - `v2.1.1` doesn't seem to be able to parse the current swagger exposed by `go-restful`

**Comment by emicklei** [comment]
Thank you for reporting this. Is this because the JSON is not conform 1.2, the UI has a bug or the UI simply no longer support this.

As for progress on v2.0, see https://github.com/emicklei/swagger2 , but this is only an initial setup.

**Comment by stellentus** [comment]
Would you appreciate help with this enhancement? I might be able to work on it, though I'm pretty new to Swagger.

**Comment by emicklei** [comment]
@stellentus , yes any help is welcome. 

I had the following strategy in mind:
- define all the structs, including short comments 
- defined list structs for arrays, they have a map api (kind of a orderedhashmap), see swagger.ModelList
- create a new ModelBuilder with an improved public api
- port all the model tests from the current package to get an equal or better coverage
- create a go-restful/swagger2 package for the integration
- port all the service tests

**Comment by stellentus** [comment]
Thanks. I'm not sure yet if I'll be able to work on it, but I'll post again if/when I start to let you know.

**Comment by casualjim** [comment]
any objection to solving this with https://github.com/go-swagger/go-swagger

**Comment by dustymabe** [comment]
+1 for swagger 2.0 support

**Comment by emicklei** [comment]
see https://github.com/emicklei/go-restful-openapi
