### ISSUE TITLE
Support request schema validation

### ISSUE THREAD

**Issue by bgrant0607** [emicklei/go-restful#165]
go-restful has all the information it needs to validate request bodies. It would be great if we could provide that feature to our users to catch malformed requests earlier.

See:
https://github.com/GoogleCloudPlatform/kubernetes/pull/2492

/cc @brendandburns

**Comment by gogames** [comment]
This feature is extremely helpful for writing elegant code. Would you provide any example? I am tired of validating if some json field is missing by unmarshal all inputs to map[string]interface{} then unmarshal to what I want. Tired of that.

**Comment by emicklei** [comment]
yes, agree.  I was planning to work on that ; too busy lately doing other stuff.

**Comment by emicklei** [comment]
anybody interested in this feature?

**Comment by bgrant0607** [comment]
Kubernetes will implement it's own solution to this. We have some special schema needs.

cc @mbohlool

**Comment by lmtwb** [comment]
@emicklei hello,  Does schema validation support this feature currently?，I think it can be developed with "github.com/go-playground/validator/v10"

**Comment by emicklei** [comment]
no interest for more than a year, lets close this
