### ISSUE TITLE
Swagger improvements external handler

### ISSUE THREAD

**Issue by vimdude** [emicklei/go-restful#166]
We are using gorestful and swagger and there are small modifications we would like to make to the api declaration map. We don't want to change your swagger package all the time. We currently do the following:

1. Changed Config to have an other field called ExternalHandler which is an instance of an interface called:
type SwaggerExternalHandlerInterface interface {
        PatchApiDeclarationMap(apiDeclarationMap *map[string]ApiDeclaration{})
}
2. On RegisterSwaggerService, we added the following after // Build all ApiDeclarations loop:
        if config.ExternalHandler != nil {
                config.ExternalHandler.PatchApiDeclarationMap(&sws.apiDeclarationMap)
        }

3. Then we pass our own interface to ExternalHandler On your method  RegisterSwaggerService:
 config := swagger.Config{
                WebServices:     container.(*restful.Container).RegisteredWebServices(),
                ExternalHandler: SwaggerPatch,
        }

If possible to give us this nice feature, it'll help us a lot. It won't be much work as we already do it, I can submit a pull request if necessary.

Thank you for your hard work.

**Comment by emicklei** [comment]
@vimdude could you please compose a pull request for this feature? (keeping the name ExternalHandler is fine)
