### ISSUE TITLE
Router does not use Content-Type if Content-Length not supplied

### ISSUE THREAD

**Issue by dkolbly** [emicklei/go-restful#170]
I have a client that is sending data using `multipart/form-data` content type and is not supplying a content-length because that is not easily determinable.  My go-restful server defines two handlers for that path, one with a `Consumes("application/json")` and one with a `Consumes("multipart/form-data")`.  But go-restful does not appear to be respecting the consumes clause and picks the first defined route despite the correct specification of the content-type.

I believe [this line](https://github.com/emicklei/go-restful/blob/master/jsr311.go#L60) in `jsr311.go` is causing the problem, since in this case the `httpRequest.ContentLength` is `-1` and so it is skipping the check by contentType.

I have a patch that changes it to `httpRequest.ContentLength != 0` but I'm not sure if that's the right fix or if I'm missing something else.

**Comment by nikhiljindal** [comment]
From https://jsr311.java.net/nonav/releases/1.1/spec/spec3.html, "Obtain the media type of the request. If the request does not contain a Content-Type header then use application/octet-stream"
Server should always do the content-type check. "application/octet-stream" should be used as the default value if the request does not have a content-type. Hence the current code and the proposed fix both seem wrong.

Here is what we can do:
contentType := httpRequest.Header.Get(HEADER_ContentType)
if httpRequest.ContentLength == 0 {
  contentType = "application/octet-stream"
}
// Compare contentType with Content-Type accepted by the server.

**Comment by emicklei** [comment]
I wonder whether this behavior is specific to jsr311, i.e. will it become router impl specific in go-restful.

**Comment by emicklei** [comment]
@nikhiljindal , please verify the change. Feel free to reopen if problems occur

**Comment by wuub** [comment]
@emicklei AFAICT this change introduced a very serious regression for GET requests.
A standard GET looks like this:
```
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, compress
Host: [Host]
User-Agent: [U-A]
```

No Content-Type and no Content-Lenght, as expected. In such case go-restful sets the Content-Type to `application/octet-stream`, which at least in theory is RFC compliant. But then it tries to validate this Content-Type against a list specified in .Consumes(), which causes GETs to error with 415 in almost all non-trivial cases.

I'm pretty confident that requests with empty body should not be checked against .Consumes() list,  and GET/HEAD/OPTIONS  should probably  not be checked against .Consumes()  at all.

What do you think?

**Comment by wuub** [comment]
A test for this problem here: https://github.com/grupawp/go-restful/commit/267fd225c7f1da239e1e4fc0da818acf6d8b4582

**Comment by emicklei** [comment]
Thank you for pointing this out.  I must admit that I wasn't quite sure about the test. I will study your solution asap and merge if ok.

**Comment by dkolbly** [comment]
@wuub @emicklei Please note that an empty body is not the same thing as lacking a Content-Length header; clients streaming their data will not supply a Content-Length at all and may use a Transfer-Encoding such as `chunked` instead.  That was my original issue, in fact.
