### ISSUE TITLE
Allow Fields to be hidden or synthesized

### ISSUE THREAD

**Issue by DylanLukes** [emicklei/go-restful#171]
Say you have a decently complicated `User` model, including `CreatedAt`, `UpdatedAt`, etc fields.

It doesn't make sense to have to provide these when creating a `User`, and it also doesn't make sense to have a separate structure representing just the parts of a `User` that should be necessary for construction (one might call that a `UserSpec`).

I think the nicest solution is something like this. I included some other struct tags to show how it might work in parallel with them.

```go
type User struct {
  ID int64 `gorm:"column:id; primary_key:yes" restful:"synthesized"`
  ...
  CreatedAt time.Time `restful:"synthesized"`
}
```
What this means is that, for instance, these fields should not be shown in Swagger documentation, and any validation on them should occur *after* relevant handlers run (to check they were generated, for instance).

Thoughts? This is really the only issue I'm having with go-restful so far, otherwise great work!

**Comment by emicklei** [comment]
Have a look at the recent addition of the PostBuildDeclarationMapFunc. Feel free to reopen if you need more.

**Comment by dkiser** [comment]
@emicklei - are there any examples of using `PostBuildDeclarationMapFunc` to do exactly what @DylanLukes is proposing here?

Trying to figure out how to redact certain fields when Creating a resource verses Returning a resource.

**Comment by emicklei** [comment]
I do not have an example of this yet. I checked the feature commit and it does not even include a test.  There should be at least one example, i think
