### ISSUE TITLE
CORS and OPTIONSFilter not working together

### ISSUE THREAD

**Issue by jcw9930** [emicklei/go-restful#174]
Some browser are doing an OPTIONS request prior to special HTTP methods (like DELETE). The restful-CORS-filter example states two wsContainer.Filter() calls to deal with this. 

But I find only the first wsContainer.Filter() invocation works, so depending whichever comes first, I get:

jan@localhost ~ $ curl -H "Origin: http://example.com" -i -X OPTIONS localhost:8008/foo
HTTP/1.1 200 OK
Allow: DELETE
Date: Tue, 13 Jan 2015 14:04:13 GMT

or

jan@localhost ~ $ curl -H "Origin: http://example.com" -i -X OPTIONS localhost:8008/foo
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://example.com
Date: Tue, 13 Jan 2015 14:04:32 GMT

https://github.com/emicklei/go-restful/blob/master/examples/restful-CORS-filter.go#L59

**Comment by emicklei** [comment]
I remember a change to CORS such that the Options Filter was no longer needed in case the CORS was told which http methods to allow.
I will review this and your examples to see what is needed to fix this.

**Comment by emicklei** [comment]
I had a look into one of our projects and noticed that we defined the AllowedMethods on the CORS structure and no Options filter was added.

**Comment by emicklei** [comment]
Line 75 says it will compute the AllowedMethods when not specified; this indicates that both filters cannot be used together. This means I will change the example and update the docs

**Comment by jcw9930** [comment]
Thanks for looking into it. It seems though that the computing doesn't work (also the static definition with AllowedMethods):

        cors := restful.CrossOriginResourceSharing{
                AllowedHeaders: []string{"Content-Type"},
                AllowedMethods: []string{"GET", "DELETE", "OPTIONS"},
                CookiesAllowed: false,
                Container:      wsContainer}
        wsContainer.Filter(cors.Filter)

gives me:

$ curl -H "Origin: http://example.com" -i -X OPTIONS localhost:8008/foo
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://example.com
Date: Mon, 19 Jan 2015 09:12:14 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

When I leave out AllowedMethods, I get the same response.

**Comment by emicklei** [comment]
I am investigating this now.

**Comment by emicklei** [comment]
I found and fixed 2 problems with CORS. Will add some extra tests for the first later.

**Comment by emicklei** [comment]
The latest commit fixes the problem with the computation of allowed methods.
