### ISSUE TITLE
Missing apiVersion in ResourceListing

### ISSUE THREAD

**Issue by nikhiljindal** [emicklei/go-restful#177]
I am setting ws.apiVersion("1.0") but still apiVersion is "" in my apidocs.json.
The bug seems to be in this line: https://github.com/emicklei/go-restful/blob/master/swagger/swagger_webservice.go#L132.
It should be:
listing := ResourceListing{SwaggerVersion: swaggerVersion, ApiVersion: apiVersion}
instead of:
listing := ResourceListing{SwaggerVersion: swaggerVersion}

swagger-codegen requires that ResourceListing should have a non-empty apiVersion.

Let me know if I should send a PR

**Comment by emicklei** [comment]
Thank you for reporting this. I will change it now.

**Comment by emicklei** [comment]
Hmm, so what should the version be if the list contains resources with different api versions. A Webservice is in Swagger represented by a ApiDeclaration which will have your defined version.

**Comment by nikhiljindal** [comment]
Yes this is tricky.
We can pick the apiversion of the first WebService.

Or it might be good to introduce a top level construct for defining ResourceListing values. ResourceListing has other things like Info as well.

For us: We were exploring swagger-codegen when I found this bug. We might not end up using it. So while this is good to fix, its not critical for us.
Will let you know if it becomes critical.

Thanks for looking!

**Comment by emicklei** [comment]
I was thinking of letting the swagger WebService itself hold the top-level api version.  It is not a singleton as we can have multipl such webservices serving on their own path (and therefore version).

With swagger-codegen, as you refereing to the one in my branch? if not , which are you evaluating?

thanks

**Comment by nikhiljindal** [comment]
Yes. That sounds fine for api version.

https://github.com/swagger-api/swagger-codegen is the one I am looking at.
