### ISSUE TITLE
Respecting the Content-Type

### ISSUE THREAD

**Issue by wadewegner** [emicklei/go-restful#178]
Simple sample as follows: 

``` go
func New() *restful.WebService {
    service := new(restful.WebService)
    service.
        Path("/users").
        Consumes(restful.MIME_XML, restful.MIME_JSON).
        Produces(restful.MIME_XML, restful.MIME_JSON)
 
    service.Route(service.GET("/{user-id}").To(FindUser))
```

However, when I use Postman and test with a `Content-Type: application/json` in my header, it returns XML instead of JSON. If I switch to `Produces(restful.MIME_JSON, restful.MIME_XML)` and set the content-type to `application/xml` it only returns JSON.

I must be missing something? Any pointers?

Thanks!

**Comment by emicklei** [comment]
Content-Type refers to the payload for methods such as PUT and POST. You need to set the Accept header instead.

**Comment by wadewegner** [comment]
Bah, yes. Thank you!
