### ISSUE TITLE
route {param:*} error

### ISSUE THREAD

**Issue by gogames** [emicklei/go-restful#179]
My code is simple as follow:

```go
package main

import (
	"log"
	"net/http"

	"github.com/emicklei/go-restful"
)

func main() {
	ws := &restful.WebService{}
	ws.Route(ws.GET("/v1/category/{param:*}").To(handle))
	restful.Add(ws)
	http.ListenAndServe(":8081", nil)
}

func handle(r *restful.Request, w *restful.Response) {
	log.Println(r.PathParameter("param"))
}
```

When I GET ```http://127.0.0.1:8081/v1/category/sub``` it prints ```sub``` which is correct.

I GET ```http://127.0.0.1:8081/v1/category/sub/sub``` and expect to print ```/sub/sub``` but in the browser I get error 404 page not found. I read the document many times but still can not solve this problem.

Would you help? Thank you!

**Comment by emicklei** [comment]
Thank you for reporting this. I will create a test for this see what happens

Alternatively, you culd use the CurlyRouter instead of the default RouterJSR311. 

`restful.DefaultContainer.Router(CurlyRouter{})`

**Comment by gogames** [comment]
Thank you!

I also check the test cases in CurlyRouter and it really works. So I get confuser.

**Comment by emicklei** [comment]
Me too. I wil investigate now

**Comment by emicklei** [comment]
I have a lead now. The regular expression used by the Route internally is not correct (does not use the wildcard param). I will study the spec for the correct way of handling.

**Comment by gogames** [comment]
cool. Not hurry, take your time XD

**Comment by emicklei** [comment]
path_expression.go:46 says // ignore var spec.   I left a hint :-)

**Comment by gogames** [comment]
oh. That's my fault.. 

Maybe you can also update the document. I just read it from godoc XD

**Comment by gogames** [comment]
sry. I made a mistake. haha. that's cool. Thank you for help!

**Comment by emicklei** [comment]
so I have your test working now. Need some more units tests before I release it
