### ISSUE TITLE
swagger doc version control

### ISSUE THREAD

**Issue by gogames** [emicklei/go-restful#180]
Hi, I am encountering a problem that I have different versions of api and would like to enter the api page via `http://localhost/doc` in browser and type `http://localhost/v1/doc.json` in swagger page to show all version 1 documents or `http://localhost/v2/doc.json` to show all version 2 documents.

I tried to figure it out but don't know how, can you help? Thanks in advance!

**Comment by emicklei** [comment]
I think this is possible because you can create multiple swagger.Webservices, each with its own set of restful.Webservices, ApiPath and SwaggerPath.

**Comment by gogames** [comment]
I am supposed to run all doc in localhost:8080/doc and view version 1 doc by type localhost:8080/v1/doc.json in swagger index.html page. XD

my code:
```go
package main

import (
	"net/http"

	"github.com/emicklei/go-restful"
	"github.com/emicklei/go-restful/swagger"
)

func main() {
	v1Services, v2Services := make([]*restful.WebService, 0), make([]*restful.WebService, 0)
	configV1 := swagger.Config{
		WebServices: v1Services,
		ApiPath:     "/v1/doc.json",

		SwaggerPath:     "/doc",
		SwaggerFilePath: "/Users/cc/swagger-ui/dist",
	}
	configV2 := swagger.Config{
		WebServices: v2Services,
		ApiPath:     "/v2/doc.json",

		SwaggerPath:     "/doc",
		SwaggerFilePath: "/Users/cc/swagger-ui/dist",
	}

	swagger.RegisterSwaggerService(configV1, restful.DefaultContainer)
	swagger.RegisterSwaggerService(configV2, restful.DefaultContainer)

	http.ListenAndServe(":8080", nil)
}
```

go run the file, panic.

2015/02/11 11:10:31 [restful/swagger] listing is available at /v1/doc.json
2015/02/11 11:10:31 [restful/swagger] use corrected SwaggerPath ; must end with slash (/)
2015/02/11 11:10:31 [restful/swagger] /doc/ is mapped to folder /Users/cc/swagger-ui/dist
2015/02/11 11:10:31 [restful/swagger] listing is available at /v2/doc.json
2015/02/11 11:10:31 [restful/swagger] use corrected SwaggerPath ; must end with slash (/)
2015/02/11 11:10:31 [restful/swagger] /doc/ is mapped to folder /Users/cc/swagger-ui/dist
panic: http: multiple registrations for /doc/

**Comment by emicklei** [comment]
I see. This means that we need to run multiple containers, on different ports and that is not what you want I guess. 

To recap your requirements, you want 1 swagger page showing 2 versions of the api.  Have you considered settting the RootPath of v1Services to "/v1"  en "/v2" respectively ?

**Comment by gogames** [comment]
Yep I did that in my production code. But it does not work for swagger. I am still trying XD

**Comment by emicklei** [comment]
Can we close this issue?

**Comment by gogames** [comment]
sure. thank you for open sourcing the library. XD
