### ISSUE TITLE
filter feature

### ISSUE THREAD

**Issue by gogames** [emicklei/go-restful#182]
Is it a good idea that users can insert a filter `before route` `before execute` `finish execute` `finish route`? Now we only have `before route` if we use `container.Filter(filterFunction)`. Of course we can insert filters into web service, but sometimes it is not a good idea.

For example, if i want to monitor the execution time of each request, code can be written like this:
```go
container.Filter(beforeExec, filterFuncTimerStart)
container.Filter(finishExec, filterFuncTimerStop)
```

**Comment by emicklei** [comment]
Using the chain argument you resume the execution flow and after that do you measurement.  This is how we measure time and increment counters for status codes.

```
func monitor(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
	now := time.Now()
	chain.ProcessFilter(req, resp)
        duration := time.Now().Sub(now)
        // send duration to metrics
}
```

**Comment by gogames** [comment]
```go
webservice.Route(webservice.PUT("").
                   Filter(filter1).
                   Filter(filter2).
                   Filter(filter3).
                   Filter(filter4).
                   Filter(filter5).
                   To(updateUser))
```

How can I just measure the execution time of ```To(updateUser)``` in container level?

**Comment by emicklei** [comment]
and how about
```
func  filter1(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
    req.SetAttribute("now",  time.Now())
    chain.ProcessFilter(req, resp)
}

func  filter5(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
    before := req.Attribute("now").(time.Time)
    duration := time.Now().Sub(before)
    // send duration to metrics
    chain.ProcessFilter(req, resp)
}
```

**Comment by gogames** [comment]
Seems good lol. Thank you for suggestion!
