### ISSUE TITLE
unpredictable Items order in the Swagger GUI

### ISSUE THREAD

**Issue by rsagy** [emicklei/go-restful#185]
Hi

I'm using Swagger with the Go language and its great: Very intuitive and easy to use, thanks!
I have a problem, though,  that I do not know how to solve and I hope you can help me with:
I have a container with 6 services, and each service  holds several routs (in some cases more than 10 routs). I commented out the sorter in the index.html file so the swagger will be displayed in the browser in its original order - the order in which I added the routes to the server (not sorted). For some reason this doesn't do the trick and the routes are not displayed in the order they were added to the service. Do you have an idea what I done wrong?

**Comment by emicklei** [comment]
Hi,

Webservices (called Resource in Swagger) are sorted (https://github.com/emicklei/go-restful/blob/master/swagger/swagger_webservice.go#L140)  in the listing. 

Routes per Webservice (called ApiDeclaration) are collected using a map (https://github.com/emicklei/go-restful/blob/master/swagger/swagger_webservice.go#L183) 

So, you are not doing things wrong. The listing building part does not preserve the order. 
I guess an ordered map could be a solution to this.

**Comment by nikhiljindal** [comment]
+1. The order changes each time and hence it is tough to keep track of what exactly changed in the spec when we make changes in our code.
Would love to see this fixed soon.
Happy to send a PR if it speeds up things.

**Comment by emicklei** [comment]
Currently working on this....
