### ISSUE TITLE
go-restful generates incorrect swagger spec for model with array fields

### ISSUE THREAD

**Issue by nikhiljindal** [emicklei/go-restful#186]
The swagger spec generated when one of the model has an array field is incorrect.

For ex:
The swagger spec generated for the following model is:

```
type User struct {
  name string
}
type UserList struct {
  users []User
}
````

```
"models": {
   "main.User": {
    "id": "main.User",
    "required": [
     "name"
    ],
    "properties": {
     "name": {
      "type": "string"
     }
    }
   },
   "main.UserList": {
    "id": "main.UserList",
    "required": [
     "users"
    ],
    "properties": {
     "users": {
      "type": "array",
      "items": [
       {
        "$ref": "main.User"
       }
      ]
     }
    }
   }
  }
```

Passing this spec through `swagger-tools validate` gives the following error:
```
#/models/main.UserList/properties/users/items: Data does not match any schemas from 'oneOf'
#/models/main.UserList/properties/users/items:: Expected type object but found type array
```

It seems that the incorrect part is:
```
      "items": [
       {
        "$ref": "main.User"
       }
      ]
```
As per https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#5291-object-examples, Items should be an object and not an array. The correct spec is:
```
      "items": {
        "$ref": "main.User"
       }
```

**Comment by emicklei** [comment]
The tests in the swagger package has correct examples of this. Did you miss an update of the go-restful package? https://github.com/emicklei/go-restful/commit/a55bcd8b711411166692a0ed6e8b9836e88c1bad

**Comment by emicklei** [comment]
btw, I noticed that some tests are non-deterministic due to the naive json-string-compare approach. I need to change this.
