### ISSUE TITLE
TraceLogger should accept an interface, not a type

### ISSUE THREAD

**Issue by GuyMorgan** [emicklei/go-restful#187]
There are plenty of logging package altenatives to the standard library log, and at least some of them try to be (somewhat) API-compatible with it. I'm using the popular [logrus](https://github.com/Sirupsen/logrus) which should be compatible to the extent required by go-restful, but the fact that `func TraceLogger(logger *log.Logger)` specifies a concrete type rather then an interface means I must use the standard library all over, or have two logging packages present in my code.

The [godoc](http://golang.org/pkg/log/) doesn't define an interface for `log`, somewhat surprisingly, but it seems like a natural thing to want to define. go-restful could define its own logger interface (with the subset of the logging API it used), which would also allow wrappers to be written for whatever logging package one uses, even if it uses its own API.

If this is acceptable, I could try to put together a PR. Would you take one?

**Comment by emicklei** [comment]
Yes, I was hoping to see an interface in std Go as well. 

In recent projects, I follow this practice too (statsd,pgx,etcd) ; defining an interface for what I am using of the third party package. It also makes stubbing/mocking easier ; just pass a different impl.

So back to this TraceLogger, I am greatful to receive a PR for this.
