### ISSUE TITLE
go-restful should allow the user to provide the logger it will use

### ISSUE THREAD

**Issue by GuyMorgan** [emicklei/go-restful#189]
Tthere are explicit uses of the stdlib log.* methods, which doesnt interoperate well
in the case where a user uses a different .logging package. there's also `LogIngo` which
probably could be monkey-patched (-1), but even that isn't consistent:
```
route_builder.go
136:	log.Println("ReturnsError is deprecated, use Returns instead.")
189:		log.Fatalf("[restful] Invalid path:%s because:%v", b.currentPath, err)
192:		log.Fatalf("[restful] No function specified for route:" + b.currentPath)

swagger/swagger_webservice.go
26:// LogInfo is the function that is called when this package needs to log. It defaults to log.Printf
27:var LogInfo = log.Printf

web_service.go
29:		log.Fatalf("[restful] invalid path:%s because:%v", w.rootPath, err)
 
container.go
110:			log.Fatalf("[restful] WebService with duplicate root path detected:['%v']", each)
135:	log.Println(buffer.String())
174:				log.Println("[restful] unable to install compressor:", err)
 
````

 for example of why this is an issue, here's an example where the application uses structured logging: 
```
{"level":"info","msg":"Starting up...","time":"2015-03-16T23:27:17"}
2015/03/16 23:27:17 [restful/swagger] listing is available at http://localhost:8080/apidocs.json
2015/03/16 23:27:17 [restful/swagger] http://localhost:8080/apidocs/ is mapped to folder swagger-ui/dist
{"level":"info","msg":"start listening on localhost:8080","time":"2015-03-16T23:27:17"}
```

related to #187

**Comment by emicklei** [comment]
Indeed, it is not consistent.  We should change these calls as well
And the swagger pkg could use the same logger interface (it is exposed)

**Comment by emicklei** [comment]
For the swagger part in my current project, I am using ```swagger.LogInfo = glog.Infof``` as the trace var and logger are currently not exposed. 

I will change the calls in the other restful types.

**Comment by GuyMorgan** [comment]
The PR only changed the default for LogInfo  (it now uses the overridable logger in restful/log), but it is still modifiable in that way and you shouldn't need to touch your project code.

How about adding a setter for the TraceLogger trace var? that way if the tracer is "enabled" rather then "set" by the user, the package logger can be used by default. That won't break any code.

**Comment by emicklei** [comment]
Thank you for the PR. I have been studying it and I like the solution better than the modifications I was about to do. 

While thinking about those modifications, I realized that tracing and normal logging should not be combined ; if a tracelogger was not set, the RouteBuilder would not be able to do a Fatal.

Your suggestion to add a setter for the trace var is a good one ; e.g.   func EnableTracing(bool)

**Comment by GuyMorgan** [comment]
Added EnableTracing. The package logger is exported now.

> I realized that tracing and normal logging should not be combined ; if a tracelogger was 
> not set, the RouteBuilder would not be able to do a Fatal.

The tracelogger *if enabled* can default to sending its output to the existing package logger
created on init() when the package is imported. That should ok, right? I've put it in for now, but let me know If I've misunderstood.

**Comment by emicklei** [comment]
Great work. One more question :-), why did you create the SetLogger as a variable i.o
```
package restful
...
func SetLogger(customLogger StdLogger) {
	log.SetLogger(customLogger)
}
```
which is more like they way the TraceLogger is set. Then we have 2 functions in restful to control the logging.

**Comment by GuyMorgan** [comment]
Do you mean "why keep Trace and Package logging seperate?" or "Why a setter and not a variable" ?

If the former, it's because TraceLogger is an established API which I couldn't remove or change just because I felt like it. That depends on whether your prioritize "Keep users code working" or "Get rid of cruft". Each has its merits, and whicever you espouse we can do.

If the latter, when you chose to use setter for `TraceLogger` you've established a convention for the package (and the rest of restful is similar in style), so I'm just trying to blend in...

**Comment by emicklei** [comment]
I meant the latter. Totally agree with the former.

In your PR it says (logger.go):
```
// expose the setter for the global logger on the top-level package
var SetLogger = log.SetLogger
```
so the question was why did you not choose:
```
func SetLogger(customLogger StdLogger) {
    log.SetLogger(customLogger)
}
```
Functionally they are the same and there is no difference to the user of the package. Just a remark.


It is true that some other parts of go-restful are using exposed variables; I now consider that a mistake because the "implementation" can never be changed.  For instance, having TraceLogger(...) allows us to change the definition to call EnableTracing.  Or what if we decide to put in more trace logging. With variables we are stuck (see the deprecated DefaultResponseMimeType, EnableContentEncoding)

**Comment by GuyMorgan** [comment]
Oh, right you are. Only because that's an unnecessary extra function call, but that truly doesn't matter here. Changed (and squashed the review commits).

**Comment by emicklei** [comment]
Thank you for contributing

**Comment by jbub** [comment]
great work, thank you
