### ISSUE TITLE
go-restful uses "$ref" to describe primitive type items object

### ISSUE THREAD

**Issue by nikhiljindal** [emicklei/go-restful#190]
As per https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#434-items-object
"type" should be used for primitive types and "$ref" for complex types.
But go-restful seems to be using "$ref" for primitive types as well.

For example, for the following Go struct:
```
type User struct {
  items []string
}
```
The swagger spec generated contains:
```
"models": {
   "main.User": {
    "id": "main.User",
    "required": [
     "items"
    ],
    "properties": {
     "items": {
      "type": "array",
      "items": {
       "$ref": "string"
      }
     }
    }
   }
```
The items object should say `"type": "string"` instead of `"$ref": "string"`
`swagger-tools validate` fails for a spec generated using go-restful due to this.

**Comment by nikhiljindal** [comment]
Actually, the logic of when to use "$ref" and when to use "type" seems wrong.
It seems that go-restful uses "$ref" incase of an array and "type" otherwise.
Although https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#529-property-object says that $ref should be used to link to other models (irrespective of array or not).

Hence, for the following Go struct:
```
type User struct {
    name Name
}
```
The swagger spec should be:
```
"models": {
   "main.User": {
    "id": "main.User",
    "required": [
     "name"
    ],
    "properties": {
     "name": {
      "$ref": "main.Name"
     }
    }
   }
}
```
Right now, the generated spec says `"type": "main.Name"` instead of `"$ref": "main.Name"`

**Comment by emicklei** [comment]
Thank you for diving into this.  I will have a close look and produce some
extra tests if needed.

On Tue, Mar 17, 2015 at 7:15 AM, Nikhil Jindal <notifications@github.com>
wrote:

> Actually, the logic of when to use "$ref" and when to use "type" seems
> wrong.
> It seems that go-restful uses "$ref" incase of an array and "type"
> otherwise.
> Although
> https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#529-property-object
> says that $ref should be used to link to other models (irrespective of
> array or not).
>
> Hence, for the following Go struct:
>
> type User struct {
>     name Name
> }
>
> The swagger spec should be:
>
> "models": {
>    "main.User": {
>     "id": "main.User",
>     "required": [
>      "name"
>     ],
>     "properties": {
>      "name": {
>       "$ref": "main.Name"
>      }
>     }
>    }
> }
>
> Right now, the generated spec says "type": "main.Name" instead of "$ref":
> "main.Name"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/go-restful/issues/190#issuecomment-82132637>.
>



-- 
^ Ernest Micklei

http://ernestmicklei.com
