### ISSUE TITLE
swagger operation must be explicitly set

### ISSUE THREAD

**Issue by porjo** [emicklei/go-restful#191]
I've found that I have to explicitly set `RouteBuilder.Operation` each time. Failing to do this results in the Swagger UI not displaying the webservice properly.

For example, a snippet of my go code:
```Go
 ws.Route(ws.GET("").To(r.getReviews).
                 Doc("get reviews").
                 Operation("getReviews").
                 ...
```

In Swagger UI, this displays like so:

![gorestful](https://cloud.githubusercontent.com/assets/1296987/6702916/bab52510-cd7e-11e4-927c-2c3e8e00238f.png)

If I leave off `Operation("getReviews")` then Swagger UI fails to open the section under 'reviews' and throws console error `uncaught exception: SwaggerOperations must have a nickname.`

I would be nice if the value for operation, when missing, could be set automatically based on the method name passed to `To()`. e.g. in this case set to 'getReviews'.

**Comment by emicklei** [comment]
Yes, the UI requires that. 
Implementing your suggestion would require some reflection (magic); I will have a look

**Comment by emicklei** [comment]
Just created an example (http://play.golang.org/p/ueA1e0kLak) to experiment with this. Need to figure out what the suffix (fm) means here.

**Comment by porjo** [comment]
Thanks, that works well.
