### ISSUE TITLE
Setting Content-Type / charset

### ISSUE THREAD

**Issue by muesli** [emicklei/go-restful#193]
I'm having issues with go-restful responding to JSON requests with Content-Type "application/json" but with no additional information about the charset (e.g. charset=UTF-8).

I tried setting it on the response within a filter, but that gets overwritten with MIME_JSON (constants.go) by go-restful again.

What's the correct way to do this?

**Comment by emicklei** [comment]
You have found a flaw in the implementation. Indeed, the WriteAsJson writes the constant and in a response filter it is too late to change that. At the moment, I can think of a few options. As a workaround, you can do all the writing in your route function. To fix this, go-restful will have a WriteJson(v interface{}, contentType string) method that can be used directly by the route function and can be used by the WriteEntity method that will call WriteJson with what is specified by aRoute.Produces(..) and if empty fallback to the constant.

**Comment by emicklei** [comment]
how about providing this:

```
// WriteJson is a convenience method for writing a value in Json with a given Content-Type
func (r *Response) WriteJson(value interface{}, contentType string) error {
```

**Comment by muesli** [comment]
This would certainly ease the pain quite a bit for me. As of right now I'm actually overwriting the default MIME_JSON in constants.go, which isn't a solution I'm exactly proud of.
