### ISSUE TITLE
Set description property on model fields

### ISSUE THREAD

**Issue by gdamore** [emicklei/go-restful#196]
I'm interested in having better API documentation.  I'm inclined to believe that the addition of a new structure tag, say "restful" (as a peer to the json tag) to structure members may allow automatic generation of richer documentation for structure properties in the models.

Alternatively, having a documented API to set this would work, but that would be pretty awkward.  Right now the API is fairly automatic, so it would be nice to preserve that.

I can probably code this up sometime this week if there is interest.

**Comment by emicklei** [comment]
This is a suggestion that has been discussed before (will find the issue later). The person suggested to use the `swagger` tag to make it independent of restful.  At the time I was planning to investigate this but, as you can see, I kind of lost interest.

Recently, I did add a callback feature in the Swagger config that allows for modification of the ApiDeclaration. Maybe extending this (and exposing the model_builder) is a start for the API approach.

So yes, I would like to see what you can contribute here.

**Comment by emicklei** [comment]
Related https://github.com/emicklei/go-restful/issues/159

**Comment by gdamore** [comment]
I've actually implemented this -- PR coming shortly.  I added all the swagger 1.2 fields for now, using tags.  So there are tags like "swagger%description" and "swagger%enum", etc.  I even allow overriding the type using swagger%type.

**Comment by gdamore** [comment]
I'll probably update *again* after this, with 2.0 properties, but I want to implement swagger 2.0 support first.  But if someone else has done so, or is nearly done, then I'll wait rather than doing the work myself.
