### ISSUE TITLE
Set Fields of a Data Model to Required

### ISSUE THREAD

**Issue by tortis** [emicklei/go-restful#202]
I was unable to find a way to set specific fields in a model definition to required. It seems that when you specify .Reads() that it just treats the whole body as a required parameter.

Then in the produced documentation I see something like this:
```
main.User {
address (object, optional),
created (integer, optional),
email (string, optional),
first_name (string, optional),
id (string, optional),
last_name (string, optional),
modified (integer, optional),
password (string, optional),
phone (string, optional),
}
```
Where all fields are optional.

Is there some mechanism to set these fields to required individually (even if it is not automatically enforced by go-restful)?

Thanks for the awesome library!

**Comment by emicklei** [comment]
Does the fields of your User struct have the `omitempty` in its json tag? Currently, this is only way to control the required value (which will be false in that case). 
See https://github.com/emicklei/go-restful/blob/master/swagger/model_builder.go#L63

I have been thinking lately about adding an interface that allows a callback to a struct in which the swagger Model can be custom changed.

```
type ModelBuildable interface {
        PostBuildModel(m *swagger.Model) *swagger.Model
}
```

Now, you can implement that and modify the parameter (or return a complete new).
```
func (u User) PostBuildModel(m *swagger.Model) *swagger.Model {
    m.Required = []string{"email"}
    return m
}
```

Others have suggested to introduce a new tag, such as swagger%required. Not sure about that.

**Comment by tortis** [comment]
Interesting, I actually was just looking at that function before you replied and I tested adding and removing omitempty. It did not seem to have an effect on the produced documentation. All of the fields were still marked as optional.

Here is how I'm building the route:
```
ws.Route(ws.POST("").To(u.createUser).
        Doc("Create a new user account").
        Operation("createUser").
        Reads(User{}).
        Returns(http.StatusCreated, "Newley created user", User{}))
```

Here is my User struct:
```
type User struct {
    Id         bson.ObjectId `bson:"_id" json:"id,omitempty"`
    Created    int64         `bson:"created" json:"created"`
    Modified   int64         `bson:"modified" json:"modified"`
    First_name string        `bson:"first_name" json:"first_name"`
    Last_name  string        `bson:"last_name" json:"last_name"`
    Email      string        `bson:"email" json:"email"`
    Address    struct {
        Country string `bson:"country" json:"country"`
        State   string `bson:"state" json:"state"`
        City    string `bson:"city" json:"city"`
        Street  string `bson:"street" json:"street"`
        Zip     string `bson:"zip" json:"zip"`
    } `bson:"address" json:"address"`
    Phone      string `bson:"phone" json:"phone"`
    School     string `bson:"school" json:"school"`
    Is_teacher bool   `bson:"is_teacher" json:"is_teacher"`
    Password   string `bson:"password" json:"password"`
    Token_key  string `bson:"token_key" json:"-"`
}
```

Along the same lines it would be nice to be able to specify Id as readOnly. I don't want to mark it with "-" because I still want it to be included in GET calls.

Thanks so much for the help! I'm still learning all of this Swagger terminology.

**Comment by emicklei** [comment]
can this be closed?

**Comment by genexp** [comment]
I know things have changed quite a bit in (2!) years, but is there a way to do this now? I can't find this interface anymore, and it looks like the Writes method just takes an interface.  The use case is allowing docs to specify which fields can be written on a POST vs which are provided on a GET.
