### ISSUE TITLE
Swagger not picking up root endpoints

### ISSUE THREAD

**Issue by icecrime** [emicklei/go-restful#210]
I'm experimenting with go-restful and swagger for the [Docker](https://github.com/docker/docker) API. One problem I'm facing is that API endpoints at the root (e.g., `/_ping` and `/version`) are not properly picked up by swagger-ui. I fail to understand what *should* be the proper behavior, but I see multiple potential reasons for the issue.

When I have two endpoints on the root, the JSON listing looks like this:

```
{
  "swaggerVersion": "1.2",
  "apis": [
   {
    "path": "/",
    "description": "basic operations"
   },
   {
    "path": "/",
    "description": "basic operations"
   }
  ],
  "apiVersion": "",
  "info": {
   "title": "",
   "description": ""
  }
}
```

What we have here is that the two endpoints seem to not be aggregated under a single resource (which I think is imputable to [this loop](https://github.com/emicklei/go-restful/blob/afcfbf4f9a55dba281edec59821d8af3bb269e0e/swagger/swagger_webservice.go#L67)).

Ultimately, even when I ditch the whole `if rootPath == "" || rootPath == "/" {` code path, I end up with the following (probably better JSON), but swagger-ui still breaks:

```
{
  "swaggerVersion": "1.2",
  "apis": [
   {
    "path": "/",
    "description": "basic operations"
   }
  ],
  "apiVersion": "",
  "info": {
   "title": "",
   "description": ""
  }
}
```

Finally, I decided to go with the following patch, which gives me the JSON below:

```
diff --git a/swagger/swagger_webservice.go b/swagger/swagger_webservice.go
index 885f9dc..3016078 100644
--- a/swagger/swagger_webservice.go
+++ b/swagger/swagger_webservice.go
@@ -68,7 +68,9 @@ func RegisterSwaggerService(config Config, wsContainer *restful.Container) {
                                        entry := staticPathFromRoute(route)
                                        _, exists := sws.apiDeclarationMap.At(entry)
                                        if !exists {
-                                               sws.apiDeclarationMap.Put(entry, sws.composeDeclaration(each, entry))
+                                               decl := sws.composeDeclaration(each, entry)
+                                               decl.ResourcePath = entry
+                                               sws.apiDeclarationMap.Put(entry, decl)
                                        }
                                }
                        } else { // use root path
```

```
{
  "swaggerVersion": "1.2",
  "apis": [
   {
    "path": "/_ping",
    "description": "basic operations"
   },
   {
    "path": "/version",
    "description": "basic operations"
   }
  ],
  "apiVersion": "",
  "info": {
   "title": "",
   "description": ""
  }
}
```

Please let me know where you think the issue lies, and I'd be happy to submit a PR for it!

**Comment by emicklei** [comment]
hi,

thank for considering this package and for reporting this. Did you try
putting each root path in its own webservice (is more like a jaxrs
resource) ? Or is the aggregation important. I will have a look at your
suggested change today

On Monday, June 8, 2015, Arnaud Porterie <notifications@github.com> wrote:

> I'm experimenting with go-restful and swagger for the Docker
> <https://github.com/docker/docker> API. One problem I'm facing is that
> API endpoint at the root (e.g., /_ping and /version) are not properly
> picked up by swagger-ui. I fail to understand what *should* be the proper
> behavior, but I see multiple potential reasons for the issue.
>
> When I have two endpoints on the root, the JSON listing looks like this:
>
> {
>   "swaggerVersion": "1.2",
>   "apis": [
>    {
>     "path": "/",
>     "description": "basic operations"
>    },
>    {
>     "path": "/",
>     "description": "basic operations"
>    }
>   ],
>   "apiVersion": "",
>   "info": {
>    "title": "",
>    "description": ""
>   }
> }
>
> What we have here is that the two endpoints seem to not be aggregated
> under a single resource (which I think is imputable to this loop
> <https://github.com/emicklei/go-restful/blob/afcfbf4f9a55dba281edec59821d8af3bb269e0e/swagger/swagger_webservice.go#L67>
> ).
>
> Ultimately, even when I ditch the whole if rootPath == "" || rootPath ==
> "/" { code path, I end up with the following (probably better JSON), but
> swagger-ui still breaks:
>
> {
>   "swaggerVersion": "1.2",
>   "apis": [
>    {
>     "path": "/",
>     "description": "basic operations"
>    }
>   ],
>   "apiVersion": "",
>   "info": {
>    "title": "",
>    "description": ""
>   }
> }
>
> Finally, I decided to go with the following patch, which gives me the JSON
> below:
>
> diff --git a/swagger/swagger_webservice.go b/swagger/swagger_webservice.go
> index 885f9dc..3016078 100644
> --- a/swagger/swagger_webservice.go
> +++ b/swagger/swagger_webservice.go
> @@ -68,7 +68,9 @@ func RegisterSwaggerService(config Config, wsContainer *restful.Container) {
>                                         entry := staticPathFromRoute(route)
>                                         _, exists := sws.apiDeclarationMap.At(entry)
>                                         if !exists {
> -                                               sws.apiDeclarationMap.Put(entry, sws.composeDeclaration(each, entry))
> +                                               decl := sws.composeDeclaration(each, entry)
> +                                               decl.ResourcePath = entry
> +                                               sws.apiDeclarationMap.Put(entry, decl)
>                                         }
>                                 }
>                         } else { // use root path
>
> {
>   "swaggerVersion": "1.2",
>   "apis": [
>    {
>     "path": "/_ping",
>     "description": "basic operations"
>    },
>    {
>     "path": "/version",
>     "description": "basic operations"
>    }
>   ],
>   "apiVersion": "",
>   "info": {
>    "title": "",
>    "description": ""
>   }
> }
>
> Please let me know where you think the issue lies, and I'd be happy to
> submit a PR for it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/go-restful/issues/210>.
>


-- 
^ Ernest Micklei

http://ernestmicklei.com

**Comment by svanharmelen** [comment]
I just updated (`go get -u`) my local copy of the `go-restful` package and all of a sudden Swagger didn't work as expected anymore. After changing the lines of code suggested by @icecrime all works fine again.

So +1 for this fix!

**Comment by emicklei** [comment]
please verify https://github.com/emicklei/go-restful/commit/a4c108ab2901f367f9ee2a041d9cfafc8206b27a

**Comment by svanharmelen** [comment]
@emicklei works like a charm, thx!

**Comment by emicklei** [comment]
@icecrime can this be closed?
