### ISSUE TITLE
Can't get filter to work with httptest.NewRecorder

### ISSUE THREAD

**Issue by hexadecimal1** [emicklei/go-restful#216]
I am trying to make a filter that records and processes a response while simultaneously passing the response through to the endpoint.

Essentially the filter needs to log API requests, but only if the response does not contain an error object (can't use http header codes to monitor this so I am using httptest.NewRecorder to log and analyze responses).

This is my barebones attempt:

func Sync(request *restful.Request, response *restful.Response, chain *restful.FilterChain) {
	recorder := httptest.NewRecorder()
	respWriter := restful.NewResponse(recorder)
	chain.ProcessFilter(request, respWriter)
	fmt.Printf("\r\n\r\n%+v\r\n", recorder.Body.Bytes())
}

The response is successfully sent through to the rest endpoint (which I did not expect would happen), but recorder never captures any data.

Do you have any insight on how this can be accomplished?

As an alternative I know I can write my own middleware similar to this (https://justinas.org/writing-http-middleware-in-go/) and set the handler for a container, but the problem with that is that all rest endpoint handlers (or containers) cannot be configured on a per-route basis. Ideally I would like to solve this with a filter if possible.

Thanks so much! go-restful is amazing!!

**Comment by emicklei** [comment]
When reading your problem statement, I was thinking about using the request attributes instead as you cannot "capture" the headers.

As for why the recorder does not record, that one is interesting. You response is no longer a restful.Response. You would use `response.ResponseWriter = respWriter` and pass reponse as usual. 

```
recorder := httptest.NewRecorder()
respWriter := restful.NewResponse(recorder)
old := response.ResponseWriter
response.ResponseWriter = respWriter
chain.ProcessFilter(request, respWriter)
fmt.Printf("\r\n\r\n%+v\r\n", recorder.Body.Bytes())
// write the bytes and headers and status to the old response.
```

Looking back at this snippet, I suggest you use the attributes instead. Feels hacky and is probably broken.

As for the middleware features, I have not given it a thought how this can be achieved. Maybe creating filters that encapsulate such handlers. It needs some experimentation and code reading

**Comment by hexadecimal1** [comment]
Awesome! Thanks!!

That worked for the most part, the only problem I am still having is that for some reason I'm not able to alter the status code of the response. I can copy the headers and body just fine, but not the status code (it seems to always be 200... maybe somehow that's coming from httptest.ResponseWriter, but not seeing how that could be possible).

```func Sync(request *restful.Request, response *restful.Response, chain *restful.FilterChain) {
	cachedResponseWriter := response.ResponseWriter
	recorder := httptest.NewRecorder()
	responseWriter := restful.NewResponse(recorder)
	response.ResponseWriter = responseWriter
	chain.ProcessFilter(request, responseWriter)

	response.ResponseWriter = cachedResponseWriter
	for headerKey, headerValue := range recorder.HeaderMap {
		response.AddHeader(headerKey, fmt.Sprintf(strings.Join(headerValue,"")))
	}
	response.WriteHeader(recorder.Code)
	response.Write(recorder.Body.Bytes())
}```

**Comment by emicklei** [comment]
That's why the following method was added to restful.Response. It captures the code.
So I think you should ask responseWriter for the StatusCode().

```
// WriteHeader is overridden to remember the Status Code that has been written.
// Note that using this method, the status value is only written when
// - calling WriteEntity,
// - or directly calling WriteAsXml or WriteAsJson,
// - or if the status is one for which no response is allowed (i.e.,
//   204 (http.StatusNoContent) or 304 (http.StatusNotModified) or PartialContent )
func (r *Response) WriteHeader(httpStatus int) 
```

**Comment by hexadecimal1** [comment]
That makes sense. Thanks again!
For the record here is a completed filter:

```
func Sync(request *restful.Request, response *restful.Response, chain *restful.FilterChain) {
	cachedResponseWriter := response.ResponseWriter
	recorder := httptest.NewRecorder()
	responseWriter := restful.NewResponse(recorder)
	response.ResponseWriter = responseWriter
	chain.ProcessFilter(request, responseWriter)

	response.ResponseWriter = cachedResponseWriter
	for headerKey, headerValue := range recorder.HeaderMap {
		response.AddHeader(headerKey, fmt.Sprintf(strings.Join(headerValue,"")))
	}
	respBody := recorder.Body.Bytes()
	response.ResponseWriter.WriteHeader(recorder.Code)
	response.Write(respBody)
}
```
