### ISSUE TITLE
save error for logging

### ISSUE THREAD

**Issue by on99** [emicklei/go-restful#220]
when resp.WriteError(code, err) is called, I want the err is saved so that I can create a filter to log all the errors in one place. Of course I can save the error in req.Attributes but it seems weird and will cause too many duplicated code, instead, it's better to keep the error in Response struct.

This feature is pretty easy to implement, by adding one line to WriteError function and adding a property in Response struct.

If it is a good idea, I can submit a pull request. Thank you!

**Comment by emicklei** [comment]
LGTM,  submit the PR with test so I can add this feature. Thanks.
