### ISSUE TITLE
using array/slice with RouterBuilder.Reads 

### ISSUE THREAD

**Issue by johnwilson** [emicklei/go-restful#223]
Hello!

I'm not able to get the swagger docs to generate a model when I pass a slice to the `RouterBuilder.Reads` function.
For example, this piece of code doesn't output any model for body parameter type section the docs:

```go
type Color struct {
    Name string `json:"name"`
}

...
ws.Route(ws.Put("/{user-id}/colors").To(u.updateColors).
    Doc("update user's color choices").
    Param(ws.PathParameter("user-id", "identifier of the user").DataType("int")).
    Reads([]Color{}))
```

Any help would be appreciated.
And thanks for your wonderful work!

**Comment by emicklei** [comment]
This is known issue (to me) and happened in my project too. I remember investigating this and an early conclusion was that swagger 1.2 UI just didn't handle it as expected.  In my project I decided to pass the non-slice version to Reads() instead ; it's only for documentation and not used for runtime decoding. 

Recently, I started working on the swagger2 project and hope to see this fixed (and many other issues).

**Comment by johnwilson** [comment]
It seems one way around this is to include the slice in a Struct:

```go
type Response struct {
    Colors []string `json:"colors"`
} 

...
ws.Route(ws.Put("/{user-id}/colors").To(u.updateColors).
    Doc("update user's color choices").
    Param(ws.PathParameter("user-id", "identifier of the user").DataType("int")).
    Reads(Response{}))
```
