### ISSUE TITLE
WriteHeader(httpStatus.Accepted) delivers httpStatus.Ok

### ISSUE THREAD

**Issue by kontrafiktion** [emicklei/go-restful#224]
When calling

    response.WriteHeader(http.StatusAccepted)

the status is filtered:

    func (r *Response) WriteHeader(httpStatus int) {
        r.statusCode = httpStatus
        // if 204 then WriteEntity will not be called so we need to pass this code
        if http.StatusNoContent == httpStatus ||
                http.StatusNotModified == httpStatus {
                r.ResponseWriter.WriteHeader(httpStatus)
        }
    }

the behaviour is documented, but still very surprising. Case in hand: httpStatus.StatusAccepted will not be returned to the client, when no body (e.g. with WriteEntity) is returned. 

Workaround: 

    response.ResponseWriter.WriteHeader(http.StatusAccepted)

Proposal:
Minimal solution: add StatusAccepted to the states that are directly written
Better: rename WriteHeader to WriteHeaderWhenSuccess or WriteHeaderWhenBody or something like that.

**Comment by emicklei** [comment]
I agree that the behavior is unexpected, but like you said, it is documented. I will add the Accepted as another exception.

As for renaming; it would have made sense to do so in the early days of its existence.
Now, I have to be careful not break the public api of the package.

Btw, the workaround is fine and maybe I will put this in the comment too.

**Comment by fortytw2** [comment]
Would it be breaking to simply not filter `r.WriteHeader()` so that it exhibits the expected behavior, which is that of `r.ResponseWriter.WriteHeader()` ?

**Comment by emicklei** [comment]
True, but the purpose of the override is to capture the statuscode such that filters (logging, etc) could use that information. It is not possible to ask the ResponseWriter to the written status.

In the current design, WriteEntity does not take care of writing the header ; it could have been a parameter though.  So yes, removing the filter code will break the existing behavior. 
Maybe, adding a new function such as WriteHeaderAndEntity will help.

**Comment by emicklei** [comment]
The entityplug merge resolves this issue.
