### ISSUE TITLE
Array return type not rendered properly

### ISSUE THREAD

**Issue by jonathathan** [emicklei/go-restful#228]
Hi, I notice that running `examples/restful-user-service.go` from this repo produces a spec that swagger-ui doesn't seem to like. The resulting swagger-ui page is shown here:

![screen shot 2015-09-04 at 4 56 45 pm](https://cloud.githubusercontent.com/assets/7103322/9696546/2bc2bbd2-5326-11e5-9dc7-9e0a5afc650a.png)

The relevant source code, from `examples/restful-user-service.go`:

```    
ws.Route(ws.GET("/").To(u.findAllUsers).
        // docs
        Doc("get all users").
        Operation("findAllUsers").
        Returns(200, "OK", []User{}))
```

appears to generate this json:

```
  "apis": [
   {
    "path": "/users",
    "operations": [
     {
      "type": "void",
      "method": "GET",
      "responseMessages": [
       {
        "code": 200,
        "message": "OK",
        "responseModel": "array[main.User]"
       }
      ],
```

I played around with it a little and wrote a patch which produces the following, which I _believe_ to be proper Swagger 1.2 syntax (with User -> string for simplicity):

```
  "apis": [
   {
    "path": "/users",
    "operations": [
     {
      "type": "array",
      "items": {
        "type": "string"
      },
      "method": "GET",
      "responseMessages": [
       {
        "code": 200,
        "message": "OK"
       }
      ],
```

and swagger-ui didn't render any response schema, so there may be multiple facets to this bug.

Hope this helps! Also happy to lend a hand if I could be any help :)

**Comment by emicklei** [comment]
thank you for reporting this. I will investigate the issue more.

**Comment by emicklei** [comment]
could be related to https://github.com/emicklei/go-restful/issues/223 which is not solved by the way.

**Comment by emicklei** [comment]
The role of type
https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#523-operation-object

**Comment by emicklei** [comment]
At https://github.com/emicklei/go-restful/blob/master/swagger/swagger_webservice.go#L216 I see that it only takes into account the write sample which is specified by RouteBuilder.Write(interface{}). Now we need to decide what to do when both Returns and Writes have been called.

**Comment by emicklei** [comment]
By searching for related Swagger problems I am starting to think that this is a unsupported feature in spec 1.2. Therefore I am strongly considering not fixing this and instead put my effort in getting support for 2.0 working.

**Comment by jonathathan** [comment]
Thanks for looking into it! 

Given that the modified json blob in my first post wasn't accepted by swagger-ui, I would believe that it's unsupported. Definitely looking forward to 2.0 support :smile:

**Comment by vikstrous** [comment]
Returning an array from an API is a very common use case. It's hard to believe that swagger 1.2 doesn't support it. Is there no workaround for now?

**Comment by emicklei** [comment]
Try this https://github.com/emicklei/go-restful/issues/223

On Mon, Sep 21, 2015 at 9:36 PM, Viktor Stanchev <notifications@github.com>
wrote:

> Returning an array from an API is a very common use case. It's hard to
> believe that swagger 1.2 doesn't support it. Is there no workaround for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/go-restful/issues/228#issuecomment-142087117>
> .
>



-- 
^ Ernest Micklei

http://ernestmicklei.com

**Comment by vikstrous** [comment]
This is the code I'm using:
```
...
		Writes(
		struct {
			Data []userResponse
		}{
			Data: []userResponse{},
		}).
...
```

Model:
```
 struct { Data ||apiserver.userResponse } {
Data (Array[apiserver.userResponse])
}
apiserver.userResponse {
id (undefined),
type (string),
name (string),
ldapLogin (string, optional),
isActive (boolean, optional)
}
undefined {
} 
```

Model Schema:
```
{
  "Data": [
    {
      "type": "string",
      "name": "string",
      "ldapLogin": "string",
      "isActive": true
    }
  ]
}
```

There are several issues with this.
1. The "model schema" doesn't reflect the fact that some of the fields are optional.
2. I think I found another bug: I see uint rendered as `undefined{}`.
3. I want to be able to express the fact that a list item can be a user OR and organization and I'm lucky that the user is a superset of an organization, but that might not always be the case.
4. If I populate the struct it doesn't seem to use its contents, so I can't show an example output. Is there another way to do this?
5. I feel like having `Data: []...` is just as wrong as having just the model without an array, so this is not a real solution.

**Comment by vikstrous** [comment]
This should be fixed for Writes().

**Comment by emicklei** [comment]
@jonathathan , can you confirm that these changes fixes your initial problem?
