### ISSUE TITLE
New method like `Response.WriteHeader` (respects content types in `Produces`)

### ISSUE THREAD

**Issue by truszkowski** [emicklei/go-restful#235]
Method `WriteHeader` doesn't check `Produces` defined in Route / Path.
Before 14 Sep headers was set in `WriteEntity`, because `WriteHeader` just set status code.

**Comment by emicklei** [comment]
That's correct, the new access pattern is to inspect the result of EntityWriter() and if returned false, write the 406 in your application instead.
Reason for this change is that the side effect of writing the header as part of WriteEntity caused problems and would make the pluggable readers/writers feature too complex.

**Comment by ghra** [comment]
In fact in this case problem was different:

We'd like to return code other than http/200 with eg. JSON body attached, and with content-type taken from `Produces` defined in Route / Path. Code seems to be like:

```
response.WriteHeader(404)
response.WriteEntity(object)
```

That works fine a few weeks ago. But after bbafb8e4035 change (fix for #229):
 1. call for `WriteHeader` really push headers into http.ResponseWriter,
 2. call for `WriteEntity` implies call of `writeJSON` which tries to set headers with content-type (see `entity_accessors.go:125`), but the headers was already sent with default text/plain set up before.

**Comment by ghra** [comment]
Commit that changed the behaviour was f1fe10e

**Comment by emicklei** [comment]
At what point were the headers set to default text/plain ? Is this part of your application?

**Comment by ghra** [comment]
Let's play with an example. The goal is to return http/404 response with content-type: application/json

Base code:

```
func main() {
        container := restful.NewContainer()

        ws := new(restful.WebService)
        ws.Path("").Consumes("*/*").Produces(restful.MIME_JSON)
        ws.Route(ws.GET("/ping").To(pingPong))
        container.Add(ws)

        server := &http.Server{Addr: ":8080", Handler: container}
        log.Fatal(server.ListenAndServe())
}

var pong = struct {
        Foo string `json:"foo"`
}{Foo: "123"}
```

Our old case, where the goal was a little different, was:
```
func pingPong(request *restful.Request, response *restful.Response) {
        response.WriteHeader(200)
        response.WriteEntity(pong)
}
```
and such will output:
 * http/200 + application/json when using go-restful up to 8dbf868,
 * http/200 + text/plain when using go-restful newer than 8dbf868.

Answering your question about text/plain - it seems it is default from `http.ResponseWriter`.

Now, back to the main goal, with current HEAD (01a62cf):
```
func pingPong(request *restful.Request, response *restful.Response) {
        response.WriteHeader(404)
        response.WriteEntity(pong)
}
```
outputs http/404 (good) + text/plan (wrong)

Based on the discuss for #229 I hoped it would be possible to use:
```
func pingPong(request *restful.Request, response *restful.Response) {
        response.SetStatusCode(404)  // func (r *Response) SetStatusCode(s int) {r.statusCode = s}
        response.WriteEntity(pong)
}
```
but it outputs http/200 (wrong) + application/json (good).

I think it should be possible to return an error code with content-type based on `Produces`, without need of explicit `AddHeader` call like below:
```
func pingPong(request *restful.Request, response *restful.Response) {
        response.AddHeader(restful.HEADER_ContentType, restful.MIME_JSON)
        response.WriteHeader(404)
        response.WriteEntity(pong)
}
```
(which works fine, except the need of knowing by func what is allowed/designed content-type of the response)

**Comment by truszkowski** [comment]
Some other test case: https://gist.github.com/truszkowski/451e7ea4cc80275ead4e
Tagged `FIXME` places with wrong content-type returned.

Needed new method like `WriteHeader` which will respects `Produces`?

**Comment by emicklei** [comment]
Thank you for your time putting it all together, I will have a close look at this

**Comment by emicklei** [comment]
Are you sending the Accept header for this request?  , should be Accept: application/json

**Comment by emicklei** [comment]
From the golang net/http docs,
```Changing the header after a call to // WriteHeader (or Write) has no effect```
which indicates the problem.

**Comment by emicklei** [comment]
I am considering adding `WriteStatusWithEntity(status int, value interface{}) error` as was suggested earlier by some other contributor

**Comment by emicklei** [comment]
I have create a branch (issue235) for this change. Please have a look

**Comment by emicklei** [comment]
See https://github.com/emicklei/go-restful/commit/c91dde5f04402aef2951d6ec2cce4ba6589086a4 for an api change to fix this.

**Comment by truszkowski** [comment]
Method `WriteStatusAndEntity` work fine, thanks!

**Comment by emicklei** [comment]
Good to get this feedback.  Today, I realised that maybe the function must be called  WriteHeaderAndEntity because it is actually writing the status and header (just like WriteHeader does) before writing the entity.
