### ISSUE TITLE
Access to the Route from within a Request

### ISSUE THREAD

**Issue by vikstrous** [emicklei/go-restful#236]
The only information a request can get about its route seems to be SelectedRoutePath(). It would be very helpful to also have a Route() function on a Request object to get the actual Route object. I want this so that I can log documentation violations at run time. This feature can also enable writing a check for making sure all documented responses have been tested.

**Comment by emicklei** [comment]
The request currently has the selectedRoutePath ; we could replace that with a reference to the Route object and refactor the code unsing this Path without growing the Request struct.

However, how can we prevent applications from modifying this Route ; not all changes are reflected in the underlying datastructure (Router, SwaggerService). How do see that?

**Comment by vikstrous** [comment]
I don't think we need to prevent the application from modifying the route. Just because they can doesn't mean they will... you can just mention in the documentation that they shouldn't.

**Comment by emicklei** [comment]
@vikstrous can we close this?
