### ISSUE TITLE
Write in Body line by line (Streaming)

### ISSUE THREAD

**Issue by tclass** [emicklei/go-restful#246]
I just want to write in the raw Response Body line by line and the client reads until EOF

**Comment by emicklei** [comment]
you can grab the underlying ResponseWriter from restful.Response and call its Write(...)

**Comment by emicklei** [comment]
Feel free to reopen this if you need more help

**Comment by lukepatrick** [comment]
I've got the same question/issue.
If I have a stream and using an io.Copy, I try:
```go
io.Copy(response.ResponseWriter, logReader)
```
as an example. This however causes a `406: Not Acceptable`

**Comment by emicklei** [comment]
could you provide a test or an example for this?  
maybe starting from https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go

**Comment by lukepatrick** [comment]
My bad. io.Copy was misleading. It's a text stream, had to adjust the webservice to produce text, e.g.
```go
Produces(restful.MIME_JSON, restful.MIME_XML, "plain/text", "text/javascript")
```
