### ISSUE TITLE
log package not compatible with google app engine

### ISSUE THREAD

**Issue by APMOadmin** [emicklei/go-restful#247]
the minimal default logger instantiated in the log package does not work for the Google App Engine (GAE) due to the fact that os.Stdout is not available in the GAE environment.
Of course you can instantiate a different logger that works with the GAE, yet it would be nice if the examples actually work in the targeted environment.

Also the standard library defines the default logger to write to os.Stderr (see https://golang.org/pkg/log/ `...That logger writes to standard error and ...`).

> Suggest to change the default logger to use os.Stderr 
> so it works for the GAE _and_ we are in-line with the standard library.

**Comment by emicklei** [comment]
thank you for contributing  (was a bit too eager with my commit until i saw your MR)

**Comment by APMOadmin** [comment]
no worries - thanks !
