### ISSUE TITLE
swagger validation fails for CurlyRouter paths with regexes

### ISSUE THREAD

**Issue by nikhiljindal** [emicklei/go-restful#251]
Swagger validation fails when path contains regex of the form {subpath:*}.

For ex: consider an example as explained in https://github.com/emicklei/go-restful/blob/master/examples/restful-serve-static.go.
```
package main

import (
	"fmt"
	"net/http"
	"path"

	"github.com/emicklei/go-restful"
	"github.com/emicklei/go-restful/swagger"
)

var rootdir = "/tmp"

func main() {
	restful.DefaultContainer.Router(restful.CurlyRouter{})

	ws := new(restful.WebService)
	ws.Path("/resources")
	pathParam := ws.PathParameter("subpath", "subpath of the resource").DataType("string")
	ws.Route(ws.GET("/static/{subpath:*}").To(staticFromPathParam).Param(pathParam))
	restful.Add(ws)

	println("[go-restful] serving files on http://localhost:8080/static from local /tmp")

	swaggerConfig := swagger.Config{
		WebServicesUrl: "http://localhost",
		WebServices:    []*restful.WebService{ws},
		ApiPath:        "/swaggerapi/",
	}
	swagger.RegisterSwaggerService(swaggerConfig, restful.DefaultContainer)

	http.ListenAndServe(":8080", nil)
}

func staticFromPathParam(req *restful.Request, resp *restful.Response) {
	actual := path.Join(rootdir, req.PathParameter("subpath"))
	fmt.Printf("serving %s ... (from %s)\n", actual, req.PathParameter("subpath"))
	http.ServeFile(
		resp.ResponseWriter,
		req.Request,
		actual)
}
```

The generated swagger spec for this is:

```
{
  "swaggerVersion": "1.2",
  "apiVersion": "",
  "basePath": "http://localhost",
  "resourcePath": "/resources",
  "apis": [
   {
    "path": "/resources/static/{subpath:*}",
    "description": "",
    "operations": [
     {
      "type": "void",
      "method": "GET",
      "nickname": "staticFromPathParam",
      "parameters": [
       {
        "type": "string",
        "paramType": "path",
        "name": "subpath",
        "description": "subpath of the resource",
        "required": true,
        "allowMultiple": false
       }
      ]
     }
    ]
   }
  ],
  "models": {}
 }
```

Running swagger-tools validate gives the following error:
```
API Declaration (/resources) Errors:

    #/apis/0/operations/0/parameters/0/name: API path parameter could not be resolved: subpath
    #/apis/0/path: API requires path parameter but it is not defined: subpath:*

2 errors and 0 warnings
```

The validation code expects the path name to be `subpath:*` which is not a valid name (The generated client will have code like: public `String staticFromPathParam(String subpath:*)`)

I do not know what the correct spec is (asking it here: https://github.com/swagger-api/swagger-spec/issues/502), but wanted to let you know that the currently generated spec is incorrect.

**Comment by nikhiljindal** [comment]
As per discussion in https://github.com/swagger-api/swagger-spec/issues/502, swagger-spec does not support such paths. They are considering supporting it in the next version: https://github.com/swagger-api/swagger-spec/issues/291

**Comment by emicklei** [comment]
Thank you for reporting and investigating this.  

We could change the path reference in the generated spec to {subpath} instead and let the Route still use the wildcard. I don't know how code generation tools handle this though.

**Comment by nikhiljindal** [comment]
Yes that should work for us.

**Comment by emicklei** [comment]
I have created branch issue251 with an implementation as suggested. Please review this. Thanks

**Comment by nikhiljindal** [comment]
Thanks! I tested with that branch and it fixes our issue.
Please let us know when you merge it in the master branch.

**Comment by emicklei** [comment]
The change has been merged. Thank you
