### ISSUE TITLE
how can I get the post or patch body content？

### ISSUE THREAD

**Issue by xwlcn** [emicklei/go-restful#259]
I want to get the body content,but I only see a function BodyParameter,and it should sent a param,so how can I get the post or patch full body content？

**Comment by emicklei** [comment]
this will get you started.

```
func handlePost(request *restful.Request, response *restful.Response) {
    defer request.Request.Body.Close()
    data , err := ioutil.ReadAll(request.Body)
    if err != nil {
      response.WriteErrorString(400, "unable to read POST data")
      return
    }
   // work with data ( []byte )
}
```

**Comment by xwlcn** [comment]
thanks.

**Comment by ramnar** [comment]
> this will get you started.
> 
> ```
> func handlePost(request *restful.Request, response *restful.Response) {
>     defer request.Request.Body.Close()
>     data , err := ioutil.ReadAll(request.Body)
>     if err != nil {
>       response.WriteErrorString(400, "unable to read POST data")
>       return
>     }
>    // work with data ( []byte )
> }
> ```

ioutil.ReadAll(request.Body) should actually be ioutil.ReadAll(request.Request.Body)
