### ISSUE TITLE
Higher level error reporting abstraction

### ISSUE THREAD

**Issue by vikstrous** [emicklei/go-restful#260]
I think it makes sense for this framework to include a built in higher level error reporting system. This came up when discussing generalized input parsing in #257.

I was thinking of something like the following.

Add this interface:

``` go
type RestfulError interface {
    HTTPCode() int
    ErrorCode() interface
    Message() string
    Detail() interface
}
```

A slice of these structs would be serialized into the following (in json, xml, whatever):

``` json
{
    "errors": [
        {
            "code": "ERROR1",
            "message": "There was an error",
            "detail": null
        },
        {
            "code": "ERROR2",
            "message": "There was another error",
            "detail": null
        },
    ]
}
```

```
{
    "errors": [
        {
            "code": "ERROR_BAD_FORM",
            "message": "",
            "detail": {
                "email": "Invalid Email",
                "name": "Name too short.",
            }
        }
    ]
}
```

The `code` can be a string, int, or whatever the application wants to use.

The `message` is a human readable message.

The `detail` field can be used to specify additional information. If a user does not exist, the username of the user. If a form input is invalid, the list of errors. Etc.

The response code would be the HTTPCode() of the first error. Most of the time there will be only one error, so that's correct. In most other cases the errors will all have the same HTTPCode(). If they differ, then it can be considered a bug in the application, but I don't think there's any need to check this.

Next, the errors can be documented in the route builder using `.Error(...RestfulError)` and they can be written using `.WriteError(...RestfulError)` on the Response object.

Open questions:
- Does it make sense to allow multiple errors? (the detail field can be used for forms and more complex errors)
- Should the error writing be completely customizable using a custom function?
- Should these features be provided by a separate higher level library?

**Comment by emicklei** [comment]
To answer your last question, it would be nice if go-restful is build such that these kinds of higher level library can exist.
