### ISSUE TITLE
Example restful-swagger.go does not produce the document tags

### ISSUE THREAD

**Issue by 4piggies4me** [emicklei/go-restful#261]
running the example restful-swagger.go (tag v1.2) and retrieving the json via 'curl http://localhost:8080/apidocs.json' gives as an empty documentation result:
```json
{
  "swaggerVersion": "1.2",
  "apis": [
   {
    "path": "/books",
    "description": ""
   }
  ],
  "apiVersion": "",
  "info": {
   "title": "",
   "description": ""
  }
 }
```

**Comment by emicklei** [comment]
what do you expect to see?  this is the listing. you get docs about the books resource if you ask for `http://localhost:8080/apidocs.json/books`.  

The info part is empty because it was not specified in the example (this is because that feature was added later).

**Comment by 4piggies4me** [comment]
Ok, using the suggested url does indeed give documentation details. thx
