### ISSUE TITLE
How to cleanly handle SIGTERM ?

### ISSUE THREAD

**Issue by allan-simon** [emicklei/go-restful#264]
I would like to know if there's a predefine way to treat SIGTERM, (by un-registering webservices for example) in a way that no request get cut in the middle (i.e the request being treated are finished to be treated but no new connection are accepted)

**Comment by nullbus** [comment]
I'm currently use https://github.com/facebookgo/httpdown to perform graceful shutdown of http server.

The code will be like this

```go
		container := restful.NewContainer()
		// do handlers registration
		// ...

		// server configuration
		port := "80"
		server := &http.Server{
			Addr:    net.JoinHostPort("", port),
			Handler: container,
		}

		hd := &httpdown.HTTP{
			StopTimeout: 10 * time.Second,
			KillTimeout: 1 * time.Second,
		}

		// start!
		fmt.Printf("HTTP listen start on port %s\n", port)
		fmt.Println(httpdown.ListenAndServe(server, hd))

```

Graceful shutdown works pretty well with this code, but it would be great if go-restful package includes this feature.

**Comment by allan-simon** [comment]
Thanks, in the meantime I've found `go get gopkg.in/tylerb/graceful.v1`

and I replaced 

```
       log.Fatal(http.ListenAndServe(":"+port, nil))
```

by 

```
       graceful.Run(":"+port, 10*time.Second, nil)
```

**Comment by emicklei** [comment]
Thank you @nullbus and @allan-simon for sharing your solutions. I will have a look at both solutions to see whether we should add this feature or just add another example instead.

**Comment by emicklei** [comment]
I think it can be closed because the question was answered as code change is not necessary.

**Comment by allan-simon** [comment]
no problem for me for it to be closed :)
