### ISSUE TITLE
restful Always Prefers XML or JSON over other content types

### ISSUE THREAD

**Issue by mankyd** [emicklei/go-restful#265]
restful documents `RegisterEntityAccessor` (https://godoc.org/github.com/emicklei/go-restful#RegisterEntityAccessor) but this function does not work as expected.

I tried to write a custom writer that could generate plain HTML responses for developing, and it never uses it. That is to say, my browser says it accepts `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`. As soon as restful sees `*/*` it forces the use  of xml or json, depending on which comes first in the `produces` field.

In `response.go`, in `EntityWriter()`, JSON and XML are hardcoded into the package: https://github.com/emicklei/go-restful/blob/d74948d530a30ad5315b769d709626e94853a7d5/response.go#L74

It would seem more appropriate to use the order of content types as they appear in the header.

Even more precisely, if following the standard around the `quality` parameter (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), all the content types at quality 1 (text/html,application/xhtml+xml, and image/webp) should be preferred before falling to .9 (application/xml), which in turn should be preferred to .8 (\*/\*).

**Comment by emicklei** [comment]
Thank you for reporting this.  
Indeed, as can be read in the comment (i think), the quality parameter is not yet taken into consideration. This needs to be fixed.

**Comment by mankyd** [comment]
Yeah, even in the short term, it would be great if the order of the accept headers was taken into consideration. `*/*` should at least be demoted to last resort.

**Comment by emicklei** [comment]
@mankyd , I had a closer look to the method and realized it is a bad implementation in the sense that it uses the wrong order. I hope to find time to fix it today

**Comment by emicklei** [comment]
I have pushed the Issue265 branch with the first implementation. Tests pass but I want to add a few more cases before merging. Please review the changes.

**Comment by mankyd** [comment]
Looking at the code for matching `*/*`, it still favors JSON and XML over other entries in `routeProduces`. Why not just loop over `routeProduces` and check its contents in order?

https://github.com/emicklei/go-restful/commit/71cd3343b9657137abe9c17e28be820a34931273

The other comment I would make is that you are doing a string comparison for the q values. I think, technically, this will work for properly formatted q's, but it may return unexpected results for malformed headers. Maybe try to convert the q value to floats, and throw away values that don't convert cleanly?

**Comment by emicklei** [comment]
Thank you for your comments.
The first one suprises me because that's exactly what the new code is doing. Only when no element in produces matches then it is considering the */*

The second commit I agree on that; it's it not robust enough.

**Comment by emicklei** [comment]
I just merged my changes that fixed the issue. feel free to re-open this issue if you find it does not fit.
