### ISSUE TITLE
Accept Header mediatype: breaking change

### ISSUE THREAD

**Issue by kontrafiktion** [emicklei/go-restful#269]
From the Changelog: "take the qualify factor of the Accept header mediatype into account when deciding the contentype of the response".
This change is breaking some of our services and clients. Admittedly, they are not correctly implemented. 
We have services that normally send JSON but in error cases send plain text. And we have clients, that officially only accept JSON, but can handle text as well. But this is a breaking change for us.  

Would it be possible to add a flag? If "on" the new behaviour is activated, if "off" only a warning/error is logged.

If not, please just take this issue as a caveat for future changes.

**Comment by emicklei** [comment]
Thank you for reporting your issue and feedback on the change. 
To evaluate possible alternatives, would that "flag" be on package level, per Route or per Request?
Maybe the framework needs some callback such that services can handle potential 406 situations or an explict check on the request.

**Comment by kontrafiktion** [comment]
I see two possible places.On the "WebService" level:

       ws := new(restful.WebService)
       ws.AcceptHandling(restful.LenientAcceptHandling)

or on the package level:

      restful.AcceptHandling(restful.LenientAcceptHandling)

**Comment by emicklei** [comment]
The recent change for Issue 265 was a fix to a long outstanding problem with the Accept header.
Putting in any behavior to keep that alive is not what I want ; such features will create smells in any framework (and there are already some that cannot be removed without really breaking the api).

I see several options for you to handle your current status. The obvious one is just not to upgrade.
Another more realistic one is to fork the project and make the changes you need now yourself and motivate the team to actually fix the services (it may be difficult for the client to behave).

**Comment by kontrafiktion** [comment]
You are right. Don't fix this. We will clean up on our side.

But please: as long as Golang has no simple way of declaring dependencies on a _version_ of a library, try to be as careful as possible when you change anything ...
