### ISSUE TITLE
How to enable CORS

### ISSUE THREAD

**Issue by the42** [emicklei/go-restful#27]
in net/http I would do the following:

```
if origin := req.Header.Get("Origin"); origin != "" {
    w.Header().Set("Access-Control-Allow-Origin", origin)
}
```

Where is the right place to enable CORS in go-restful? I would assume a filter ...

**Comment by yasser1984ir** [comment]
Isn't this how you would do the same?

https://github.com/emicklei/go-restful/blob/master/examples/restful-CORS-filter.go

**Comment by emicklei** [comment]
i think the OPTIONSFilter is no longer needed (in the example). Have to verify that.

**Comment by yasser1984ir** [comment]
This ultimately worked for me, and OPTIONSFilter was unnecessary.

```go
	cors := restful.CrossOriginResourceSharing{
		ExposeHeaders:  []string{"X-My-Header"},
		AllowedHeaders: []string{"Content-Type", "Accept"},
		AllowedDomains: []string{FrontEndDomain},
		CookiesAllowed: false,
		Container:      wsContainer}
	wsContainer.Filter(cors.Filter)
```
