### ISSUE TITLE
Regression: Request now requires "Accept" header set

### ISSUE THREAD

**Issue by nikhiljindal** [emicklei/go-restful#272]
Steps to repro:
* `go run examples/restful-curly-router.go`
* Post a request for user with user-id 1 at `http://localhost:8080/users`
* Use `resp, err := http.Get("http://localhost:8080/users/1")`

Expected: Get a 200 response.
Actual: Getting a `406 Not Acceptable` response.

The following works fine:
```
client := &http.Client{}
req, _ := http.NewRequest("GET", "http://localhost:8080/users/1", nil)
req.Header.Set("Accept", "application/json")
resp, err := client.Do(req)
```
This gives the right 200 status response. Commenting out the Header.Set() line gives 406 response.

This seems to have changed recently. I was trying to update go-restful in kubernetes, when I observed this because our tests broke https://github.com/kubernetes/kubernetes/pull/22897.
It used to work fine without setting the Accept header.

I can drill down the code and try to find the culprit, but first wanted to make sure that this change is not intentional.

Is this an intentional change in behavior?

**Comment by emicklei** [comment]
Thank you for reporting this. I will investigate this too ; it was not intentional. Now that you mentioned this, I recall to have similar issues in my other project for which i was forced? to add a Consumes("*/*") to the route.

**Comment by emicklei** [comment]
the example you tried does indeed specify the mimetypes to accept.  https://github.com/emicklei/go-restful/blob/master/examples/restful-curly-router.go#L36

I will look again how an empty Accept header is handled now and why/how it was changed in the past.

**Comment by emicklei** [comment]
At https://github.com/emicklei/go-restful/blob/master/response.go#L90 the header is inspected and as you can see, the DefaultResponseMimeType is inspected to see whether a JSON or XML is preferred. 

I see a few options:
- you set the default using DefaultResponseContentType(..)
- you add an Accept header in the client, could also be */* which means the service decides
- we add another fallback at line 98 to return JSON  ( interpret empty Accept header  as */* )

**Comment by nikhiljindal** [comment]
As per: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

> If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.

Hence client should not be required to add an Accept header.
I think adding a fallback at line 98 to return one of the Produces Content-Type is best.

**Comment by emicklei** [comment]
@nikhiljindal thank you for investigating this. I will make the change

**Comment by nikhiljindal** [comment]
Thanks for the fix.
Am adding a test in https://github.com/emicklei/go-restful/pull/273 so that it is easier to catch such issues in future.

**Comment by nikhiljindal** [comment]
Thanks for merging #273 
Closing this issue.
