### ISSUE TITLE
Container cannot remove the webservice completely

### ISSUE THREAD

**Issue by uruddarraju** [emicklei/go-restful#274]
We had an issue in kube while trying to remove a webservice and add it back to the container, that is captured here: https://github.com/kubernetes/kubernetes/issues/23831#

We noticed that the container.Remove() [[here](https://github.com/emicklei/go-restful/blob/master/container.go#L129)] function only removes the webservice from the registered webservices list but does not undo the HandleFunc call it does during Add ([here](https://github.com/emicklei/go-restful/blob/master/container.go#L107)) which populates the net/http ServeMux.m map, so after a remove net/http server.go still maintains a map of the routes to the handler functions, that is not cleaned up during a delete. So if we remove a webservice from a container and try to add it back, it fails with the panic `multiple registrations found`

Was able to reproduce the issue today, where I was able to successfully add a webservice to a container, remove it and when I add it back, I see the following issue:

```
panic: http: multiple registrations for /users
```

I tried the example here: https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go. And changed the lines https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go#L74 to do,

```
	container.Add(ws)
	container.Remove(ws)
	container.Add(ws)
```

This created the panic above. Can you suggest if there is something else we can do or how can this be solved ?

**Comment by emicklei** [comment]
Thank you reporting this issue. I will have a look at this starting with your example

**Comment by emicklei** [comment]
I think the `Remove` has to change by creating a new ServeMux,  add all the remaining webservices to it and assign it to the ServeMux of the container. However, this can only be done if the ServeMux was not the default one (http.DefaultServeMux) because other parts of the application might have added handlers too. 
I need to think about this a bit more.

**Comment by lavalamp** [comment]
@emicklei That was basically my conclusion as well.

Remove should probably just return an error if you're using the default serve mux?

**Comment by emicklei** [comment]
Please have a look at https://github.com/emicklei/go-restful/commit/809fb70444f258736128d19badc901da3cd3256b

**Comment by emicklei** [comment]
I will keep the branch alive until someone needs this feature later.

**Comment by brendandburns** [comment]
I created a patch (#289) which just tests and doesn't re-add if the path has already been added.  All paths always map to `c.dispatch` anyway.
