### ISSUE TITLE
Improper routing in paths with double slash ( ie http://google.com// )

### ISSUE THREAD

**Issue by ReneKroon** [emicklei/go-restful#277]
JSR-311 implements RFC3986 which allows double slashes as a 'path-abempty' component in urls. 
See https://tools.ietf.org/html/rfc3986#section-3.3

Valid URL's can also be verified for example at http://www.websitedev.de/temp/rfc3986-check.html.gz

Go-rest gives a 'Moved Permanently' reply instead of accepting these requests. If the user expects json or xml, this actually cascades in a HTTP 406 error due to the response being plain/text. This is not nice behaviour for legal URL's

exact: Normalization according to paragraph 5.2 in the RFC eliminates the slash with step E in 5.2.4

**Comment by emicklei** [comment]
Thank you for reporting this. Can you provide a test that shows the issue with expected (JSR) behavior?

**Comment by emicklei** [comment]
Note: your http client could be configured to follow the redirect as a response to the 301. Eg.
```
curl -X GET --header 'Accept: application/json' 'http://localhost:8080///users///1' -L
```
for the given example `go run restful-user-resource.go`

**Comment by emicklei** [comment]
Note: Normalization of the base URI, as described in Sections 6.2.2 and  6.2.3, is optional.

I am hesitated to implement all the normalization methods described in the spec; IMHO you do not need it for services.

**Comment by ReneKroon** [comment]
workable.

**Comment by argoyb** [comment]
FYI use case which redirect was confusing: I'm configuring nginx as a proxy to other services, e.g.:
```
server {
  listen 80;

  location /orders {
      proxy_pass http://order-service.company.com/;
      proxy_request_buffering off;
  }

  location /profiles {
     proxy_pass http://profiles-service.company.com/;
     proxy_request_buffering off;
  }
}
```

"profiles service" is in java - working ok, "orders service" is in go-restful, returns 301. Took some time to figure out what's going on (solution to the problem: add `/` to the end: `location /orders/`)
