### ISSUE TITLE
Content-Type required on empty POST

### ISSUE THREAD

**Issue by ReneKroon** [emicklei/go-restful#278]
RFC 7231 does not state that an empty payload should have a Content-Type header:

   A sender that generates a message containing a payload body SHOULD
   generate a Content-Type header field in that message unless the
   intended media type of the enclosed representation is unknown to the
   sender.  If a Content-Type header field is not present, the recipient
   MAY either assume a media type of "application/octet-stream"
   ([RFC2046], Section 4.5.1) or examine the data to determine its type.

Currently i get a http 415 on these POST requests without a body. JSR-311 does allow this though. Im not sure how to fix this at this time as any Consumes(restful.MIME*) route would be valid for these kinds of requests.

**Comment by emicklei** [comment]
you can set it like this 
```
.Consumes("application/octet-stream")
```

**Comment by emicklei** [comment]
please have a look at the test and if not convinced, do provide a test that demonstrates this issues.

**Comment by ReneKroon** [comment]
was fixed withe .Consumes(.. part
