### ISSUE TITLE
Add support for Messagepack mime type?

### ISSUE THREAD

**Issue by bailantaotao** [emicklei/go-restful#279]
I'm developing a feature for HTTP request/response via message pack.

i have tried to use mime type: application/octet-stream
but i cannot read any body since application/octet-stream not register in accessor (RegisterEntityAccessor)

According to my observations, i can not found any support in your library, and interface of EntityReaderWriter support XML, JSON only.

do you have any idea?
or i have to implement the EntityReaderWriter for message pack?

**Comment by emicklei** [comment]
You are right that one have to implement an EntityReaderWriter for other mime types such as message pack. 

The `entity_accessors_test.go` has an implementation for simple key values ; it is just an example.
Let me know if you need help implementing this.

**Comment by bailantaotao** [comment]
can i send a pull request when i done this feature?

**Comment by emicklei** [comment]
I propose you create an example instead and a PR for it.

Reason for not accepting this as a feature of go-restful itself is to avoid adding external dependencies (I assume you are going to use another package for the actual implementation of messagepack).

For example, you could make a `msgpack_entity.go`  and a `restful-msgpack-io.go` in the examples folder once you created the feature in your fork.

**Comment by bailantaotao** [comment]
ok, thanks for you comments

I have the other problem. 
I want to read byte slices from request.body, so i must to use Octet of mime type.
But it not implemented in your library, so i also likes to implement in EntityReaderWriter?
Do you have any recommends?
And this feature do a PR?

**Comment by emicklei** [comment]
Hi,

You can use restful.MIME_OCTET in your Consumes.

For reading the bytes from a Body, use request.Request.Body which is a
io.ReadCloser  (here, request is of type *restful.Request).

If it helps, I can setup a small prototype to get you started.


On Thu, Apr 14, 2016 at 10:36 AM, bailantaotao <notifications@github.com>
wrote:

> ok, thanks for you comments
>
> I have the other problem.
> I want to read byte slices from request.body, so i must to use Octet of
> mime type.
> But it not implemented in your library, so i also likes to implement in
> EntityReaderWriter?
> Do you have any recommends?
> And this feature do a PR?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/go-restful/issues/279#issuecomment-209828988>
>



-- 
Ernest Micklei
*Ubanita.com*

**Comment by bailantaotao** [comment]
oh...i'm very happy if you can help me by head :D:D:D
thanks!!

btw, i have implemented MessagePack entity, could you help me to see where is needed improvement?
https://github.com/bailantaotao/go-restful/pull/1/files

**Comment by emicklei** [comment]
Hi,

With your changes you are on the right track. However, as mentioned in my previous comment, I will not accept a PR that add this feature to the framework itself for reasons explained earlier. 
You can ofcourse keep it in your own fork. 
I do accept a PR which adds an example.

I will now comment on your implementation.

**Comment by bailantaotao** [comment]
hi 
i have finished your comments.
So i can adds an example PR for your repository when i don't have any changes in framework? right?

**Comment by emicklei** [comment]
That's correct.  I suggest you add the example under examples, so we have

/go-restful/examples/
/go-restful/examples/google_app_engine
/go-restful/examples/msgpack


On Fri, Apr 15, 2016 at 6:26 AM, bailantaotao <notifications@github.com>
wrote:

> hi
> i have finished your comments.
> So i can adds an example PR for your repository when i don't have any
> changes in framework? right?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/go-restful/issues/279#issuecomment-210282143>
>



-- 
Ernest Micklei
*Ubanita.com*

**Comment by bailantaotao** [comment]
thank you very much

i will send the PR when i finished

**Comment by bailantaotao** [comment]
hello, 
i have added a PR in #282 
thanks
