### ISSUE TITLE
202 with body cause annoying log message

### ISSUE THREAD

**Issue by hafe** [emicklei/go-restful#284]
Keep getting this:
http: multiple response.WriteHeader calls

I know it is because of:
resp.WriteHeader(202)
resp.WriteEntity(somedata)

How do I change this to get rid of the log but keeping a body with a 202?

Thanks,
Hans

**Comment by emicklei** [comment]
use WriteHeaderAndEntity instead

**Comment by hafe** [comment]
Thanks! I was using a pre 1.2 version so I didn't see the new method.
