### ISSUE TITLE
CrossOriginResourceSharing support domain regex check

### ISSUE THREAD

**Issue by AdoHe** [emicklei/go-restful#285]
FYI. now the `CrossOriginResourceSharing` use strictly equal to check whether the origin is allowed, should we add regex support here?

**Comment by emicklei** [comment]
yes, good suggestion. can you send a PR?

On Friday, April 29, 2016, TonyAdo <notifications@github.com> wrote:

> FYI. now the CrossOriginResourceSharing use strictly equal to check
> whether the origin is allowed, should we add regex support here?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/go-restful/issues/285>
>


-- 
Ernest Micklei
*Ubanita.com*

**Comment by AdoHe** [comment]
@emicklei sure, I will send a PR a tomorrow.

**Comment by AdoHe** [comment]
Landed in #286.
