### ISSUE TITLE
Why declare Param when Routing and request it again in functions?

### ISSUE THREAD

**Issue by harryge00** [emicklei/go-restful#288]
In [restful-user-resource.go](https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go#L51)
```
ws.Route(ws.GET("/{user-id}").To(u.findUser).
		// docs
		Doc("get a user").
		Operation("findUser").
		Param(ws.PathParameter("user-id", "identifier of the user").DataType("string")).
```
It seems duplicate to declare `Param()`  because in `findUser()`, we have to get 'user-id'  by `request.PathParameter("user-id")`.  Even without `Param`, the program works fine....

On the other hand, if I declare DateType when routing, can I get the corresponding type automatically in business functions? For example:
```
ws.Route(ws.GET("/{user-id}").To(u.findUser).
		Param(ws.PathParameter("user-id", "identifier of the user").DataType("int"))
```
Then in findUser:
```
var user-id int
user-id = request.PathParameter("user-id")
```

**Comment by emicklei** [comment]
The only reason for calling Param on the RouteBuilder is to provide some documentation when generating the Swagger document (so says the comment).  Actually the Operation() can be omitted unless you want the operation to be different from the function name.

As for type conversion, that would be a nice feature but unfortunately that is not possible in Go. We could add functions such as IntPathParameter("user-id") but then it would return 2 values, int and error and you would produce a BadRequest when the "user-id" cannot be converted to an int.

**Comment by harryge00** [comment]
thanks so much!
