### ISSUE TITLE
Removing a web service and then re-adding on the same path it causes a panic

### ISSUE THREAD

**Issue by brendandburns** [emicklei/go-restful#289]
This is because the path is registered with the ServeMux and can't be unregistered.

See: https://github.com/emicklei/go-restful/pull/287 for a workaround.

**Comment by emicklei** [comment]
I do have a branch (issue274) that implements the expected behavior. I will check #287 and see what to merge/include.

**Comment by emicklei** [comment]
@brendandburns, I think you call it a workaround because it does not actually remove the handlers right ; it prevents duplicate registrations.  Could you have a look at the branch to see if that would be a proper solution.

**Comment by brendandburns** [comment]
@emicklei yeah, that looks like it would work correctly also.  It's up to you which one you prefer.  But I would like to get this fixed one way or the other.

Thanks!

**Comment by emicklei** [comment]
merged https://github.com/emicklei/go-restful/commit/0e9e201e5de4f54c61e6d09aef44c4cfde43ede6

**Comment by brendandburns** [comment]
Awesome, thanks @emicklei I'll rev our dependencies in kubernetes
