### ISSUE TITLE
ReadEntity on GET method

### ISSUE THREAD

**Issue by Fantasim** [emicklei/go-restful#293]
Hey,

I would like to read an entity on GET method but i get this error "EOF" (if i try with POST method it works)

Have u an idea?

Thank's :)

**Comment by emicklei** [comment]
no idea yet but i will do a test myself

**Comment by Fantasim** [comment]
ok thanks :)

**Comment by Fantasim** [comment]
have u do some test ?

**Comment by emicklei** [comment]
Using the example

`go run restful-user-resource.go`

and changing the createUser mapping on line 62 to use a GET

     ws.Route(ws.GET("").To(u.createUser).
		// docs
		Doc("create a user").
		Operation("createUser").
		Reads(User{})) // from the request

I was able to process an entity using the GET method with the following curl test:

` curl http://localhost:8080/users -X GET --data '<User><Id>2</Id><Name>Melissa</Name></User>' -H "content-type:application/xml" -v`

	*   Trying ::1...
	* Connected to localhost (::1) port 8080 (#0)
	> GET /users HTTP/1.1
	> Host: localhost:8080
	> User-Agent: curl/7.43.0
	> Accept: */*
	> content-type:application/xml
	> Content-Length: 43
	> 
	* upload completely sent off: 43 out of 43 bytes
	< HTTP/1.1 201 Created
	< Content-Type: application/json
	< Date: Tue, 14 Jun 2016 18:44:46 GMT
	< Content-Length: 37
	< 
	{
	  "Id": "2",
	  "Name": "Melissa"
	* Connection #0 to host localhost left intact
	 }

**Comment by Fantasim** [comment]
nice thanks i will try with xml

**Comment by emicklei** [comment]
feel free to re-open if you still have the issue
