### ISSUE TITLE
RecoverHandleFunction should include http.Request

### ISSUE THREAD

**Issue by cvle** [emicklei/go-restful#295]
I wish the _RecoverHandleFunction_ would include the http.Request.
Without this I have no way to determine which Content-Type the client accepts.
Any idea how to get this implemented? It's backward-incompatible to just
change the RecoverHandleFunction.

**Comment by cvle** [comment]
Ok just got an idea. I'lll experiment achieving this with filters instead of the built-in RecoverHandler. On the first glance this might be possible.

**Comment by emicklei** [comment]
Yes, you are right. Unfortunately, the signature of the function could have been chosen better.

It might be an option to change it but I have no idea how/if developers are using this feature.

Let me know if you found a workaround.

**Comment by cvle** [comment]
Yes it works using filters. I use the following workaround:
```
func recoverFilter(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
    defer func() {
        if r := recover(); r != nil {
            panicHandler(r, req, resp)
            return
        }
    }()
    chain.ProcessFilter(req, resp)
}

 func panicHandler(err interface{}, req *restful.Request, resp *restful.Response) {
    ...
}

restful.Filter(recoverFilter)
```
