### ISSUE TITLE
passes lock by value to RegisteredWebServices: restful.Container contains sync.RWMutex

### ISSUE THREAD

**Issue by mbohlool** [emicklei/go-restful#299]
I found this while running go-vet tools. I suggest we pass Container by reference to all methods (not only RegisteredWebServices)

**Comment by mbohlool** [comment]
Routes method in web_service.go has the same problem accessing routesLock on a passed by value object. The same suggestion for that file, passing WebService by reference to all methods.

**Comment by emicklei** [comment]
thx, I just run the vet tool and confirmed your findings. I will investigate the remaining as well.
