### ISSUE TITLE
multiple and same query parameters

### ISSUE THREAD

**Issue by leonchen83** [emicklei/go-restful#302]
hi
We want to parse query parameter as below
http://localhost:8080/users?userid=12345&userid=123456

but when we use request.QueryParameter("userid"). this method only return 1 param
userid = 12345

as I know I can use below code to work around
        if m := request.Request.Form;m == nil {
        request.Request.ParseMultipartForm(32 << 20)
    }
    m := request.Request.Form["userid"];
    for _,v:= range m {
        log.Println(v)
    }
but could we do better on this issue?

**Comment by emicklei** [comment]
Yes, we could introduce another function that returns the slice of values, e.g. `ListQueryParameter`

**Comment by emicklei** [comment]
Anybody else interested in this feature?

**Comment by emicklei** [comment]
I am closing this as there is no need for this. Feel free to re-open this issue or better, send a PR
