### ISSUE TITLE
restful v2

### ISSUE THREAD

**Issue by emicklei** [emicklei/go-restful#306]
The idea is to start a new repository (but keeping the package name) that will introduce a new, improved, API to create REST-like applications in Go. With respect to the current status, this will be a major change (hence the v2) as I expect to see a few changes to the current API.

This issue will list the things I like to change/improve
- move Swagger to its own repository allowing for a 2.0 OpenAPI support
- RouteFunction will have a Context parameter (as the last?)
- Replace public vars by functions
- Use CurlyRouter by default
- No caching of request content by default
- Introduce a static container in addition to the current one that allows add/remove WebServices
- Remove request attributes in favor of Context

Other suggestions are welcome.

**Comment by vikstrous** [comment]
My thoughts in no particular order:

I think it's best to stick to the convention of passing a context as the first parameter.

I may be wrong, but I doubt anyone would be upset if the new gorestful 2 supported only swagger 2 and not 1.2.

It would be cool if parts of go-swagger can be reused here, if not all of it.

On July 13, 2016 4:26:02 PM CDT, Ernest Micklei <notifications@github.com> wrote:
>The idea is to start a new repository (but keeping the package name)
>that will introduce a new, improved, API to create REST-like
>applications in Go. With respect to the current status, this will be a
>major change (hence the v2) as I expect to see a few changes to the
>current API.
>
>This issue will list the things I like to change/improve
>
>- move Swagger to its own repository allowing for a 2.0 OpenAPI support
>- RouteFunction will have a Context parameter (as the last?)
>- Replace public vars by functions
>- Use CurlyRouter by default
>- No caching of request content by default
>- Introduce a static container in addition to the current one that
>allows add/remove WebServices
>- Remove request attributes in favor of Context
>
>Other suggestions are welcome.
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/emicklei/go-restful/issues/306

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AdoHe** [comment]
Really look forward to this, @emicklei could you paste the new repository location here?

**Comment by emicklei** [comment]
fyi, i am working on an initial version that includes the Context. Once all tests pass , I will create the initial commit (which will still be WIP though)

**Comment by AdoHe** [comment]
I think I have time to help with the new version. So really look forward to your init commit.

**Comment by emicklei** [comment]
@AdoHe , thank you for offering the time to help. When I return from holidays, I will continue with this.

**Comment by emicklei** [comment]
Today, I have second thoughts about starting a new repository. This was motivated by the future fact that two repos need to be maintained. So, what if I could change the existing repo?

First of all, I think it will have a swagger2 directory containing all the code to produce the Swagger 2 spec JSON. Second, I think about changing the defaults to the common use. Next, I think I will remove very special features that almost nobody uses. The latter will break the API ; to communicate that I start with 2.0 tag and release.

**Comment by AdoHe** [comment]
Generally I am ok with this, maintain two repos is not always that easy. So what about the original todo lists:

* move Swagger to its own repository allowing for a 2.0 OpenAPI support
* RouteFunction will have a Context parameter (as the last?)
* Replace public vars by functions
* Use CurlyRouter by default
* No caching of request content by default
* Introduce a static container in addition to the current one that allows add/remove WebServices
* Remove request attributes in favor of Context

what should we do in v2? Seems swagger won't be moved to a new repo.

**Comment by AdoHe** [comment]
@emicklei

**Comment by JoakimSoderberg** [comment]
When you are talking about `Context` do you refer to this: https://golang.org/pkg/context/#Context ?

At least I think it would be nice to easily be able to inject this in go-restful, so that the Request itself has the context.

This way normal HTTP Handler interface can be used:
```
type Handler interface {
        ServeHTTP(ResponseWriter, *Request)
}
```
But maybe that is changing the design of go-restful too much? I am a beginner at go :)

**Comment by emicklei** [comment]
@JoakimSoderberg 

yes, restful Request will provide access to the context of http Request 
https://golang.org/src/net/http/request.go?s=10298:10357#L280

**Comment by emicklei** [comment]
@AdoHe 

- move Swagger to its own repository allowing for a 2.0 OpenAPI support

add package github.com/emicklei/go-restful/swagger2 that probably will use https://github.com/go-swagger/go-swagger

- RouteFunction will have a Context parameter (as the last?)

that is not needed if we follow the design of http.Request w.r.t ctx

- Replace public vars by functions

add those functions and document the var being deprecated.

- Use CurlyRouter by default

this we can change and document

- No caching of request content by default

I regret merging this feature into the package. After removing it, I want to create an example using a filter that achieves the same.

- Introduce a static container in addition to the current one that allows add/remove WebServices

this can be added without api changes (i hope)

- Remove request attributes in favor of Context

this is an implementation detail so that should not be difficult.

**Comment by JoakimSoderberg** [comment]
@emicklei Hmm yes but why have a separate Context parameter? It is accessible via `http.Request.Context()` in Go 1.7+ ... Unecessary to bloat the function signature is what I mean?
https://joeshaw.org/revisiting-context-and-http-handler-for-go-17/

So maybe have something similar? Keep the signature like it is:
```
type RouteFunction func(*Request, *Response)
```
Why bloat this (and break old API) with this:
```
type RouteFunction func(*Request, *Response, *Context)
```
When you already can access this from the `http.Request`, like so: `Request.Request.Context()`

Again, I might be missunderstanding things :) Maybe this is the same thing that you mean by:

> that is not needed if we follow the design of http.Request w.r.t ctx

**Comment by emicklei** [comment]
yes, that is my intention. The extra parameter in RouteFunction is not needed. That was my conclusion after looking more closely to http.Request 1.7 implementation.

**Comment by emicklei** [comment]
status

- [to decide] move Swagger to its own repository allowing for a 2.0 OpenAPI support
- [wontfix, breaks api] RouteFunction will have a Context parameter (as the last?)
- Replace public vars by functions
- [done] Use CurlyRouter by default
- [done] No caching of request content by default
- [benchmark first] Introduce a static container in addition to the current one that allows add/remove WebServices
- [wonfix, breaks api] Remove request attributes in favor of Context

**Comment by emicklei** [comment]
currently the repository or organized like this

- go-restful/swagger
- go-restful/log

The nested swagger pkg contains 3 chunks: swagger data models, Go to swagger data (modelBuilder) and restful to swagger operations.

One re-organization I am thinking of could be
- go-restful  ( REST stuff only )
- swagger12 ( everything currently in go-restful/swagger )
- swagger2   ( same but for swagger 2.0 )

This would mean that the new swagger2 will contain more than just swagger2 model. So perhaps we should have

- go-restful-swagger12 ( everything currently in go-restful/swagger )
- go-restful-swagger2   ( same but for swagger 2.0 )

For the last package, a decision is needed whether to define own models or use go-openapi.

**Comment by emicklei** [comment]
created https://github.com/emicklei/go-restful-swagger20

**Comment by emicklei** [comment]
go-restful/swagger has been deleted
