### ISSUE TITLE
Accepting URLs including Query Parameters

### ISSUE THREAD

**Issue by nikolasborrel** [emicklei/go-restful#308]
I'm in a situation where my web service has to accept urls with query parameters like

http://example.com/oath2callback?state=the_state&code=the_code

but I can't find any documentation for this type of URL. I have used the following approach using the CurlyRouter with no luck (404 returned):

ws := new(restful.WebService)
ws.Path("/oauth2callback")
ws.Route(ws.GET("{*}").To(MyHandle))

How should the route be defined in this case?

**Comment by nikolasborrel** [comment]
I noticed that is has been fixed in the forked SavantSystem branch: https://github.com/SavantSystems/go-restful/commit/fdb78e128bb600f4a6d030fe71ebafaea7531307

Would it be possible to merge the fix into this branch?

**Comment by emicklei** [comment]
The routing is only based on the path and path parameters, query parameters are not taken into consideration. In your MyHandle function, you can access the values of each query parameter using request.QueryParameter("state").
I wonder what the SavantSystems fix actually does; I will have a look.

**Comment by nikolasborrel** [comment]
My problem is, that the path is not accepted and 404 is returned, this is also true for

ws.Route(ws.GET("").To(MyHandle))

However, the above route works in SavantSystems (because the url is split at '?') and I can get the parameters using request.QueryParameter("state") as you propose.

**Comment by emicklei** [comment]
So if your path does not include the `?` then it works.  Currently the routers do not match the query part of the URL. So perhaps a change is needed to split on ?

**Comment by nikolasborrel** [comment]
How is it going with the fix? At the moment I'm using the before mentioned branch, but that means that I don't have the newest version running...

**Comment by emicklei** [comment]
i kind of forgot about this one.

looking at back at the original question, I do not think a change is needed. 
The example you provided should just work. Only the path part is used for the matching.
Try running the restful-user-resource.go example and call it using any query params.
