### ISSUE TITLE
Custom EntityAccessor not honoured for Accept: */* requests

### ISSUE THREAD

**Issue by jGleitz** [emicklei/go-restful#309]
If I register a custom `EntityAccessor` using 

     restful.RegisterEntityAccessor(mime, accessor)

I’d expect a request declaring `Accept: */*` to a route producing `mime` to be responded using `accessor`. However, this does not happen. A `406` error is sent instead and the message 

    no registered EntityReaderWriter found for */*

is logged.

I wrote a [small example](https://gist.github.com/jGleitz/c0de485d543bccba7c9842dbfee9425f). If I execute it, I get the following responses:

```
$ curl -v localhost:8080/test 
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 406 Not Acceptable
< Date: Thu, 28 Jul 2016 14:26:10 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
```

```
$ curl -v localhost:8080/test -H 'Accept: test/mime'
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: test/mime
> 
< HTTP/1.1 200 OK
< Date: Thu, 28 Jul 2016 14:27:12 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
< 
This is the test
* Connection #0 to host localhost left intact
```

As you can see, the code works as expected if the request declares `Accept: test/mime` but not if it declares `Accept: */*`. This is unexpected. 

[The block starting at L79 in `response.go`](https://github.com/emicklei/go-restful/blob/master/response.go#L79) suggests that this behaviour is in fact not intended. If it is, please explain why!

**Comment by emicklei** [comment]
your example does specify what the route produces. Perhaps that loop in response.go also need to check for `*/*`.  When I get back from holidays, I will investigate further.

**Comment by emicklei** [comment]
i ran your sample program with different curl commands:

```
$ curl http://localhost:7070/test
This is the test

$ curl http://localhost:7070/test -H "Accept:*/*"
This is the test

$ curl http://localhost:7070/test -H "Accept:test/mime"
This is the test

$ curl http://localhost:7070/test -H "Accept:something/else"
406: Not Acceptable
```

(don't mind the port change)

**Comment by jGleitz** [comment]
I was checking against the latest stable version (v1.2).

I can confirm that everything works as expected on `master`. This bug only occurs on `tags/v1.2` (and probably before that).

Hoping for a new version release soon.

**Comment by emicklei** [comment]
Probably a good idea to create a new release I guess. Thank you for getting back on this.
