### ISSUE TITLE
No response entities or insupported media type

### ISSUE THREAD

**Issue by Fantasim** [emicklei/go-restful#313]
Hello,

When i would like to send a file to my server,

with this routes : 

```
    ws := new(restful.WebService)
    ws.Path("/message").
    Doc("Manage message").
    Consumes(restful.MIME_JSON).
    Produces(restful.MIME_JSON)

    ws.Route(ws.POST("/talk/{talk-id}").
    Consumes("multipart/form-data").
    Produces("multipart/form-data").
    Param(ws.HeaderParameter("token", "session's token").DataType("string").Required(true)).
    Param(ws.PathParameter("talk-id", "talk's id").DataType("int").Required(true)).
    Param(ws.FormParameter("content", "Message content").DataType("string").Required(true)).
    Param(ws.FormParameter("image", "Message image").DataType("file")).
    Filter(message.user.CheckAndGetUserBySessionToken).
    Filter(message.talk.CheckAndGetTalkById).
    Filter(message.checkIfUserIsInTalk).
    Filter(message.checkBodyCreate).
    To(message.createMessage).
    Returns(201, "Success", Message{}).
    Doc("Create a message").
    Operation("createMessage"))
```

i got a 406 error without content, or insupported media type.

But if i remove form parameters (image and content), i get content in json, and i remove this two lines : 
```
Consumes("multipart/form-data").
Produces("multipart/form-data").
```

it works perfectly, so can you tell me what's wrong?

**Comment by emicklei** [comment]
My initial thought is that specifying the Produces with this value is not correct. Only Consumes refers to the content type of the payload of the request.  Produces tells the router what content type it can respond with and that will be matched against the Accept header value of the request. I hink your handler will respond with JSON, not with multipar/form-data.

**Comment by Fantasim** [comment]
Hey, i've found solution : it was just

Add in route : 

`Consumes("application/x-www-form-urlencoded", "multipart/form-data").`

Instead

```
Consumes("multipart/form-data").
Produces("multipart/form-data").
```

**Comment by emicklei** [comment]
can this be closed?

**Comment by Fantasim** [comment]
yes
