### ISSUE TITLE
Extender response message examples

### ISSUE THREAD

**Issue by JoakimSoderberg** [emicklei/go-restful#314]
(I am new to go, so maybe this isn't possible).

But, I was thinking about the Swagger output for response messages.

Would it be possible to make it so that one can provide "example values" for the repsonse messages. Instead of simply showing `"string"` or `0` for example, the values passed to the struct one is returning will be a part of the example.

# How it works now

So for example, instead of having this:

```go
 ws.Route(ws.GET("/").To(ev.listEvents).
        Doc("Get all events").
        Returns(http.StatusOK, http.StatusText(http.StatusOK), []CatEvent{}).
        Returns(http.StatusInternalServerError,
                http.StatusText(http.StatusInternalServerError),
                CatError{}))
```

Which produces this Swagger output:

![2016-08-21 22_59_50-swagger ui](https://cloud.githubusercontent.com/assets/1446626/17839783/1078a868-67f3-11e6-9603-fdcd20a6f46c.png)

# How I wish it to work

Instea we would have this. With some example values that are then present in the Swagger output

```go
 ws.Route(ws.GET("/").To(ev.listEvents).
        Doc("Get all events").
        Returns(http.StatusOK, http.StatusText(http.StatusOK), []MyEvent{}).
        Returns(http.StatusInternalServerError,
                http.StatusText(http.StatusInternalServerError),
                CatError{HttpStatusCode: http.StatusInternalServerError, HttpStatus: http.StatusText(http.StatusInternalServerError)}))
```

Which produces this:
![2016-08-21 23_01_35-swagger ui](https://cloud.githubusercontent.com/assets/1446626/17839789/56e392fe-67f3-11e6-9d95-abf1733c78a9.png)

**Comment by JoakimSoderberg** [comment]
I guess this is in the code where the change would be made:

https://github.com/emicklei/go-restful/blob/c4afa8e5421428d584b32d36d7b35f2c9ae5f823/swagger/swagger_webservice.go#L290-L300

But as I said, I am new to golang so not sure yet how to solve it, if it even is possible.

**Comment by emicklei** [comment]
The swagger JSON (v1) produced by the handler can only contain type information for the models. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#527-model-object
It is the swagger UI in Javascript that creates the sample for a model.

**Comment by JoakimSoderberg** [comment]
oh ok, thank you for the clarification :) and thanks for a nice lib
