### ISSUE TITLE
Best way of doing nested resources?

### ISSUE THREAD

**Issue by JoakimSoderberg** [emicklei/go-restful#320]
I'm trying to figure out the best way to create a nested resource?

So that this would be possible:

`/container/{id}/the-resource/{sub-id}`

But then also there could be a global version of the same resource:

`/the-resource/{sub-id}`

And of course these two should share the same code. But I am unsure how I am supposed to do something like this in go-restful? Is it even possible?

Do I have to use one `restful.Webservice` and list all possible routes there explicitly? Something like:

``` go
ws := new(restful.WebService)
ws.Path("/")

// Becomes quite a lot of repeating....
ws.Route(ws.GET("/the-resource/{sub-id}")...
ws.Route(ws.POST("/the-resource/")...
ws.Route(ws.GET("/container/{id}/the-resource/{sub-id}")...
ws.Route(ws.POST("/container/{id}/the-resource/")...
```

Instead I would like to do something like creating a `WebService` for `the-resource`:

``` go
theResourceWS := new(restful.WebService)
theResourceWS.Path("/the-resource")

theResourceWS.Route(ws.GET("/")...               // List
theResourceWS.Route(ws.GET("/{sub-id}")...  // Get
theResourceWS.Route(ws.POST("/")...  // Get
```

And then simply "attach" this to both the root path, and as a sub-resource

``` go
ws.NestedRoute("/", theResourceWS)
ws.NestedRoute("/container/{id}/", theResourceWS)
```

Is this something that is possible already? The examples are all for at the most one resource, and never nested or anything more complex.

**Comment by JoakimSoderberg** [comment]
@emicklei Is this something that is possible with todays API? Or maybe a use case to have in mind for v2? What is your opinion?

**Comment by emicklei** [comment]
@JoakimSoderberg that is certainly not possible with the current implementation although the JSR311 spec, which I used as a basis, does have support for it. 
Maybe we could have a parent-child relationship between WebServices. 
It will definitely make this package more complicated but we could try to prototype it.

**Comment by emicklei** [comment]
I wonder if we could implement NestedRoute(..) by re-registration of the nested resource using a different path.

**Comment by emicklei** [comment]
feel free to reopen if you want to propose an implementation.
