### ISSUE TITLE
JSON POST requests don't seem to be getting all the fields

### ISSUE THREAD

**Issue by vichargrave** [emicklei/go-restful#322]
When I try to send JSON parameters to the PUT service in restful-curly-router.go web service - ws.Route(ws.PUT("/{user-id}").To(u.createUser)) - only the User.Id is returned.  The User.Name field is an empty string.  Here is the request I'm sending:
    
```
curl http://localhost:8080/users/003 -X PUT -H "Content-Type: application/json" -d '
{
    "User": {
        "Id": "003",
        "Name": "vic"
    }
}'
```

The response sent back is:

```
{
     "Id": "003",
     "Name": ""
}
```

I put a fmt.Println statement in the code which prints out the request parameters:

```
{0xc8200f4a80 <nil> map[user-id:003] map[] /users/{user-id}}
```

It seems that the User.Name parameter is not coming across.  When I do this example with XML, it works fine.  Is this a bug or am I doing something wrong?

**Comment by emicklei** [comment]
I have been able to reproduce the problem. Now investigating...

**Comment by emicklei** [comment]
Your are posting the wrong JSON document.  Compared to XML, JSON does not expect a "root node" , here "User". Instead use

```
{
        "Id": "003",
        "Name": "vic"
}
```

**Comment by vichargrave** [comment]
OK fair enough.  I figure I was doing something wrong.  Thanks.
