### ISSUE TITLE
swagger doesn't work in production

### ISSUE THREAD

**Issue by Fantasim** [emicklei/go-restful#323]
i'm deploying my api, and i would i like to deploy swagger (with auth).

It works perfectly in localhost but when i would like route it on my server it doesn't work 

so this is my swagger config

```
    config := swagger.Config{
        WebServices:    restful.RegisteredWebServices(), 

// you control what services are visible
        WebServicesUrl: "http://46.105.240.244:9000",
        ApiPath:        "/apidocs.json",

        // Optionally, specifiy where the UI is located
        SwaggerPath:     "/apidocs/",
        SwaggerFilePath: "/root/go/src/SpottedRethink/swagger-ui/dist"}

```

and these lines in swagger-ui/dist/index.html are update like that : 

> ```
>   var url = window.location.search.match(/url=([^&]+)/);
>   if (url && url.length > 1) {
>     url = decodeURIComponent(url[1]);
>   } else {
>     url = "http://46.105.240.244:9000/apidocs.json";
>   }
> ```

Could you tell me what is wrong ?

**Comment by emicklei** [comment]
in one of our apps we changed the url defintion to
```
var url = window.location + "../apidocs.json"; 
```

**Comment by Fantasim** [comment]
in which file ?

**Comment by Fantasim** [comment]
I think error come from my swagger config (in my go file) because : 

> http://46.105.240.244:9000/apidocs/
return 
`curl: (7) Failed to connect to 46.105.240.244 port 9000: connection refused`

**Comment by emicklei** [comment]
connection refused indicates that there is no tcp listener on that port.
Maybe this is a firewall issue or when using Docker a port mapping?

**Comment by Fantasim** [comment]
No, i don't use Docker and there is no firewall :/

**Comment by emicklei** [comment]
i strongly believe the problem is related to your configuration or infrastructure.
this package has been been used in production for many years, therefore I do not think it is Go related.
