### ISSUE TITLE
DefaultRequestContentType does nothing

### ISSUE THREAD

**Issue by alfred-landrum** [emicklei/go-restful#324]
DefaultRequestContentType sets the defaultRequestContentType variable, but that is not used when selecting the entity reader. Hence, requests with no "Content-Type" header can only be decoded by manually updating the request headers before processing.

**Comment by emicklei** [comment]
thank you for reporting this. I wil check the code

**Comment by emicklei** [comment]
by inspecting the code path, I see the problem in the reques.go:112 .  Fixing it now...

**Comment by emicklei** [comment]
please verify the merge change so we can close this
