### ISSUE TITLE
Swagger and problem with Array

### ISSUE THREAD

**Issue by OmidHekayati** [emicklei/go-restful#327]
I have been tested in any way, but I always get same error for array in API request same as below picture. Can anyone explain why or how to fix it?

![photo_2017-01-28_15-24-43](https://cloud.githubusercontent.com/assets/21355363/22396509/800519e6-e570-11e6-8c6a-1fd1cf618fb9.jpg)

**Comment by emicklei** [comment]
thank you for reporting this.  

i could reproduce the problem and will see how to fix it.

**Comment by emicklei** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/449 seems related

**Comment by emicklei** [comment]
made small modification but UI does not seem to handle this.   More time needed...

```
        "type": "array",
          "items": {
            "$ref": "main.User"
          },
```

**Comment by OmidHekayati** [comment]
Thanks.
It was best idea to separate swagger, because I believe "Separate Concern, Separate Package" like microservice architecture.
We'd be glad to help improve this helpful go-restful library to v2.
