### ISSUE TITLE
google_app_engine examples broken

### ISSUE THREAD

**Issue by muesli** [emicklei/go-restful#330]
It needs to import go-restful-swagger12 and the upstream appstats API has changed (NewContext is now unexported newContext). I can fix the former, but I have no idea how to solve the latter.

**Comment by emicklei** [comment]
thank you for reporting this.

**Comment by muesli** [comment]
Note: This actually breaks Travis builds (at least with its default setting of building everything recursively) for projects that vendor go-restful.

**Comment by emicklei** [comment]
yes, unfortunately, the examples folder in included in the vendor directory. I wonder if this being taken care in future dep like tooling

**Comment by emicklei** [comment]
for a while, i have been using the official "dep" tool for vendoring which has a prune feature. With that, all unused packages are removed from the vendor folder.
