### ISSUE TITLE
JWT auth question

### ISSUE THREAD

**Issue by basilex** [emicklei/go-restful#331]
Hello,

is it possible to use jwt auth using github.com/dgrijalva/jwt-go library?
If so, could you please help me to implement such middleware for go-restful library?
Moreover it's will be very helpful to avoid instantiation some kind of jwt backend during each request...

Thanx a lot!

**Comment by emicklei** [comment]
Yes that is certainly possible. As a matter of face, we are using this in two of our major projects at bol.com.
I propose to add an example which demonstrates how to implement a filter for authentication.

**Comment by knabben** [comment]
An example of JWT HMAC authentication with filter in https://github.com/emicklei/go-restful/pull/407
