### ISSUE TITLE
Path parameter not detected if suffixed by file extension

### ISSUE THREAD

**Issue by vwochnik** [emicklei/go-restful#332]
We have a scenario where we want to dynamically generate a JavaScript file using templates.

Here is the service definition and the `get` method which is not working because `configId` is empty.

```
func Register(container *restful.Container) {
	ws := new(restful.WebService)
	ws.Path("/{siteId}/script").Produces(MIME_JS)

	ws.Route(ws.GET("/{configId}.js").To(get))

	container.Add(ws)
}

func get(req *restful.Request, resp *restful.Response) {
	siteId := req.PathParameter("siteId")
	configId := req.PathParameter("configId")
	fmt.Printf("SiteId: %s, ConfigId: %s\n", siteId, configId)
        // ConfigId is empty although specified in URL and this function is called.
        // ...
}
```

Currently, we are fixing the problem by having `/{configId}/script.js` but having `/{configId}.js` would be good.

**Comment by emicklei** [comment]
Another workaround is to use  ```/{configId:*}``` then ```configId``` will have the value ```yourscript.js```  when called with  ```/yoursite/yourscript.js```

**Comment by emicklei** [comment]
or simply ```/{configId}```
