### ISSUE TITLE
Getting `nil` value from body parameter consuming JSON

### ISSUE THREAD

**Issue by Chaseshak** [emicklei/go-restful#333]
In my request handler for a `POST` request, I have a line of code getting the body parameter `uid` and printing it to the console: `fmt.Println(request.BodyParameter("uid"))`.

The request I make looks like this:
![image](https://cloud.githubusercontent.com/assets/13201458/24666979/63f5a5d2-1927-11e7-9b2a-6c00ad6bc672.png)

This gets me a response (as I've hard-coded the rest of the code), but to the console prints `<nil>`  instead of the `uid` that is passed in the body of the request as JSON.

```
{
    "uid" : 20
}
```

Am I missing something here?

**Comment by Chaseshak** [comment]
```
func New() *restful.WebService {
	service := new(restful.WebService)
	service.
		Path("/reward").
		Consumes(restful.MIME_JSON).
		Produces(restful.MIME_JSON)

	// The below are some more RESTful examples.
	// They are commented out since the functions are dummy ones
	service.Route(service.POST("/{reward-id}").To(purchaseReward))

	return service
}
```


This is the `New()` function for that API End-Point. I have set it to consume and produce JSON.

**Comment by emicklei** [comment]
The body (content) of your request must be consumed using unmarshalling a struct that has the uid field. For example

```
type Reward struct {
  UID int `json:"uid"`
}
```

and
```
r := new(Reward)
request.ReadEntity(r)
```

Have a look at the example  UserResource from the examples folder.

**Comment by Chaseshak** [comment]
Ahh this makes sense. Thank you!
