### ISSUE TITLE
run example error

### ISSUE THREAD

**Issue by timchenxiaoyu** [emicklei/go-restful#335]
run  restful-user-resource.go

# command-line-arguments
gorest/rest.go:141: cannot use wsContainer.RegisteredWebServices() (type []*"workspace/vendor/github.com/emicklei/go-restful".WebService) as type []*"github.com/emicklei/go-restful".WebService in field value
gorest/rest.go:148: cannot use wsContainer (type *"workspace/vendor/github.com/emicklei/go-restful".Container) as type *"github.com/emicklei/go-restful".Container in argument to swagger.RegisterSwaggerService

**Comment by emicklei** [comment]
hi,

i cannot reproduce this problem.
Looks like you are running this example from a vendored version. May you should update this first.

**Comment by timchenxiaoyu** [comment]
yes,you are right,after update project ,err is disapper
