### ISSUE TITLE
Args to To() and Filter()?

### ISSUE THREAD

**Issue by ZedCode** [emicklei/go-restful#340]
Is there a way to add additional arguments to functions registered by `.To()` or `.Filter()`? The reason for asking is that I would like to create a new `restful.WebService` at the same time I create a database connection. I'd then like to pass `*sql.DB` into the functions registered to `.To()` when required.

Something along the lines of:
```golang
func (m myTestAPI) New(container *restful.Container) {
	db, _ := sql.Open("mysql",
		"root@tcp(localhost:3306)/apps")
	service := new(restful.WebService)
	service.
		Path("/testapi").
		Consumes(restful.MIME_JSON).
		Produces(restful.MIME_JSON)
	service.Route(service.GET("/test/{t}").To(funcTest(db))

	container.Add(service)

}
```
(Obviously with better error handling :) )

**Comment by ZedCode** [comment]
Ah, I think I found a better way to do this that seems more idiomatic with the library. Put this sort of persistent information into the struct I'm using as a method receiver for all of my `restful.Container`. That makes sense to me and I'll open a new issue if I can't figure out the way that should be done.

**Comment by emicklei** [comment]
Sorry about the late response. Yes, I think your solution is better and is exactly the way we use it.
