### ISSUE TITLE
Incorrect call to Container.addHandler in Container.Remove

### ISSUE THREAD

**Issue by enj** [emicklei/go-restful#344]
`Container.addHandler` assumes that the old `Container.webServices` is valid during `Container.Remove`.  This makes it incorrectly assume that paths are `alreadyMapped` (which they are for the old `webServices` but not the new `webServices` that is being built to replace it).  This results in a new `serveMux` that has no handlers registered.

xref https://github.com/emicklei/go-restful/commit/0e9e201e5de4f54c61e6d09aef44c4cfde43ede6#commitcomment-22285239 openshift/origin/issues/14969

**Comment by emicklei** [comment]
thank you for reporting this. I will have a look at this

**Comment by emicklei** [comment]
do you have suggestions how to fix this?
