### ISSUE TITLE
Cache API Responses

### ISSUE THREAD

**Issue by anshul35** [emicklei/go-restful#348]
I am looking for a neat way to cache some of the API responses, and implement it as a filter. Since the restful.Response object does not have http.Response, is there some way I can still do it?

**Comment by emicklei** [comment]
sorry about the late response. seems that I no longer get notifications :-(

you can access the underlying http.ResponseWriter from restful.Response , it is just a decorator (wrapper).  

```writer := restfulResponse.ResponseWriter```
