### ISSUE TITLE
Tag versions to be compatible with gopkg.in

### ISSUE THREAD

**Issue by Graham42** [emicklei/go-restful#350]
In order to be compatible with gopkg.in (http://labix.org/gopkg.in) tags need to begin with a `v` example: `v2.2.0`

This is a request to either change the way tags are named, or provided both the current format and the `v` format.

Thanks!

**Comment by emicklei** [comment]
thank you for mentioning this. I will make sure new tags use this format.

**Comment by Graham42** [comment]
I'm considering this fixed since there's now a tag named `v2.2.1`. Thanks!
