### ISSUE TITLE
Response does not implement http.Hijacker

### ISSUE THREAD

**Issue by johnweldon** [emicklei/go-restful#354]
The go-restful `Response` type does not implement `http.Hijacker`, and the underlying `http.ResponseWriter` loses the potential `http.Hijacker` implementation when it gets stored as an embedded interface, making it impossible to use a type assertion on the `Response` to get a `Hijacker`, even if the underlying `ResponseWriter` actually does implement `Hijacker`.

**Comment by johnweldon** [comment]
Incidentally related to #338 

This feature is needed to allow the gorilla websocket implementation to work with go-restful.

**Comment by emicklei** [comment]
thank you for contributing
