### ISSUE TITLE
Just a question about a design change

### ISSUE THREAD

**Issue by schleppy** [emicklei/go-restful#359]
I have been using go-restful for a few years now, and unfortunately we are still running a very old version.  With the latest project I am doing I have updated the version to HEAD and everything seemed just fine.  But I have found one change in particular has caused some issues and I am trying to figure out the best way forward for my team.

The change was to both `request.SetHeader` and in the `WriteAs` methods.  `SetHeader` used to just set a value on the `Response` without actually setting the header on the underlying `ResponseWriter` (unless the status code in the Response was already set to 204).  Then the `ResponseWriter.SetHeader` call was made just prior to writing the content of the response.

This worked out really well for making APIs with consistent response types, where the top level of the response was an envelope for the contained resources.  As an example it might look something like this

```
{
    "errors": [
        {
            "code": 400,
            "message": "Foo is a required field"
        },
        {
            "code": 400,
            "message": "Bar must be an integer between 1 and 100"
        }
    ],
    "resources": [
        <some resources>
    ]
}
```

A common approach in our http handlers would go something like

```
func foo(request *restful.Request, response *restful.Response) {
    var resources []Resource
    var errors []ApiError
    defer func() {
        response.WriteAsJson(Envelope{Errors: errors, Resources: resources})
    }()
    // do stuff that makes errors, or makes resources
}
```

And we have a library of Validators for various expected inputs, and when these validators fail they call `response.SetHeader`.  

So there are two problems, now when `SetHeader` is called it calls `ResponseWriter.SetHeader` immediately (before the Content-Type header has been set), and when `WriteAsJson` is called, it sets the response code again (causing a logged error - not the end of the world) but the Content-Type can no longer be set.

I am wondering if there is an already known solution to handle this with the changed design and why it was changed in the first place (not saying it is wrong, just wondering the motivation).

Sorry for the long *issue* here, and thanks for your work on this library,

**Comment by emicklei** [comment]
hi,

thank you for using this package and providing this feedback.
This change has been done quite a while ago and one of the result was that methods such as WriteHeaderAndEntity were added to the Response.
I recall that is was related to whether or not a valid entitywriter could be found ; in that case a 406 had to be written.

**Comment by emicklei** [comment]
does my answer your question? can i close this?

**Comment by schleppy** [comment]
Yes, please do so.  We have updated our code to work around this issue.
