### ISSUE TITLE
Add optional description to body parameters

### ISSUE THREAD

**Issue by jumisz** [emicklei/go-restful#360]
At the moment the only way to support structured data types in body parameters, is to use `Routebuilder.Reads(sample interface{})` function. But this function doesn't add any description for the parameter to the swagger docs. This is not the case when using `WebService.BodyParameter`, which provides further flexibility. However `BodyParameter` does not support structured data types in the current implementation. 

Can I suggest adding an optional description argument to `RouteBuilder.Reads()` that adds the description to the parameter?

**Comment by emicklei** [comment]
you mean something like
```
Read(sample interface{}, optionalDescription ...string) { 
     // accept zero or one description
}
```

**Comment by jumisz** [comment]
yes, something like that

**Comment by emicklei** [comment]
pr has merged
