### ISSUE TITLE
PathParameters inconsistent with jsr311 router when route has greedy parameter

### ISSUE THREAD

**Issue by iainduncani** [emicklei/go-restful#363]
In the situation where there are two routes:

```
/resource/{name:*}
/resource/{name:*}/child
```

If using the jsr311 router to get `/resource/wibble/fish/child` the jsr311 router correctly picks the second route as the handler, however the name path parameter is set to `wibble/fish/child`.

This is because the route handler for the path parameter does the same thing whether the curly or jsr311 router is being used:

https://github.com/emicklei/go-restful/blob/master/route.go#L141

I think the solution would be to make the route.go accept the parameter processing function when it is created and the existing code moved into curly.go.  jsr311.go could then provide an alternative behaviour that is consistent with it's routing policy.

**Comment by emicklei** [comment]
thank you for sharing this. Would you care to work on such proposal together?

**Comment by iainduncani** [comment]
Yes, I'm happy to put something together, mostly wanted to use the issue to see if this is something you would consider merging if I looked at the implementation!

**Comment by iainduncani** [comment]
I've done a bit more digging and I don't think this will be too hard to get out of the JSR311 route as the way the regexp is built up means we have all the information in the thing returned from the regexp matcher on this line:

https://github.com/emicklei/go-restful/blob/master/jsr311.go#L127

One thing I'm not sure about though is where to put this information to not end up processing the regex again.  It looks like the route objects that are created are created when they are defined so there isn't one-per request that is built up by the jsr311router like I had hoped.  I guess it's not the end of the world to re-process the regex but it seems like it would be nicer to just set the path params onto the route when we do this selecting.

**Comment by iainduncani** [comment]
Hi @emicklei I've just raised a PR for this, let me know if you are happy with the changes!

**Comment by iainduncani** [comment]
Hi @emicklei I've added a new fix that doesn't change any of the existing interfaces so hopefully it is more appropriate

**Comment by emicklei** [comment]
can we close this?

**Comment by iainduncani** [comment]
Yes! Thanks for you help merging the fix.
