### ISSUE TITLE
route can ignore case ？？？

### ISSUE THREAD

**Issue by rentiansheng** [emicklei/go-restful#364]
route can ignore case ？？？

 / api, / Api, / API said the same one

**Comment by emicklei** [comment]
no it cannot with the current router implementations.
You could write your own implementation, copying and modifying the CurlyRouter for instance.

**Comment by rentiansheng** [comment]
okey, thanks.

**Comment by iainduncani** [comment]
You could achieve it using the curly routers regex matching by doing:

```
Path("{api:(?i)api}")
```
