### ISSUE TITLE
swagger api generate break

### ISSUE THREAD

**Issue by oilbeater** [emicklei/go-restful#367]
I tried the swagger example in https://github.com/emicklei/go-restful/blob/master/examples/restful-swagger.go
When access 127.0.0.1:8080/apidocs.json only part of the api specification shows up like below

`{
  "swaggerVersion": "1.2",
  "apis": [
   {
    "path": "/books",
    "description": ""
   }
  ],
  "apiVersion": "",
  "info": {
   "title": "",
   "description": ""
  }
 }`

I use the master code from go-restful and go-restful-swagger12, not sure if it is the version problem or something wrong with the swagger generation.

**Comment by emicklei** [comment]
This is correct. Version 1.2 of Swagger uses multiple documents (by path) for the API (compared to a single doc for OpenAPI).  Follow ```http://localhost:8080/apidocs.json/books```  to see the docs for the books service.

**Comment by emicklei** [comment]
I added another example that uses the more recent package go-restful-openapi.

**Comment by oilbeater** [comment]
Thanks, that's very useful
