### ISSUE TITLE
how can i get the http server crash error in the http client side?

### ISSUE THREAD

**Issue by breezelxp** [emicklei/go-restful#368]
Hi, 
First of all, thanks go-restful.

Here is my problem:

I used go-restful to implement a http  watch api in server and client side. The server write data to the client side with a long connection continuously, and the client receive these datas and decode it.

But i found that, the client can not get an error when the server side is crashed(actually, i stop it manualy) after the connection have already established. 

***How can i get this error?***

Here is my client side code:
```golang
func (c Client) WatchJobs(slave *util.Slave, jobChan chan *util.Job, errChan chan error) error {
	js, err := json.Marshal(slave)
	if err != nil {
		return err
	}
	url := fmt.Sprintf("%s%s", c.master.GetServers(), watch_job_url)
	req, err := http.NewRequest("PUT", url, bytes.NewReader(js))
	if err != nil {
		return err
	}
	
	resp, err := c.cli.Do(req)
	if err != nil {
		return err
	}

	
	go func() {
		defer resp.Body.Close()
		decoder := json.NewDecoder(resp.Body)
		for {
			r := new(util.SvrResponse)
			if err := decoder.Decode(r); err == io.EOF || err != nil {
				errChan <- err
				return
			}

			if r.Error != nil {
				continue
			}

			for _, j := range r.Jobs {
				jobChan <- j
			}
		}
	}()
	return nil
}
```

I have tried to use request.Context().Done() to get this error, but i found it does work.

Any suggestion is grateful. Thanks.

**Comment by emicklei** [comment]
can this be closed?

**Comment by breezelxp** [comment]
> can this be closed?

yes, thanks
