### ISSUE TITLE
Support json.DisallowUnknownFields or another method to deny unknown body fields

### ISSUE THREAD

**Issue by objque** [emicklei/go-restful#369]
go 1.10 introduces feature to deny all bodies with unknown fields.
to add this feature in go-restful need to insert call of this method on [entity_accessors.go:133](https://github.com/emicklei/go-restful/blob/master/entity_accessors.go)

but if we wanna support this feature, then we should drop support all users with go < 1.10

Is go-restful already implements ways to deny unknown fields? _(unknown fields - fields that aren't announced in structure tags)_

cc @emicklei 
godoc [Decoder.DisallowUnknownFields](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields)

**Comment by emicklei** [comment]
hi,

thank you for reporting this.

I will have a closer look into this, but my first idea is to create an interface "HasMethodDisallowUnknownFields" with the function DisallowUnknownFields and then test the decoder if it implements that helper interface such that it can be called without compile|runtime error.

**Comment by emicklei** [comment]
hi, i think the PR is usable to have this feature. It allows injection of your own function to create a json Decoder. let me know if this works for you

**Comment by objque** [comment]
Thanks for your rapid solution! 
if I understand correctly, then all users with go10 will receive errors when there are unknown fields in a body. Maybe will correctly to make the ability to turn off the check of unknown fields to support backward compatibility with users that migrate from earlier versions of go? 
This is exactly what the core go team did. By default DisallowUnknownFields function is disabled.

**Comment by emicklei** [comment]
so it is the second commit you should look at.  could not make the first one to work actually.

**Comment by objque** [comment]
If I understand correctly now **JSONNewDecoderFunc** it's a public variable that might be overloaded with a custom serializer.

If it is, then everything fine. 👍  
Also would be better to update/add some information into the docs to avoid future questions about this feature!

**Comment by objque** [comment]
Think we have done with this. Thanks, @emicklei :)

**Comment by objque** [comment]
Hello again
This PR https://github.com/emicklei/go-restful/pull/379 broke custom unmarshals :(

@emicklei

**Comment by emicklei** [comment]
@objque can you provide an example (test) that shows the problem?

**Comment by objque** [comment]
actual code doesn't contain JSONNewDecoderFunc object, that was introduced in this PR
