### ISSUE TITLE
Support urlencode params in request.PathParameter()

### ISSUE THREAD

**Issue by hewen1125** [emicklei/go-restful#370]
**Example**
`ws := new(restful.WebService)`
`ws.Route(ws.Get("/url/{url}").To(u.url))`

I visite **/url/http%3A%2F%2Ftest.com%2Ftest** but return **404 page not found**
I found that **httpRequest.URL.Path** would auto decode the request url, so the url go-restful get was **/url/http://test.com/test**  and could not match **/url/{url}**

So I changed to use QueryParameter.
Will this feature be supported?

**Comment by emicklei** [comment]
i recall this issue and AFAIK it could be solved that easy. I will have a second look at this problem

**Comment by emicklei** [comment]
https://github.com/emicklei/go-restful/issues/249

**Comment by emicklei** [comment]
```
package main

import (
	"io"
	"net/http"
	"fmt"
	. "github.com/emicklei/go-restful"
)

// GET http://localhost:8080/slashy/Go/lang

func main() {
	DefaultContainer.Router(CurlyRouter{})
	ws := new(WebService)
	ws.Route(ws.GET("/slashy/{slash:*}").To(slash))
	Add(ws)
	http.ListenAndServe(":8080", nil)
}

func slash(req *Request, resp *Response) {
	fmt.Println("%#v", req.Request)
	io.WriteString(resp, "slash="+req.PathParameter("slash"))
}
```

**Comment by hewen1125** [comment]
Got it, thanks.

**Comment by NigelZHANG** [comment]
When i use this way to route, it also return 404 error, how to deal with this path:

route path is: /slashy/{var:*}/moreslashy/{otherVar}
url path is: /slashy/go/lang/moreslashy/test

expect result params:
var: go/lang
otherVar: test

**Comment by emicklei** [comment]
Hi @NigelZHANG , I guess the CurlyRouter is greedy and will return `go/lang/moreslashy/test` for your var.

Now the question is whether the CurlyRouter can be changed to allow this, without breaking its existing behavior.

**Comment by NigelZHANG** [comment]
Thank you for reply.
I found the way to resolve it, use the `RouterJSR311` to parse params.
Hope it can be helpful to others.
