### ISSUE TITLE
How to log all request body in my log?

### ISSUE THREAD

**Issue by tubzby** [emicklei/go-restful#372]
I want to record all my request, seems restful.WebService.Filter() function is common way to archive this.

check out function "formatRequestLog"  on links below
https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/filter.go

```
// formatRequestLog formats request log string.
func formatRequestLog(request *restful.Request) string {
	uri := ""
	if request.Request.URL != nil {
		uri = request.Request.URL.RequestURI()
	}

	content := "{}"
	entity := make(map[string]interface{})
	request.ReadEntity(&entity)
	if len(entity) > 0 {
		bytes, err := json.MarshalIndent(entity, "", "  ")
		if err == nil {
			content = string(bytes)
		}
	}

	return fmt.Sprintf(RequestLogString, time.Now().Format(time.RFC3339), request.Request.Proto,
		request.Request.Method, uri, request.Request.RemoteAddr, content)
}
```

here it use request.ReadEntity to read the post body, since http.Request.Body is io.Reader it will cause an EOF error in this function 

https://github.com/kubernetes/dashboard/blob/master/src/app/backend/auth/handler.go
```
func (self AuthHandler) handleLogin(request *restful.Request, response *restful.Response) {
	loginSpec := new(authApi.LoginSpec)
	if err := request.ReadEntity(loginSpec); err != nil {
		response.AddHeader("Content-Type", "text/plain")
		response.WriteErrorString(http.StatusInternalServerError, err.Error()+"\n")
		return
	}

	loginResponse, err := self.manager.Login(loginSpec)
	if err != nil {
		response.AddHeader("Content-Type", "text/plain")
		response.WriteErrorString(http.StatusInternalServerError, err.Error()+"\n")
		return
	}

	response.WriteHeaderAndEntity(http.StatusOK, loginResponse)
}
```

I can't understand why kubernetes/dashboard is working, because i setup an example and always get an EOF on the second call of  ReadEntity.

**Comment by emicklei** [comment]
Once you have read the body, it is closed and cannot be read again.
You could put back the content of the body by setting it after reading it.
This is also done by the forest package (see snippet below).

```
		body, err := ioutil.ReadAll(resp.Body)
		....
		resp.Body.Close()
		// put the body back for re-reads
		resp.Body = ioutil.NopCloser(bytes.NewReader(body))
```
You cannot use this code as is but I hope you understand the idea of the solution.

**Comment by tubzby** [comment]
thanks,but why kubernetes dashboard is working that way?

**Comment by emicklei** [comment]
i do not understand what you mean by "that way"

**Comment by emicklei** [comment]
can this be closed?
