### ISSUE TITLE
Unit testing best practice for backends built with go-restful

### ISSUE THREAD

**Issue by cdosoftei** [emicklei/go-restful#373]
Hello!

I am (unsuccessfully so far) trying to figure out the optimal way of unit testing handlers designed specifically for go-restful powered API backends.

The integration testing portion works excellent with emicklei/forest but I am unsure about unit testing per se.

Thank you!

**Comment by rajphoenix20** [comment]
moved to: https://github.com/emicklei/go-restful/blob/master/examples/tests/restful-routefunction_test.go
