### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by ulrichSchreiner** [emicklei/go-restful#374]
hi,

i know that vgo is not released. but it would be great to support it in the near future. with the current version of `vgo` you cannot import a version-2 of `go-restful`. the [design document](https://research.swtch.com/vgo-module) says:
>  Again, the go.mod file is required for v2 and later so that vgo can use the module line as a sign that the code has been written with semantic import versioning in mind, ...

to support multiple versions, the packages should have the version in their import path (`.../v2`).

so the author of `vgo` want the version 2 (or later versions) to have a `go.mod` file. this is not present in the current code. this leads to the following situation:
~~~
$ vgo list -t github.com/emicklei/go-restful   
github.com/emicklei/go-restful
        v1.0.0
        v1.0.1
        v1.1.0
        v1.1.1
        v1.1.2
        v1.1.3
~~~
Great!
~~~
$ vgo list -t github.com/emicklei/go-restful/v2
github.com/emicklei/go-restful/v2
        v2.2.1
        v2.3.0
        v2.4.0
        v2.5.0
        v2.6.0
        v2.6.1
        v2.7.0
~~~
Great!

But:
~~~
$ vgo get github.com/emicklei/go-restful/v2       
vgo: finding github.com/emicklei/go-restful/v2 v2.7.0
vgo: github.com/emicklei/go-restful/v2 v2.7.0: missing go.mod
vgo: finding github.com/emicklei/go-restful/v2 v2.7.0
vgo: github.com/emicklei/go-restful/v2 v2.7.0: missing go.mod
vgo get: missing go.mod
~~~
:-(
Here `vgo` complains about the missing `go.mod` file which indicates that the module does semantic versioning.

So adding a dependency with `vgo`:
~~~
$ vgo get github.com/emicklei/go-restful@v2.7.0 
$ vgo list -m
github.com/cznic/fileutil             v0.0.0-20180108211300-6a051e75936f
github.com/emicklei/go-restful        v0.0.0-20180416204930-2810ccc68e0c
github.com/go-stack/stack             v1.7.0
...
~~~
as you can see, `go-restful` is added as an unversioned dependency (0.0.0) with the current git-SHA (2810ccc68e0c). well, this works, but is is not the desired behaviour (at least for me).

It would be great to support `vgo` in the long run. at the moment i have no problem with the `0.0.0` dependency but it would be great to support `vgo` in some later versions.

**Comment by emicklei** [comment]
Thank you for sharing this. I definitely want to support vgo. I guess I have to add the mod file and adhere to the rules. I will find out what is needed and probably update all my projects in the process.

**Comment by emicklei** [comment]
so I started adding vgo support but ran into a challenge.
to make it work, the imports to the subpackage log needs to be rewritten to `github.com/emicklei/go-restful/v2/log`

This not only breaks my current Travis build (that can be fixed , see https://github.com/Celeo/Blog/blob/master/posts/2018/travis-codecov-vgo.md ) but it also would break build of users of this package that do not use vgo (yet).

So although, I added and tagged a go.mod file, it actually does not work yet. 
Maybe I need to move the vgo stuff to a v2 branch instead and let the master be old-style...

**Comment by ulrichSchreiner** [comment]
hi,

i'm not sure if it is a good idea to have the master "old style". most people think the master is *latest greatest*. on the other hand: you're right, changing the master to vgo-style will break other's people code/builds. 

vgo support will be great for the future, but i think you have time to make it correct. go 1.11 will have vgo as an experimental feature, 1.12 will have vgo. so nobody can blame you, if your library does not support it now.

an btw: i do not have a problem if your *master* breaks my build. in this case i have a dependency on your master and that can always happen that you change your code in a incompatible way. if i do not want this, i should pin my build to a tag or commit of your library.

**Comment by emicklei** [comment]
need to work on this soon

**Comment by tekkamanendless** [comment]
Given that there are already 2.x release published, I would recommend that the switch to Go 1.11 modules (`go.mod`) be done for a v3 release.  The Go module documentation also recommends adding module support in a new major version, not midway through one.

This way, everyone can continue to use the 2.x series the same way that they always have, and we can update `master` to be `github.com/emicklei/go-restful/v3` and tag it `v3.0.0`.

**Comment by emicklei** [comment]
i think it is time to add the v3, agree?

**Comment by y0ssar1an** [comment]
Do eeeet 🙂 
Even if the only feature of v3 is Go module support, it's worth it.

**Comment by emicklei** [comment]
From https://blog.golang.org/v2-go-modules

.. do we have users developing in GOPATH mode ?

I.e are you ok with v3 being on master or should this package use a v3 subdirectory?

**Comment by tekkamanendless** [comment]
I have never worked on a project that took the subdirectory approach; everything that I've seen so far has just bumped the major version and added `go.mod` to the top-level directory.  If you take the sub-directory approach, then you'll have two code-bases to maintain in one branch for no particularly good reason.

Even if people still use GOPATH, it's pretty clear to me that the future of Go is modules because of (1) their ease of use, and (2) the consistency that they provide.  Anyone still using GOPATH will be quite familiar with their packages breaking all the time due to incompatible changes and incompatibilities between the requirements of different packages that both include the same one, but at a different version (and they're likely used to working around the issue with `vendor` directories or multiple GOPATHs, etc.).  GOPATH is essentially unsustainable for anyone working on more than one project at a time, which is why we have modules in the first place.

My vote is for a major version bump with `go.mod` at the top.

**Comment by y0ssar1an** [comment]
>are you ok with v3 being on master or should this package use a v3 subdirectory?
Yeah, I definitely think v3 should be on `master`. I've seen repos that try to keep multiple copies of the same repo under `v2/`, `v3/`, etc. directories and it's really ugly. `go test ./...` runs the same test multiple times (for code that didn't change between versions). The repo size doubles. It's harder to `grep`.

Putting v3 on `master` won't break anybody who has pinned their version of `go-restful`. If they haven't done that, they can't complain about breakages.

**Comment by emicklei** [comment]
thank you all for commenting on this issue, I decided to put the v3 on the current master. 

Initially, I planned to process all the deprecated pieces in v3. This would however break existing code bases that do not use modules. So to prevent that from happening, those pieces will be removed in a later major version (v4), if ever.

**Comment by emicklei** [comment]
fyi, I am working on the getting the module support right.
I found a problem with the subpackage called log which is used in several files but not imported with the v3 in the path. This causes the go.mod to include a require on a v2 version.

To investigate and solve this problem, I created a temporary project https://github.com/emicklei/thingabee  to have a minimal setup that shows it.

**Comment by tekkamanendless** [comment]
That's because you _must_ change the import of every `emicklei/go-restful` reference to a `emicklei/go-restful/v3` reference in order to use `v3`.

Because you import `github.com/emicklei/thingabee/log`, it knows that it's not looking at `v3`, so it drops back to `v2`.  The proper import would be `github.com/emicklei/thingabee/v3/log`; doing that will make it happy.

**Comment by emicklei** [comment]
@tekkamanendless thank you for explaining this. I did some testing to see if there was another way that would not break GOPATH users of this package, i.e those that do not use Go modules.

**Comment by emicklei** [comment]
I am now exploring this approach https://posener.github.io/branch-strategy/  using  the github.com/emicklei/thingabee project. I get unexpected results though.

```
package main

import "github.com/emicklei/thingabee/v2"

func main() {
	thingabee.Ping()
}
```

```
module demo

go 1.13

require (
	github.com/emicklei/thingabee/log/v2 v2.0.0-20191214055724-d65d0b299bed // indirect
	github.com/emicklei/thingabee/v2 v2.0.4
)
```

Why the indirect require? The /log directory has its own module definition.

**Comment by emicklei** [comment]
with a go.mod
```
module github.com/emicklei/tryout

go 1.13

require github.com/emicklei/go-restful/v3 v3.0.0-rc2
```
and program
```
package main

import (
	"fmt"

	"github.com/emicklei/go-restful/v3"
	l "github.com/emicklei/go-restful/v3/log"
)

func main() {
	fmt.Println(new(restful.Container))
	l.Logger.Print("hello")
}
```
the Go module dependency is pickup up correctly and this program runs fine.

**Comment by tekkamanendless** [comment]
On the `demo` comment (2 above), the thingabee `v2.0.5` release fixes the log path and the correct `go.mod` and `go.sum` files end up looking like this (after `go mod tidy`):

*go.mod*

```
module demo

go 1.13

require github.com/emicklei/thingabee/v2 v2.0.5
```

*go.sum*

```
github.com/emicklei/thingabee/v2 v2.0.5 h1:837FiAGloQnaX9gUC7u5Kyp2MBiYZEmzQi1niPCU0lM=
github.com/emicklei/thingabee/v2 v2.0.5/go.mod h1:h8hMBeSJb9jo49XZ6+6PUF1rFDbmrFTCLRmnNwy8AWY=
```

The important thing to remember is that the module version is a suffix on the module name, not any arbitrary path (that was what `v2.0.5` was doing incorrectly).

Diff between `v2.0.4` and `v2.0.5`:

```
-import "github.com/emicklei/thingabee/log/v2"
+import "github.com/emicklei/thingabee/v2/log"
```

The thing here is the module is `github.com/emicklei/thingabee`, and its subsequent versions are `github.com/emicklei/thingabee/vN`.  Having a `v2` after the `log` implies that there is a module somewhere called `github.com/emicklei/thingabee/log` with its own `go.mod` file, etc.

On `tryout` (1 above), that looks like what I'd expect.

**Comment by emicklei** [comment]
I have updated both master and v3 branch and created the v3.0.0 version which supports Go Modules.

**Comment by y0ssar1an** [comment]
@emicklei I think you forgot to add a `go.mod` file. My understanding is that it's not a Go module until it has this file.

**Comment by emicklei** [comment]
@y0ssar1an the go.mod only exists in the v3 branch.

If you start importing the package using github.com/go-restful/v3 then the Go tooling will use the v3 branch instead of the master ( your go.mod should have:  require github.com/emicklei/go-restful/v3 v3.0.0
