### ISSUE TITLE
Path matching both root and parameter

### ISSUE THREAD

**Issue by SkinyMonkey** [emicklei/go-restful#384]
Is it possible to declare a path that match both "/" and "/{some_id}"?

I tried with several solutions but none seemed to work without redeclaring both possilibities separatly.

**Comment by emicklei** [comment]
I haven't used or seen this before. I am afraid, this is not possible. Did you try `/{subpath:*}` only and check whether the subpath is empty for the root case?

**Comment by SkinyMonkey** [comment]
Sadly I did and it throws a not found.

I setup a small gist to reproduce/study the problem here:
https://gist.github.com/SkinyMonkey/72b86672936dd06bae4925ebfc853137

I know it's not common but due to some previous design that would be hard to change I have to go with it.

**Comment by emicklei** [comment]
can this be closed?
