### ISSUE TITLE
Double compression 

### ISSUE THREAD

**Issue by bgadrian** [emicklei/go-restful#389]
Hello,

I have a small issue/question, how can I disable the gzip compression (from container.go) for a specific response.

Sometimes I have a content that is already compressed, and I do not want to decompress and let the restful compress it again, for optimization purposes.

I have found the contentEncodingEnabled flag but that is for all the routes and requests, I want to have a more granular effect.

Maybe if the container will look if a ContentEncoding header already exists? And do not compress it then?

**Comment by emicklei** [comment]
hi, i understand your usecase. Maybe indeed you should be able to control this per response. 
Will investigate teh ContentEncoding suggestion

**Comment by emicklei** [comment]
Alternatively, we could have an extra field in the the restful.Response to indicate that compression must be skipped.

**Comment by bgadrian** [comment]
Thanks for the answer!

From what I saw, the first problem in any fix is that the container compression stream is started before executing the handler, so without any major rehaul I guess the only way it would be to flag/filter only a specific route, which would be acceptable for most use cases I guess.

**Comment by emicklei** [comment]
yes, that is done because any filter should be able to abort the chain and respond by itself.

Furthermore, the NewCompressingResponseWriter already write the content-encoding header upon creation.

What if you create a separate container, disable contentEncoding and set the ServeMux to use the Default. Then you have 2 containers, one with, one without encoding. Then for each WebService choose the right container.

**Comment by emicklei** [comment]
or func (r *Route) EnableContentEncoding(enabled bool){}

**Comment by bgadrian** [comment]
That sounds better, but where to keep the flag, in the Routes metadata? 

I can make a PR if is ok

**Comment by emicklei** [comment]
or just a field in Route, same as WebService.  

yes, PR is welcome

**Comment by emicklei** [comment]
i think this can be closed.

**Comment by bgadrian** [comment]
The functionality is there, but I forgot to
* add the functionality in the Route Builder
* add tests
