### ISSUE TITLE
Make Response readable

### ISSUE THREAD

**Issue by IhorBondartsov** [emicklei/go-restful#391]
I created a wrapper for handler, i maked it for saving request and response to database. But I cant read response body.

**Comment by ic2hrmk** [comment]
Hi guys! I also need an opportunity to read body from response object for advanced logging and debug purpose. Now we suffers from inability to trace error responses between two automated systems written in Go and Java, so this feature would be just handsome!

**Comment by emicklei** [comment]
Capturing the response is possible but should not be done for every request, for all users of the package. So we could have this behaviour:
- per request (looking at Header?) 
- per Route ?
- per WebService ?
- globally for the whole package and disabled by default?

How would you use this feature?

**Comment by ic2hrmk** [comment]
We need it for the web-service layer as well. Our QA wanted to see request & response data from 3-rd party system that calls as via REST API (based on go-restful) and we have no access to it. I tried to explain it via simple diagram, attached to the post
![untitled diagram](https://user-images.githubusercontent.com/11685484/53637624-542d6700-3c2c-11e9-81b7-d6c018967383.png)

**Comment by emicklei** [comment]
hi,  i just add an example https://github.com/emicklei/go-restful/blob/master/examples/restful-full-logging-filter.go that should get you started. The response headers are not captured yet. Maybe you can complete the example as you would like it work

**Comment by ic2hrmk** [comment]
@emicklei Thank you so much for the example, we will try it out!

**Comment by IhorBondartsov** [comment]
Thank you!
