### ISSUE TITLE
DefaultReturns (status code 0) leads to invalid swagger spec

### ISSUE THREAD

**Issue by Gerrit91** [emicklei/go-restful#392]
Hi there,

maybe I am getting something wrong, but the `DefaultReturns` function in the route builder adds a response with status code 0 to the specification, which seems not to be compatible with the swagger spec 2.0. When trying to generate a client with go-swagger, it then raises the following error:

```
swagger generate client -f spec.json 
2019/02/27 09:35:18 validating spec xxx/spec.json
The swagger spec at "xxx/spec.json" is invalid against swagger specification 2.0. see errors :
- paths./v1/resource.get.responses.0 in body is a forbidden property
```

Actually, I think the problem is in go-restful-openapi, where code 200 is always considered to be the default response type, which was already questioned here: https://github.com/emicklei/go-restful-openapi/issues/10

To me it feels like the following code:

```
new(restful.WebService).Route(ws.GET("/").
		To(sr.getResource).
		Doc("get resource").
		Metadata(restfulspec.KeyOpenAPITags, tags).
		Returns(http.StatusOK, "OK", Resource{}).
		DefaultReturns("Unexpected Error", ErrorResponse{}))
```

Should actually produce a spec like this:

```
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Resource"
            }
          },
          "default": {
            "description": "Unexpected Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
```
Here is the description of how default responses are used: https://swagger.io/docs/specification/2-0/describing-responses/#default

Thanks!

**Comment by emicklei** [comment]
thank you for reporting this. I agree that the response is not correct. Did you try fixing this?

**Comment by Gerrit91** [comment]
Thanks for taking a look so fast!

I just opened two PRs, which I hope will address this issue accordingly. Feel free to comment on these if you want to discuss the detail. :)

https://github.com/emicklei/go-restful/pull/393
https://github.com/emicklei/go-restful-openapi/pull/54
