### ISSUE TITLE
Support google "Custom Methods" style urls

### ISSUE THREAD

**Issue by sindrepm** [emicklei/go-restful#394]
Does `go-restful` currently have support for routes like this?

`ws.Route(ws.POST("/projects/{name}:customVerb").To(h.handleCustomVerb))`

For example Google uses this pattern to implement custom methods on resources.
https://cloud.google.com/apis/design/custom_methods

I tried but just get a 404 error when hitting the endpoint.

**Comment by emicklei** [comment]
hi, the closest setup you can do now is similar to https://github.com/emicklei/go-restful/blob/master/examples/restful-path-tail.go

However, the concept is interesting and I would like to see what is needed to support this.

**Comment by emicklei** [comment]
so
```
func main() {
	ws := new(restful.WebService)
	ws.Route(ws.GET("/{name:*}").To(hello))
	restful.Add(ws)
	log.Fatal(http.ListenAndServe(":8080", nil))
}

func hello(req *restful.Request, resp *restful.Response) {
	io.WriteString(resp, req.PathParameter("name"))
}
```
with

    curl http://localhost:8080/name:customVerb

gives you:

    name:customVerb

**Comment by sindrepm** [comment]
> so
> 
> ```
> func main() {
> 	ws := new(restful.WebService)
> 	ws.Route(ws.GET("/{name:*}").To(hello))
> 	restful.Add(ws)
> 	log.Fatal(http.ListenAndServe(":8080", nil))
> }
> 
> func hello(req *restful.Request, resp *restful.Response) {
> 	io.WriteString(resp, req.PathParameter("name"))
> }
> ```
> with
> 
> ```
> curl http://localhost:8080/name:customVerb
> ```
> gives you:
> 
> ```
> name:customVerb
> ```

That would require all custom verbs to be handled by the same route / passed to the same handler.

**Comment by emicklei** [comment]
yes, i realise that's not want you want. 
a better suggestion is create a new CustomMethodsRouter, using the CurlyRouter as an example.
maybe it is only the `tokenizePath` that needs to be aware of this mode of operation. If that turns out to be the solution , we could extend CurlyRouter with this configurable behaviour.

**Comment by emicklei** [comment]
@sindrepm did you find a solution to this issue?

**Comment by ShiningRush** [comment]
@sindrepm @emicklei  i have already support google custom verb, plz check the pr

**Comment by emicklei** [comment]
this feature has been implemented by @ShiningRush
