### ISSUE TITLE
Nesting web services

### ISSUE THREAD

**Issue by andrewmeissner** [emicklei/go-restful#399]
Is there anyway to nest webservices?  Meaning, if I define a top layer ws

```go
api := new(restful.WebService)
api.Path("/api/v1")
```

and a lower layer api
```go
users := new(users.UserService{}.WebService()) // where .Path is defined as "/users"
```

can I somehow combine these two so the `/users` endpoint is reachable at `http://localhost/api/v1/users`?

**Comment by emicklei** [comment]
hi,

So the short answer is; there is no way to do nesting currently.

I understand what you ask for. It has been requested before (https://github.com/emicklei/go-restful/issues/320) and at that time, it was not followed up by me or the issue poster.

I wonder what it would take to have a function such as  top.AddNestedService(nested) that would copy all the routes into the top service. This requires some investigation.

**Comment by andrewmeissner** [comment]
Thanks for the reply @emicklei
