### ISSUE TITLE
chrome request header "application/signed-exchange;v=b3" causing mime parse error

### ISSUE THREAD

**Issue by siff-jason** [emicklei/go-restful#400]
I believe since Chrome 73 there is a new Accept request header and this appears to be causing a mime parse issue with go-restful.

The request header:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
```

The error:
```
mime.go:37: unable to parse quality in application/signed-exchange;v=b3, strconv.ParseFloat: parsing "b3": invalid syntax
```

**Comment by emicklei** [comment]
thank you for reporting this. i will revisit the parsing section.

**Comment by siff-jason** [comment]
Thanks @emicklei - i've grabbed the latest and all seems good!
