### ISSUE TITLE
Is there a way to preserve path parameter with double slash

### ISSUE THREAD

**Issue by yathindra** [emicklei/go-restful#402]
Is there a way I can configure the curly router to preserve `//` in the path parameter (for example: `/go//website/`)? In the handler, I see the path parameter has all the double slashes replaced with single slash. I know this is the right behavior. But wanted to see if there is a way to preserve it. One way I could workaround this issue was to double URL encode the path parameter.

**Comment by emicklei** [comment]
No, there is not.  You could try to implement your own Router.
