### ISSUE TITLE
how can i get routeFunction while execute filter

### ISSUE THREAD

**Issue by jasonlkx** [emicklei/go-restful#403]
in the function container.dispatch, when create the FilterChain, there is a new function for the Target, which execute the route.Function. why not just assign the route.Function to Target, so i can get the routeFunction while execute my own filter

**Comment by emicklei** [comment]
i think you are referring to https://github.com/emicklei/go-restful/blob/master/container.go#L283 .
I do not recall why but I will investigate and test your suggestion.

**Comment by jasonlkx** [comment]
yeah,  just like https://github.com/emicklei/go-restful/blob/master/route.go#L73 .
but this method "dispatchWithFilters" has never bean called

**Comment by emicklei** [comment]
please have a look/try at the PR

**Comment by jasonlkx** [comment]
that's help me out. thanks for your changed
