### ISSUE TITLE
why go-restful do not support application/json when use post request?

### ISSUE THREAD

**Issue by kitianFresh** [emicklei/go-restful#406]
I found that restful.Request can not parse post data when i use json as post data,

curl -v -H "Content-Type: application/json" -d '{"name":"inf-hulk-demo-ppe-e4ea85bdf7257f224823b1be56ea3c61-q28ru","cluster":"1","namespace":"default"}' -X POST "http://localhost:7777/v1/pods/batch"

server side code:

clusterids, err := request.BodyParameter("cluster")
	if err != nil {
		fmt.Println(err)
	}
	podnames, err := request.BodyParameter("name")
	if err != nil {
		fmt.Println(err)
	}
	namespace, err := request.BodyParameter("namespace")
	if err != nil {
		fmt.Println(err)
	}
	respData, err := ioutil.ReadAll(request.Request.Body)
	if err != nil {
		fmt.Println(respData)
	}
	fmt.Println(clusterids)
	fmt.Println(podnames)
	fmt.Println(namespace)

all is null

**Comment by emicklei** [comment]
That's not how you get to the data posted. BodyParamter is only for Form posting. 
Your example requires a type definition with "name" and "cluster" etc.
See https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go#L91 for an example.

**Comment by emicklei** [comment]
can this be closed?

**Comment by kitianFresh** [comment]
@emicklei  So sorry for late to reply, I have got it from readEntity method. Thanks for your answer. You can close it
