### ISSUE TITLE
How i get request body more than once？

### ISSUE THREAD

**Issue by kitianFresh** [emicklei/go-restful#411]
I found go-restful can not ready body more than once. you can only call ReadEntity once, if you call it again, there is no body data any more.

I want get body twice because i want check body param in filter and then decide whether to chain it to handler

**Comment by emicklei** [comment]
there is an example that shows how to do this.  
The example is about full logging of request and ressponse data.
The implementation uses the ability to set the Body again with a new reader after consuming it.

**Comment by kitianFresh** [comment]
I’ve got it， thanks!

**Comment by xdhuxc** [comment]
@emicklei can this implementation write in req.ReadEntity(), it may be a more elegant implementation form.
