### ISSUE TITLE
WriteError return its argument as error status instead result of WriteErrorString

### ISSUE THREAD

**Issue by renkam** [emicklei/go-restful#415]
In function https://github.com/emicklei/go-restful/blob/5d8b667fa26d374ff451368b5040d3adbb9c7db4/response.go#L178 `WriteError` argument `err` is returned instead of result of calling `WriteErrorString`.

**Comment by emicklei** [comment]
good catch. this needs to be changed

**Comment by emicklei** [comment]
i will close this as the fix has been pushed to master
