### ISSUE TITLE
is go-restful support websocket?

### ISSUE THREAD

**Issue by Jiajing-Hu** [emicklei/go-restful#416]
I write a program  based on go-restful.
Recently I want to add a new API which use websocket.But the ws.Route seems only support http request..
so..I wonder does go-restful support websocket..
and if the answer is yes...May I ask how?

thank you .
sorry for my poor English

**Comment by emicklei** [comment]
Hi, 

Currently, it does not support websockets. Last time I used websocket, I initialized a direct handler using the golang/net/x websocket package.  The whole request response flow is quite different from REST. Even if it is possible to put the Route in go-resftfull, the solution would not be able to use any of the other runtime logic of this package.

**Comment by Jiajing-Hu** [comment]
okay..I'll look for other way to solve this problem.

anyway thank you and your excellent go-restful
