### ISSUE TITLE
can not specify response header?

### ISSUE THREAD

**Issue by tianxiaoliang** [emicklei/go-restful#419]
```go
// Returns allows you to document what responses (errors or regular) can be expected.
// The model parameter is optional ; either pass a struct instance or use nil if not applicable.
func (b *RouteBuilder) Returns(code int, message string, model interface{}) *RouteBuilder {
	err := ResponseError{
		Code:      code,
		Message:   message,
		Model:     model,
		IsDefault: false, // this field is deprecated, use default response instead.
	}
	// lazy init because there is no NewRouteBuilder (yet)
	if b.errorMap == nil {
		b.errorMap = map[int]ResponseError{}
	}
	b.errorMap[code] = err
	return b
}
```

now I can not use code to describe the response header, it can not automatically generate a complete swagger doc.

is there any way I can generate response header spec?

**Comment by emicklei** [comment]
Did you have a look how go-restful-openapi is generating Swagger (OpenAPI) docs?

**Comment by tianxiaoliang** [comment]
yes

**Comment by emicklei** [comment]
If you use go-restful-openapi then with the PostBuildSwaggerObjectHandler you can perhaps achieve what you want.  Your question is not clear about what you are missing in "describe the response header"
