### ISSUE TITLE
supporting compressed _request_ bodies

### ISSUE THREAD

**Issue by siff-jason** [emicklei/go-restful#427]
It's not just responses that may be large where compression is useful - there can also be requests (POSTs/PUTs) with large request bodies that could also benefit from compression. This is really only possible where you control both ends because the request comes in and there is no negotiation whether it's supported or not (unlike Accept-Encoding for responses). So it's not normally something that's supported. i.e. you'd need to set it up on the requester side and know the server side supports it.

So would it be possible to (optionall?) support requests checking for Content-Encoding header and automatically handle decompressing the body if compressed?

**Comment by emicklei** [comment]
yes, I think we can add that feature. Do you want to take a shot at it?

**Comment by siff-jason** [comment]
yeah i can give it a shot

**Comment by emicklei** [comment]
any luck with the proposal?

**Comment by emicklei** [comment]
i am closing this issue. please reopen if you or someone else needs this
