### ISSUE TITLE
Coverage report?

### ISSUE THREAD

**Issue by sundowndev** [emicklei/go-restful#428]
Hi, awesome project! Is it possible to add a coverage report? Thanks

**Comment by emicklei** [comment]
sure, will add it

**Comment by emicklei** [comment]
i am working on getting coveralls.io to work with this repo

**Comment by sundowndev** [comment]
codecov works well too 👍

**Comment by emicklei** [comment]
done for master, if it works then I will add it to v3 branch as well.
