### ISSUE TITLE
 skip the query parameter if it is empty

### ISSUE THREAD

**Issue by SKowshik4614** [emicklei/go-restful#429]
Hi Guys,

I am using go-micro frame work to build an microservice. Can anyone help me how to continue with the request if the query parameter is empty?

Main:
func main() {
log.Println("Starting")
service := web.NewService(
web.Name("ms.api"),
web.Address(":8081"),)
if err := service.Init(); err != nil {
log.Fatal(err)
}

cl = list.NewListService("ms.list", client.DefaultClient)

ing := new(List)
wc := restful.NewContainer()

ws := new(restful.WebService)
ws.Consumes(restful.MIME_XML, restful.MIME_JSON, restful.MIME_OCTET).
	Produces(restful.MIME_JSON).
	Path("/services/list")

ws.Route(ws.GET("/env/{env}/type/{type}").To(ing.GetList))

wc.Add(ws)
service.Handle("/", wc)

if err := service.Run(); err != nil {
	log.Fatal(err)
}

}

My Function:
func (ing *List) GetList(req *restful.Request, rsp *restful.Response) {
log.Println("Get List")
env := req.PathParameter("env")
type := req.PathParameter("type")
max := req.QueryParameters("max")
sort := req.QueryParameters("sort")
}

Here max and sort are my parameters from the URL. If both the value are passed then the URL is processed and no issues there. Suppose the parameter max or sort is not passed the code breaks and does not respond. I need help to understand is there a way i can make these parameters not mandatory? if either of them is not passed my service should process the URL request.

**Comment by emicklei** [comment]
In what way does your code break?  Can't you check whether the max is empty, e.g. len(max) > 0 before using it in your downstream code?
