### ISSUE TITLE
Composable WebServices

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [emicklei/go-restful#430]
Hi,

I've CRUD operations for several entities in my system. All entities are placed under a namespace, so the URLs look like this
`/namespace/{namespace}/entity1`
`/namespace/{namespace}/entity2`
My first approach was to create WebService for each entity and add routes withing every web service. The problem I've got is that go-restful throws an error that I cannot register multiple services with the same root path `/namespace`.

I fixed this by having one WebService for all entities. I pass WebService object around so the routes can be added to it. I don't really like this approach, because I'd like to avoid mutating the state of the object I receive as much as possible.

What would be a good solution for such a case?

I figured out I could write a composable Webservice - create a service and aggregate every other service (kind of like Container). The problem is that I cannot take routes from one WS and add to another because the `routes` field in WebService is protected. Would you accept a PR that exposes setter for routes?

Thanks!

**Comment by emicklei** [comment]
A similar request has been done in the past https://github.com/emicklei/go-restful/issues/399 but we did not follow up on that. 
I think it is still worth adding it as a feature. 
Your suggestion to add a Setter feels like a workaround.
Please have a look at the old issue (and so will I) then we can discuss implementation strategies

**Comment by emicklei** [comment]
how about a CopyWithRouters method?
