### ISSUE TITLE
Implementing CSRF protection

### ISSUE THREAD

**Issue by a-roberts** [emicklei/go-restful#431]
Hi all, we've got a Go backend + React (webpack bundled) based frontend for our Tekton Dashboard and I'm working on https://github.com/tektoncd/dashboard/issues/1255. We're currently using go-restful and wondering if anyone's successfully implemented CSRF protection with this library - I've had a good search and the suggestions involve using gorilla/csrf - I can't see how to get that working with go-restfuls APIs (and I'd rather not rewrite our routing code to use gorilla/mux).

Any pointers/examples where you've done this would be appreciated, lemme know if I've missed anything please!

**Comment by emicklei** [comment]
there seems to be several methods to mitigate CSRF (https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#token-based-mitigation).
I will have a look at the gorilla implementation to have a better idea what to do here.

**Comment by emicklei** [comment]
gorilla/csrf supports "any other router/framework that rallies around Go's http.Handler interface."  I will put together an example how this can be used (i guess it can) with restful.

**Comment by a-roberts** [comment]
> gorilla/csrf supports "any other router/framework that rallies around Go's http.Handler interface." I will put together an example how this can be used (i guess it can) with restful.

That'd be useful, thanks! FYI we have an implementation merged now, using the existing go restful routing set up, see https://github.com/tektoncd/dashboard/pull/1351
