### ISSUE TITLE
Was the tag v1.1.4 deleted recently?

### ISSUE THREAD

**Issue by AbelHu** [emicklei/go-restful#432]
@emicklei Just want to know whether the tag v1.1.4 was deleted recently. And the latest v1 tag v1.2 is not a valid semver version. Would you have any plan to create a new tag v1.2.0?

**Comment by emicklei** [comment]
no tag was deleted, ever. Since the go module support, new tags are v3.0+  . And yes, older tags may not conform to semver. If it helps, I can create a tag for a specific commit if you want.

**Comment by AbelHu** [comment]
Just confirm this. Will ask your help if we really need a specific commit. Thanks.
