### ISSUE TITLE
Path operation security for OpenAPI spec

### ISSUE THREAD

**Issue by exavolt** [emicklei/go-restful#433]
Is there any support for defining path operation security which follows [OpenAPI's spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object).

I can already define the supported securities through `PostBuildSwaggerObjectHandler` but I am unable to find a way to refer those from the endpoints.

**Comment by emicklei** [comment]
we could add this to a Route ; would you be interested in creating a PR?
