### ISSUE TITLE
Acceptable representations not listed in body of '406: Not Acceptable' responses

### ISSUE THREAD

**Issue by brackendawson** [emicklei/go-restful#434]
RFC 7231 says that the server *should* include a list of representations in the body of a 406 response: https://tools.ietf.org/html/rfc7231#section-6.5.6

Currently restful just says:
```
HTTP/1.1 406 Not Acceptable
Date: Sun, 24 May 2020 14:31:55 GMT
Content-Length: 19
Content-Type: text/plain; charset=utf-8

406: Not Acceptable
```
<details>
<summary>Test server</summary>

```
package main

import (
	"io"
	"log"
	"net/http"

	"github.com/emicklei/go-restful"
)

func main() {
	ws := new(restful.WebService)
	ws.Route(ws.GET("/hello").Produces("text/plain").To(hello))
	restful.Add(ws)
	log.Fatal(http.ListenAndServe(":8080", nil))
}

func hello(req *restful.Request, resp *restful.Response) {
	io.WriteString(resp, "world")
}

```
</details>

But the RFC doesn't have an opinion on what form that list should take. As restful already provides a text/plain body, I think it should be expended to include each of the route's produces, perhaps:
```
406: Not Acceptable

Acceptable: text/plain, application/json
```

If you agree with the above, I'm happy to do the work.

**Comment by emicklei** [comment]
yes, please help fixing this.
