### ISSUE TITLE
go restful examples restful-user-resource.go has error

### ISSUE THREAD

**Issue by zhangweidongyyl** [emicklei/go-restful#440]
go restful examples restful-user-resource.go has error in createUser and updateUser

**Comment by emicklei** [comment]
i ran the example and got this
```
./restful-user-resource.go:148:5: unknown field 'ContactInfoProps' in struct literal of type spec.ContactInfo
./restful-user-resource.go:155:5: unknown field 'LicenseProps' in struct literal of type spec.License
```
then I updated the go-openapi package like this
```
 go get -u -v github.com/go-openapi/spec
```
and the example worked for me

**Comment by emicklei** [comment]
yes, the problem is that these examples do not use Go modules, yet. It is on my todo list
