### ISSUE TITLE
How can I get the response body in the Response object?

### ISSUE THREAD

**Issue by whypro** [emicklei/go-restful#441]
I want to logging the response body, but I cannot found that field directly in restful.Response struct. 
I also try to make a wrapper to wrap Response object but it isn't an interface. So I cannot use the wrapper to replace `resp` in `chain.ProcessFilter(req, resp)`
How can I get the response body in the Response object?
Thanks in advanced!

**Comment by emicklei** [comment]
have a look at https://github.com/emicklei/go-restful/blob/master/examples/restful-full-logging-filter.go

**Comment by whypro** [comment]
@emicklei Thanks a lot!
