### ISSUE TITLE
Request's ReadEntity Function gives error if there is empty Body

### ISSUE THREAD

**Issue by raghavgg** [emicklei/go-restful#452]
I am using request.ReadEntity Function for reading JSON request body. In my case the body is optional. When there is Json body then it works fine but when it's empty then it gives "EOF" error.

I want to know, if it's a issue or functionality.

**Comment by emicklei** [comment]
I don't think it is an issue. An empty document is not a valid JSON document. 
But maybe the ReadEntity should inspect the Content-Length header and if it was 0 then return a nil.  Have to think a bit more about this (it would break compatibility of the pkg)

**Comment by emicklei** [comment]
i am closing this now. feel free to comment later.
