### ISSUE TITLE
Question: How to process HTTP Patch requests with content-type application/json-patch+json

### ISSUE THREAD

**Issue by chidv** [emicklei/go-restful#464]
Hi,

Does this package supports JSON Patch content type (application/json-patch+json)  ?

In all the examples I see, they have either MIME_JSON/MIME_XML..

**Comment by emicklei** [comment]
The Route.Consumes accepts any string. The MIME_JSON is just a string constant.
I suggest you change the example and test yourself.

**Comment by chidv** [comment]
Yes. I understand now. Thanks for pointing out. 
Will use the JSON Patch content-type.
