### ISSUE TITLE
Request.SelectedRoutePath panics if no route is selected

### ISSUE THREAD

**Issue by axw** [emicklei/go-restful#467]
`Request.SelectedRoutePath` panics when called on a request with selected route. For example, this happens when using Elastic APM's `apmrestful` filter: https://github.com/elastic/apm-agent-go/blob/f62afdfda01d0cbe73f477c357d5b8a3017e5144/module/apmrestful/filter.go#L55-L66

This is caused by https://github.com/emicklei/go-restful/pull/462/files. Previously the method would return "".

**Comment by emicklei** [comment]
thank you for reporting this. somehow the tests did not capture this. will work on a fix asap

**Comment by emicklei** [comment]
https://github.com/emicklei/go-restful/pull/468
