### ISSUE TITLE
IndexOutofBound panic during RemoveRoute()

### ISSUE THREAD

**Issue by jeffreydwalter** [emicklei/go-restful#471]
The issue referenced in https://github.com/emicklei/go-restful/issues/276 is not really fixed by the commit that was merged in.

There is still a panic here https://github.com/emicklei/go-restful/blob/1e8c63ce7906ee023956e8068ce4c54d634c2d2b/web_service.go#L190 when you call `RemoveRoute()` with a route that is not in w.routes.

You can reproduce the issue with this code:
```
func main() {
	ws := new(WebService)
	ws.SetDynamicRoutes(true)
	ws.Route("GET", "/some/path")
	ws.RemoveRoute("/some/path/that/does/not/exist", "GET")
	ws.Routes()
}
```

I created a go playground that reproduces the issue here: https://play.golang.org/p/SYUMGQeY0cU

Changing `RemoveRoute()` to this fixes the issue:
```
func (w *WebService) RemoveRoute(path, method string) error {
	if !w.dynamicRoutes {
		return errors.New("dynamic routes are not enabled.")
	}
	w.routesLock.Lock()
	defer w.routesLock.Unlock()
	newRoutes := make([]Route, 0)
	for ix := range w.routes {
		if w.routes[ix].Method == method && w.routes[ix].Path == path {
			continue
		}
		newRoutes = append(newRoutes, w.routes[ix])
	}
	w.routes = newRoutes
	return nil
}
```

**Comment by jeffreydwalter** [comment]
I created a PR which includes the suggested fix here: https://github.com/emicklei/go-restful/pull/472

**Comment by emicklei** [comment]
thank you reporting this and providing a fix using the PR. I will review the changes and merge on approval.

**Comment by jeffreydwalter** [comment]
Fixed in PR https://github.com/emicklei/go-restful/pull/472.
