### ISSUE TITLE
query parameters in route 

### ISSUE THREAD

**Issue by albertforweb** [emicklei/go-restful#473]
Hi,

I have registered a route like this (use path parameters, not query parameters) :

RegisterAPI("GET", "/objects/{bucket}/{key}", restful.RouteFunction(api.GetObjectData))

works fine when make calls like this:

$ curl -i http://localhost/objects/mybucket/myobject.txt

**but** if I want to add query parameters like this , it does not work, get "no matches found":

$ curl -i http://localhost/objects/mybucket/myobject.txt**?begin=0&end=20**

does the go-restful support this ?

**Comment by emicklei** [comment]
the query part of a url is not used for matching. The example you provided contains 2 stars ** . Is that part of the path?

**Comment by albertforweb** [comment]
the "**" was added by the github editor when you want to bold the words.

the real request is this: 

$ curl -i http://localhost/objects/mybucket/myobject.txt?begin=0&end=20

**Comment by emicklei** [comment]
can you share the example code? it should work so I want to reproduce it.

**Comment by albertforweb** [comment]
code :

`
package main

import (
	"github.com/emicklei/go-restful/v3"
	"log"
	"net/http"
	"path"
)

var logger = log.Default()
var wsContainer = restful.NewContainer()
var wsApp = new(restful.WebService).Doc("app")

func registerAPI(method string, subPath string, featureflagKey string, handler restful.RouteFunction, ws *restful.WebService) {
	log.Default().Printf("Registering %s route: %s %s", ws.Documentation(), method, path.Join(ws.RootPath(), subPath))
	route := ws.Method(method).Path(subPath).To(handler)
	ws.Route(route)
}

func RegisterAPI(method string, subPath string, handler restful.RouteFunction) {

	registerAPI(method, subPath, "", handler, wsApp)
}

func DoPathParameters(request *restful.Request, response *restful.Response) {
	logger.Printf("path parameters : %v", request.PathParameters())
	
	response.WriteHeader(http.StatusOK)

}


func DoQueryParameters(request *restful.Request, response *restful.Response) {
	
	logger.Printf("query parameter start : %v", request.QueryParameters("start"))
	logger.Printf("query parameter end : %v", request.QueryParameters("end"))

	response.WriteHeader(http.StatusOK)

}

func main() {
	var port = "8081"

	RegisterAPI("GET", "/range/start/{start}/end/{end}", restful.RouteFunction(DoPathParameters))
	RegisterAPI("GET", "/range", restful.RouteFunction(DoQueryParameters))

	wsContainer.Add(wsApp)

	var server = &http.Server{
		Addr:     "0.0.0.0:" + port,
		Handler:  wsContainer,
		ErrorLog: logger,
	}

	server.ListenAndServe()
}

`

here is the result:

% curl -i http://localhost:8081/range/start/1/end/2
HTTP/1.1 200 OK
Date: Wed, 21 Jul 2021 23:35:59 GMT
Content-Length: 0

% curl -i http://localhost:8081/range?start=1&end=2
[1] 87711
zsh: no matches found: http://localhost:8081/range?start=1

**Comment by albertforweb** [comment]
never mind, url with curl need to be in quotes:

% curl -i "http://localhost:8081/range?start=1&end=2"
