### ISSUE TITLE
Compression is applied to already compressed responses

### ISSUE THREAD

**Issue by mpdn** [emicklei/go-restful#481]
If a request has an `Accept-Encoding` header and the route itself responds with a compressed response with `Content-Encoding` set, restful will try to compress the response again, resulting in an invalid response body with two `Content-Encoding` headers.

Compression should probably only be applied if there is no `Content-Encoding` header in the response from the route.

**Comment by emicklei** [comment]
hi, thank you for reporting this. I can remember solving a similar reported problem. I will have a look at it again.

**Comment by mpdn** [comment]
I am using `gzip` and the route I have responds with compressed content with a `content-encoding: gzip` header set as well.

**Comment by emicklei** [comment]
So your response already has compressed content and the package should check the response header too to prevent the duplication?

**Comment by mpdn** [comment]
Yes, exactly. Otherwise you end up gzipping the response twice.

Though I guess if if compressing it once is good then twice must be better. 😆

**Comment by emicklei** [comment]
@mpdn can you verify the change in the PR?
