### ISSUE TITLE
Support content-type application/json for body parameter

### ISSUE THREAD

**Issue by BennyDjo** [emicklei/go-restful#486]
Hello,

I saw there was already a question (issue 406) about this, and you answered it was by designed not supported. 
I wish to make a feature request about this. I understand that supporting application/json for BODY is not 100% standard as BodyParamter is made for Form. 
Now, I am not an expert in HTTP, and I might be mixing things, in which case sorry for the dummy request :). I feel it is however very common to have webserver supporting it Json encoded Body Parameter. I would also argue most HTTP application, such as curl, Postman ..., support Http request with body Json encoded. 

Would you consider adding support for this? 
In any case, thanks for the great work !

**Comment by emicklei** [comment]
could you provide an example how you would like it to work?

**Comment by emicklei** [comment]
having looked at #406 again, I think you want BodyParameter to unmarshal JSON when application/json is sent and return the value with the parameter name as key?

**Comment by BennyDjo** [comment]
Hello, 
Thanks for the reply
Yes indeed.
To give an example, if I make a request like this:

`curl -XPOST  -H "Accept: application/json"  https://127.0.0.1/myAPI  -d {"key1":"value1", "key2":"value2"} 
`
Then, inside the webserver, I can acces body parameter with:

```
func foo( request *restful.Request, response *restful.Response) {
  key1, _ := request.BodyParameter("key1") // return 'value1'
  key2, _ := request.BodyParameter("key2") // return 'value2'
}
```

**Comment by emicklei** [comment]
If we change BodyParameter to do this then its usage is very limited ; body must be a hash, value must be string.

Same can be achieved using ReadEntity
```
func foo( request *restful.Request, response *restful.Response) {
  var body struct {
       Key1, Key2 string
  }
  _ = request.ReadEntity(&body)
  key1 := values.Key1
  key2 := values.Key2
}
```

**Comment by emicklei** [comment]
feel free to reopen if you need more help
