### ISSUE TITLE
Question: How to set httponly cookie in response

### ISSUE THREAD

**Issue by BrucePeng92** [emicklei/go-restful#487]
I want to set the token as a cookie. How can I set it as a response using HTTPonly ?

**Comment by emicklei** [comment]
something like this, accessing the embedded ResponseWriter directly.

```
yourCookie := &http.Cookie{
    Name: "somename",
    Value: "somevalue"
    HttpOnly: true
}
http.SetCookie( restfulResponse.ResponseWriter, yourCookie )

**Comment by BrucePeng92** [comment]
Thanks for your reply. I used "WS. Route" as the service route. Is there a way to set cookies in this method?

In "restful. Routefunction", can I set cookies by running "http.SetCookie"?

**Comment by BrucePeng92** [comment]
It works, thanks again.
