### ISSUE TITLE
New release with the latest commit

### ISSUE THREAD

**Issue by vinpai** [emicklei/go-restful#498]
When can we expect a new release with the new commits ? Specifically, looking for one with this commit which fixes a cors issue - https://github.com/emicklei/go-restful/commit/f292efff46ae17e9d104f865a60a39a2ae9402f1

**Comment by emicklei** [comment]
Hi @vinpai , I don't this commit is fixing the issue completely. As suggested in the PR, I am thinking about making it more explicit. The allowed domains are just strings + add a function hook such that you can provide your own matching logic. Would that solve your problem?

**Comment by vinpai** [comment]
I am actually not using this library directly, but one of the dependencies we are using is using this. Looks like adding a callback should work as then the responsibility of providing the logic would be on the user of the library. But why not make it an explicit list of domains instead ? Or was a regex match the original intention behind that param ?

**Comment by emicklei** [comment]
@vinpai so with the PR is supports both:  a callback AND an explicit list of domains.
