### ISSUE TITLE
swagger example does not use go-restful/v3

### ISSUE THREAD

**Issue by bokunodev** [emicklei/go-restful#499]
swagger example does not use `go-restful/v3` and `go-restful-swagger12` is not compatible with `go-restful/v3`
```log
cannot use absensiNext.Container.RegisteredWebServices() (value of type []*"github.com/emicklei/go-restful/v3".WebService) as []*"github.com/emicklei/go-restful".WebService value in struct literal
```

**Comment by emicklei** [comment]
@bokunodev you should look at https://github.com/emicklei/go-restful/tree/v3/examples/openapi instead.
The swagger example is there for those that are using the older non-v3 versions. Maybe I will delete it...

**Comment by emicklei** [comment]
good point, I will revist this
