### ISSUE TITLE
can resful.Webservice be chained? [question]

### ISSUE THREAD

**Issue by bokunodev** [emicklei/go-restful#500]
can i chain resful.Webservice's ?

**Comment by emicklei** [comment]
@bokunodev can you explain what you expect with chaining?
Do you mean: if the first cannot match the URL then try the next in the chain?

**Comment by emicklei** [comment]
you can add routes to an existing webservice
```
func (w *WebService) Route(builder *RouteBuilder) *WebService {
```
removal is also possible when you enable dynamic routes
