### ISSUE TITLE
[bug] types with same name mixed up

### ISSUE THREAD

**Issue by bokunodev** [emicklei/go-restful#506]
```go
type SekResponse struct {
	Meta    datatable.Response
	Results []*model.Sek `json:"results"`
}
```
i've go structs like above, for some reason the generated doc contain fields that does not belongs to that type.
change the type name does fix the problem.
same type name with different import path get mixed up for some reason.
i'll make a reproducible example later since the original codebase is quite large.

**Comment by emicklei** [comment]
> i think this should be in the openapi repo. but i'm not sure.

yes , better have it there

**Comment by emicklei** [comment]
> `restful.WebService` as `.TypeNameHandler` method. but the handler only invoked for sample passed to`.Reads` and not `.Returns` and it only change type name in the ref and not the definition. i add this to `main.go`
> 
> ```go
> ws.TypeNameHandler(func(sample interface{}) string {
> 	t := reflect.TypeOf(sample)
> 	name := fmt.Sprintf("%s.%s", t.PkgPath(), t.Name())
> 	name = strings.ReplaceAll(name, "/", "_")
> 	log.Println(name)
> 	return name
> })
> ```

Without looking into the details, I think a handler invocation for Returns is possible.  The definition change is a bigger challenge.

**Comment by emicklei** [comment]
Move to go-restful-openapi repo
