### ISSUE TITLE
Request.QueryParameter function consumes large memory for big request

### ISSUE THREAD

**Issue by wofanli** [emicklei/go-restful#510]
I try to process query parameters before the whole HTTP request body are well-received in server. However, looks like Request.QueryParameter would wait for the whole HTTP request body.

>func (r *Request) QueryParameter(name string) string {
>	return r.Request.FormValue(name)
>}

Could we replace this function with something like:  r.Request.URL.Query()[name][0]?

**Comment by emicklei** [comment]
hi, thank you for reporting this. I will have a look at this issue.

**Comment by emicklei** [comment]
can you verify the fix @wofanli  so this can be closed ?
