### ISSUE TITLE
Support for multiple return types

### ISSUE THREAD

**Issue by Jefftree** [emicklei/go-restful#514]
Is there any plan to support an endpoint capable of returning multiple return types? Eg: a `ws.Route(...).Writes(TypeA{}}, TypeB{})`

**Comment by emicklei** [comment]
can you explain the usecase?  does the OpenAPI also support this?

**Comment by Jefftree** [comment]
OpenAPI V3 supports returning a oneOf (https://swagger.io/specification/#discriminator-object). Kubernetes has endpoints that could return one of multiple values and I think it'd be useful if the WebService object could express that as well.

**Comment by emicklei** [comment]
@Jefftree , did you have a look at the PR?

**Comment by Jefftree** [comment]
Thanks for the addition, will test it out this week but marking this as closed for now.
