### ISSUE TITLE
The go-restful-swagger12 not support go-restful version 3

### ISSUE THREAD

**Issue by weijian2014** [emicklei/go-restful#525]
Hi guys, I have tried to integrated swagger in my project, but I got a syntax error as blow:
```
ws := new(restful.WebService)
wss := []*restful.WebService{ws}
config := swagger.Config{
    WebServices: wss,
    ApiPath:     "/apidocs.json",
    SwaggerPath: "/apidocs/"}
swagger.InstallSwaggerService(config)
```

`cannot use wss (variable of type []*"github.com/emicklei/go-restful/v3".WebService) as []*invalid type value in struct literalcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)`

I deduce that go-restful-swagger12 does not support using go-restful version 3, is there any workaround I can do?

**Comment by emicklei** [comment]
@weijian2014 thank you for reporting this. Indeed that package is actually no longer maintained.
Instead, you could use `https://github.com/emicklei/go-restful-openapi` instead. See the readme of that package about compatibility

**Comment by weijian2014** [comment]
@emicklei  Thanks for your reply, for this, I think it should be described in order to reduce confusion.

**Comment by monofone** [comment]
Can you please remove the reference to the "github.com/emicklei/go-restful-swagger12" from the example in https://github.com/emicklei/go-restful/blob/v3/examples/swagger/restful-swagger.go it seems to force go to download this code in pipelines when iterating over the directories. I could not reproduce it locally but in a build environment I was able to trigger the error safely

```
Error: load packages in root "/builds/.go/pkg/mod/github.com/emicklei/go-restful/v3@v3.9.0": err: exit status 1: stderr: go build github.com/emicklei/go-restful-swagger12: examples/swagger/restful-swagger.go:8:2: no required module provides package github.com/emicklei/go-restful-swagger12; to add it:
	go get github.com/emicklei/go-restful-swagger12
go build github.com/emicklei/go-restful: examples/swagger/restful-swagger.go:7:2: no required module provides package github.com/emicklei/go-restful; to add it:
```
This comes from a operator SDK project and is triggered by the `generate` and `manifest` targets when running tests.

And nowhere you can find anything about it, so I documented it here for others to hopefully help.

**Comment by emicklei** [comment]
@monofone done
