### ISSUE TITLE
Questions about WebService Path

### ISSUE THREAD

**Issue by 10196** [emicklei/go-restful#530]
When adding a route using WebService.Path("/example") and WebService.GET(""), I expect the access link to be "... /example", but actually I have to access "... /example/".

I don't think the "/" at the end is necessary, I suggest optimizing the concatPath function by not adding a "/" at the end when path2 is "".

Version: v3.10.0

Thanks.

**Comment by emicklei** [comment]
thank you for reporting this. The slash is not needed.  I will have a look again

**Comment by emicklei** [comment]
@10196 please have a look at the examples in /examples/issue519.  The latest version is 3.10.2
