### ISSUE TITLE
Why were the patch versions for vulnerability (snyk id:SNYK-GOLANG-GITHUBCOMEMICKLEIGORESTFULV3-2435654) released so late?

### ISSUE THREAD

**Issue by Silence-worker-02** [emicklei/go-restful#533]
Hello, we are a research team working on Golang. During our investigation, we found the vulnerability (https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMEMICKLEIGORESTFULV3-2435654) was addressed in commit 926662532deb450272956c7bc573978464aae74e. However, we noticed that the patch version was released after long time (103 days).  We are curious about the reasons behind the delayed release of the patch version, as it may hinder the efficient distribution of patches to downstream users. Could the reason be 

1.Issues with testing and CI checking. 

2.Other commits have to be incorporated into one release. 

3.By convention, versions are not frequently released. 

4.Other reasons. 

Thank you for your attention, and we look forward to receiving your reply.

**Comment by emicklei** [comment]
Hi,

I recall that I found this issue to be of low risc and therefore did not pay much attention to it

**Comment by Silence-worker-02** [comment]
Thank you for your reply!
