### ISSUE TITLE
default values of a slice field in a Go struct

### ISSUE THREAD

**Issue by xdanbinn** [emicklei/go-restful#534]
When generating swagger.json using restful package in Go, the default value for slice type parameters is rendered as string type, which cannot be correctly displayed as array in Swagger UI.
How should I define the json tag for default values of a slice field in a Go struct?
use 
github.com/emicklei/go-restful/v3 v3.7.4
github.com/emicklei/go-restful-openapi/v2 v2.9.0

**Comment by xdanbinn** [comment]
<img width="834" alt="企业微信截图_16917256112937" src="https://github.com/emicklei/go-restful/assets/59168889/07cf3cba-4e14-40e8-a5e9-d93dc430b9c7">
It looks like it does not support setting default values for slices.

**Comment by emicklei** [comment]
thank you for reporting this.  I think this issues is specific to the go-restful-openapi package. Can you prepare a test for this issue and report in the go-restful-openapi  github repo?

**Comment by emicklei** [comment]
this issue must be reported in the go-restful-openapi github repo
