### ISSUE TITLE
mis-route with multiple webservice and regex routeToken

### ISSUE THREAD

**Issue by haitch** [emicklei/go-restful#547]
when dealing with multiple webservice in same container, and regex routeToken, go-restful have defect on selecting webservice.

here is a code snippit reproduce the issue: [go playground link](https://go.dev/play/p/En5L85uMxzx)
```golang
package main

import (
	"fmt"
	"io"
	"net/http/httptest"

	restful "github.com/emicklei/go-restful/v3"
)

func main() {
	holaWS := new(restful.WebService).Path("/{:hola}")
	helloWS := new(restful.WebService).Path("/{:hello}")

	holaWS.Route(holaWS.GET("/{name:*}").To(hola))
	helloWS.Route(helloWS.GET("/{name:*}").To(hello))
	restful.DefaultContainer.Add(holaWS)
	restful.DefaultContainer.Add(helloWS)

	holaRequest := httptest.NewRequest("GET", "/hola/Juan", nil)
	holaRespWriter := httptest.NewRecorder()
	restful.DefaultContainer.ServeHTTP(holaRespWriter, holaRequest)

	helloRequest := httptest.NewRequest("GET", "/hello/Juan", nil)
	helloRespWriter := httptest.NewRecorder()
	restful.DefaultContainer.ServeHTTP(helloRespWriter, helloRequest)

	fmt.Println(holaRequest.Method, holaRequest.URL.Path, "-", holaRespWriter.Result().Status, holaRespWriter.Body.String())
	fmt.Println(helloRequest.Method, helloRequest.URL.Path, "-", helloRespWriter.Result().Status, helloRespWriter.Body.String())
}

func hola(req *restful.Request, resp *restful.Response) {
	io.WriteString(resp, "hola "+req.PathParameter("name"))
}

func hello(req *restful.Request, resp *restful.Response) {
	io.WriteString(resp, "hello "+req.PathParameter("name"))
}
```
output:
```
GET /hola/Juan - 200 OK hola Juan
GET /hello/Juan - 404 Not Found 404: Page Not Found
```

**Comment by haitch** [comment]
when dispatching request go-restful have 2 phases: **detectWebService**, and **detectRoute**.
there is a **defect in detectWebService, where it ignores any regex pattern and treat them as matched with same score.**
so holaWS and helloWS get same score, thus first holaWS wins.
now when detectRoute, it does regex matching, for all route tokens, include webservice root path.
holaRequest get perfectly matched, belloRequest failed to match any route in holaWS.

**Comment by haitch** [comment]
did a deep dive, and proposed 2 PR:
- #548, simple change on variable name
- #549, fix misroute when dealing multiple webservice with regex

**Comment by emicklei** [comment]
thank you reporting this and suggestion the fixes, will have a look
