### ISSUE TITLE
why use copy instead of loop

### ISSUE THREAD

**Issue by Jerry-yz** [emicklei/go-restful#561]
why not use copy(result, c.webServices)
[loop](https://github.com/emicklei/go-restful/blob/v3/container.go#L414)
func (c *Container) RegisteredWebServices() []*WebService {
	c.webServicesLock.RLock()
	defer c.webServicesLock.RUnlock()
	result := make([]*WebService, len(c.webServices))
	for ix := range c.webServices {
		result[ix] = c.webServices[ix]
	}
	return result
}

**Comment by emicklei** [comment]
there was no particular reason for not using copy.
