### ISSUE TITLE
can find any doc about uncompatible in here?

### ISSUE THREAD

**Issue by Cod3er-ai** [emicklei/go-restful#565]
there is no release ，if somebody use some version before ，how can he fastly know the function or what he can't use in the latest version

**Comment by emicklei** [comment]
In order to use this package, no release other than a git tag is needed.  Currrent tag is v3.12.1

**Comment by emicklei** [comment]
a list of changes can be read here https://github.com/emicklei/go-restful/blob/v3/CHANGES.md

**Comment by emicklei** [comment]
i think this can be closed. re-open if needed
