### ISSUE TITLE
WriteHeader not being propegated into response without a WriteEntity call

### ISSUE THREAD

**Issue by jchenry** [emicklei/go-restful#94]
example: 

trying to return a 202 or 204 ( a response that will likely have no body, or explicitly have no body) WriteHeader would be called without a subsequent call to WriteEntry

In this case a 200 would be returned. this is wrong

Sending a header back without a response body should be allowed and the proper status code should be returned.

**Comment by pengux** [comment]
This also baffles me for a moment as I was using the Write method instead of WriteEntity, WriteAsJson etc. Was expecting the header to be written when using the Write method...

**Comment by emicklei** [comment]
sorry about that
